### ISSUE TITLE
ThinkingSphinx::QueryExecutionError: index 'user_core' does not support INSERT (enabled=0)

### ISSUE THREAD

**Issue by development-amold** [pat/thinking-sphinx#1000]
I am using Thinking Sphinx version: Sphinx 2.2.5-id64-release (r4825) with real time indexes.
When I used rake ts:regenerate then it is giving following errors: 
1. ThinkingSphinx::QueryExecutionError: index 'user_core' does not support INSERT (enabled=0)
2. Mysql2::Error: index 'user_core' does not support INSERT (enabled=0)

I have read all the docs but didn't resolve problem.

**Comment by pat** [comment]
Hmm. Not entirely sure what the cause of this problem is…

When you installed Sphinx, did you compile it with support for MySQL? And are you switching from SQL-backed indices to real-time indices? Or is this the first time adding Sphinx to this app?

**Comment by development-amold** [comment]
Yes, I followed sll above mentioned steps.  But, When I removed
characterset- UTF 8 option from thinkingsphinx.yml then its working well.
But, still not getting the exact cause.

**Comment by pat** [comment]
If you start the Sphinx daemon manually, then the output may give you a better idea of what the problem might be? UTF-8 is enabled by default in 2.2.x releases of Sphinx, I believe, but that should just output a warning, not actually cause any problems.

`searchd --config config/development.sphinx.conf`

**Comment by xtrasimplicity** [comment]
In case anyone stumbles upon this in the future, I was able to resolve this in one of my projects by deleting my Sphinx configuration file and rebuilding it via `rake ts:rebuild`. :)
