### ISSUE TITLE
Wildcard search seems to be broken with PostgreSQL

### ISSUE THREAD

**Issue by sebastianrjay** [pat/thinking-sphinx#1002]
I'm using ThinkingSphinx 3.2.0.

I tried using the syntax described [here](http://freelancing-gods.com/thinking-sphinx/searching.html#star) and [here](https://github.com/pat/thinking-sphinx/issues/899). Regular search works perfectly (where the search query exactly matches a whole word), but incomplete searches never match properly. It seems that neither automatically wildcarded nor manually wildcarded searches work. (E.g. 'Gm' does not match 'Gm7'. 'Gm*' also does not match 'Gm7'.)

My Rails controller code:

```ruby
class Api::TracksController < ApplicationController
    # ...
    def search
        query = ThinkingSphinx::Query.wildcard(ThinkingSphinx::Query.escape(params[:query]))
        @tracks = Track.search query

        render json: @tracks
    end
end
```

My Rails index file code:
```ruby
ThinkingSphinx::Index.define :track, with: :real_time do
  # fields
  indexes name, :sortable => true
  indexes composer.username, :as => :composer, :sortable => true

  # attributes
  has created_at, :type => :timestamp
end
```

My schema:

```ruby
ActiveRecord::Schema.define(version: 20150706044710) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  # ...
  create_table "tracks", force: :cascade do |t|
    t.string   "name",       null: false
    t.json     "roll"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id",    null: false
  end
end
```

Am I missing something? NOTE: I am using PostgreSQL and have run `rake ts:rebuild` and `rake ts:regenerate`.

Any help would be appreciated. I found this library to be incredibly easy to set up and a joy to use in general, except that this (debatably crucial) feature appears not to work.

**Comment by pat** [comment]
Hi Sebastian

Your controller code looks fine to me. Have you got `min_infix_len` or `min_prefix_len` set in `config/thinking_sphinx.yml`? Certainly, the docs could be more clear about tying this into wildcards (though it is mentioned). Once you make that change, then run `rake ts:regenerate`.

Of course, if you already had those settings there, then I'm a bit more confused as to what the problem might be! Which version of Sphinx are you using?

Also: `rake ts:rebuild` is only useful if you're using SQL-backed indices - there's no point in running it for real-time indices.

Cheers

Pat

**Comment by sebastianrjay** [comment]
Hi Pat,

Thanks for the tip on `min_infix_len`! I've also enabled the `expanded_keywords` option, as described [here](http://sphinxsearch.com/docs/current.html#conf-expand-keywords).

My config/thinking_sphinx.yml file now looks like this:

```yaml
development:
  enable_star: true
  expand_keywords: 1
  indexed_models:
    - Track
  min_infix_len: 2
production:
  enable_star: true
  expand_keywords: 1
  min_infix_len: 2
test:
  enable_star: true
  expand_keywords: 1
  min_infix_len: 2
```

My development.sphinx.conf file:
```configuration

indexer
{
}

searchd
{
  listen = 127.0.0.1:9306:mysql41
  log = /Users/sebastianjay/WebApps/Organ/log/development.searchd.log
  query_log = /Users/sebastianjay/WebApps/Organ/log/development.searchd.query.log
  pid_file = /Users/sebastianjay/WebApps/Organ/log/development.sphinx.pid
  workers = threads
  binlog_path = /Users/sebastianjay/WebApps/Organ/tmp/binlog/development
}

index track_core
{
  type = rt
  path = /Users/sebastianjay/WebApps/Organ/db/sphinx/development/track_core
  docinfo = extern
  min_infix_len = 2
  enable_star = 1
  expand_keywords = 1
  rt_field = sphinx_internal_class_name
  rt_field = name
  rt_field = composer
  rt_attr_uint = sphinx_deleted
  rt_attr_bigint = sphinx_internal_id
  rt_attr_timestamp = created_at
  rt_attr_string = sphinx_internal_class
  rt_attr_string = name_sort
  rt_attr_string = composer_sort
}

index track
{
  type = distributed
  local = track_core
}
```

Example Sphinx SQL query:
```sql
SELECT * FROM `track_core` WHERE MATCH('*short* *name*') AND `sphinx_deleted` = 0 LIMIT 0, 20
```

Neither wildcard search nor substring search are working, even though the SQL surrounds each space-separated string with `*` characters. I've also tried activating `enable_star` and `min_infix_len` without `expand_keywords`. I'm still able to match individual complete words, or consecutive and non-consecutive sets of complete words. But I can't match partial words, with or without wildcards.

Any other tips you have would be greatly appreciated.

Thanks!

**Comment by sebastianrjay** [comment]
An update:

It looks like the problem may be that PostgreSQL does not support `MATCH` queries. MySQL clearly supports the `MATCH` query, as documented [here](https://dev.mysql.com/doc/refman/5.5/en/fulltext-search.html). In a [Google search for `postgresql match`](https://www.google.com/search?q=postgresql+match&oq=postgresql+match&aqs=chrome..69i57j69i60.2494j0j7&sourceid=chrome&ie=UTF-8), none of the results describe a `MATCH` statement, but `LIKE`, `SIMILAR TO` and `SUBSTRING` statements are documented [here](https://www.postgresql.org/docs/9.3/static/functions-matching.html).

**Comment by pat** [comment]
The MATCH query is being run against Sphinx, not PostgreSQL - so that's not part of the problem here. Indeed, with real-time indices, I don't think the type of database you're using has any impact at all.

The `indexer` section defaults to empty in your configuration file, that's nothing to be alarmed about, completely normal.

Which version of Sphinx are you using? `enable_star` was only needed for older versions of Sphinx (hence not mentioning it previously)

**Comment by sebastianrjay** [comment]
I'm using ThinkingSphinx 3.2.0 with Sphinx 2.2.10-id64-release (2c212e0)

**Comment by pat** [comment]
Okay… took a bit of hunting in some test projects to get this working for myself.

* Stop Sphinx using `rake ts:stop`
* Confirm Sphinx is actually stopped (no searchd processes listed using `ps aux | grep searchd`)
* Delete existing Sphinx index data: `rm -rf db/sphinx/development`
* Run `rake ts:regenerate`

You _do_ need `min_infix_len`, you don't need `enable_star`. Also, unrelated but you don't need the `indexed_models` setting - that's a feature from TS v1/v2 that was not brought across to TS v3 due to internal changes that made it unnecessary.

Hope this gets things working for you!

**Comment by sebastianrjay** [comment]
That fixed it. Thanks Pat!

**Comment by pat** [comment]
Great to hear :)
