### ISSUE TITLE
Error in big query in rake task ts:generate 

### ISSUE THREAD

**Issue by belov** [pat/thinking-sphinx#1003]
I have many articles with big text body. Task ts:generate use find_in_batches 
to generate query https://github.com/pat/thinking-sphinx/commit/550fc11e4d091e187dcb9753f3c33fafc272221a 
Big texts multiply by 1000 times - error and stop indexing. 
Project demonstarate this https://github.com/belov/regenerate_rt_index

I try:
1. Change options for sphinx in thinking_sphinx.yml - no result.
2. Change default size to 50 for find_in_batches. - Working, but has side effect.

May be connection by mysql2 driver needed for configuration.

ENV: ubuntu 16-04, Sphinx 2.2.11-id64-release (95ae9a6)

**Comment by pat** [comment]
Appreciate the test project to help debug this! Thanks :)

I'm thinking of adding in a configuration option to customise the default batch size - but, you've mentioned it has a side effect? What's the effect?

**Comment by pat** [comment]
Just pushed some changes:

* Thinking Sphinx now checks for statements that are too long (from my trial-and-error checks, seems the maximum allowed length is 2^23 - 1), and raises an exception of its own rather than sending the statement through to Sphinx.
* You can configure `batch_size` in `config/thinking_sphinx.yml` (per environment) to reduce things down to something that works better with your dataset.

Can be used via the following in your Gemfile:

```ruby
gem 'thinking-sphinx', '~> 3.2.0',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '94f5ecdd19'
```

**Comment by belov** [comment]
First, thank you all contributors and you Pat for this project!!! It's cool gem!
And second, thank you for fast answer and fix this issue! All work fine!

PS: Side effect - mmm... i monkeypatch  AR:Batches#find_in_batches(default batch_size 1000 -> 50) and several script in my project changed not good. It's was day not good solutions. We will not remember it :) 

For future may be made "batch_size" option of "ThinkingSphinx::Index.define"?
Example - popular news site:
We have Article model: Small count, huge content - need small batch_size
We have Comment model: Huge count, small content - need big batch_size

**Comment by pat** [comment]
Great to know the changes are working well for you :)

I did think about it being a per-index option as well - was more work, so I've left it for the moment. Patches are welcome though!
