### ISSUE TITLE
Sinatra setup issues

### ISSUE THREAD

**Issue by sbayona** [pat/thinking-sphinx#1007]
Ruby 2.3.1
Sinatra 1.4.7
Thinking Sphinx 3.2.0
Sphinx 2.2.11

File structure:
```
/app
  /indices
    watch_index.rb
  /models
    watch.rb
/config
  production.sphinx.conf
  thinking_sphinx.yml
...
```

I follow the Sinatra instructions at http://freelancing-gods.com/thinking-sphinx/installing_thinking_sphinx/sinatra.html

production.sphinx.conf: https://gist.github.com/sbayona/3b7b3c03da718c2ca11fa8340a50bd4b
First strange thing you'll notice is that it duplicates the index watch_core block.

thinking_sphinx.yml https://gist.github.com/sbayona/59d509f4edb5dee0d0fb14510d3fb146

watch_index.rb https://gist.github.com/sbayona/fd336fe5abdb139f4f4ba7936b2aa999

When I run ``rake ts:regenerate``

```
Generating index files for watch_core
rake aborted!
ThinkingSphinx::ConnectionError: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - REPLACE INTO watch_core (id, `sphinx_internal_class_name`, `name`, `reference`, ....
```

Keep in mind the data is on a Postgres DB.

**Comment by sbayona** [comment]
btw, I can connect to mysql from the terminal without a problem.

```
mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.7.14 Homebrew
```

**Comment by sbayona** [comment]
Also, running ``rake ts:index`` returns:
Generating configuration to /Users/sergiobayona/Code/watch_specs_service/config/production.sphinx.conf
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/Users/sergiobayona/Code/watch_specs_service/config/production.sphinx.conf'...
ERROR: section 'watch_core' (type='index') already exists in /Users/sergiobayona/Code/watch_specs_service/config/production.sphinx.conf line 84 col 1.
FATAL: failed to parse config file '/Users/sergiobayona/Code/watch_specs_service/config/production.sphinx.conf'

**Comment by pat** [comment]
Hi Sergio

The Sphinx server uses the MySQL protocol - so, while you're using PostgreSQL, Thinking Sphinx is connecting to Sphinx using the mysql2 gem. The error has nothing to do with your MySQL database. Also, `rake ts:index` isn't useful when you're using real-time indices. However, the fact that Sphinx doesn't like the generated configuration file explains why TS cannot connect to Sphinx - it wasn't able to start the daemon.

The duplication of the index definition is certainly odd, though! All the code you've shared looks right to me.

Do you have any code that interacts with Thinking Sphinx while your app boots up? If so, could you share that? Otherwise, I'll try to put together a test app to see if I can reproduce the issue.

**Comment by pat** [comment]
Two things further to this: I've set up a simple test app, and am not seeing the index duplication issue: https://github.com/pat/ts-sinatra - so I'm especially curious to hear how what you might be doing is different to help figure out the cause of the problem.

Also, one mistake I have spotted in what you've shared: in `config/thinking_sphinx.yml`, you should remove the `port` setting for each environment. It's meant to be an integer value of the specific port you want the Sphinx daemon to use - _but_ this is a legacy setting for Sphinx's old binary protocol, so just remove it form each environment in that file.

TS v3 uses the SphinxQL/mysql41 protocol, and so you can use the `mysql41` setting instead to determine each ports (which is perhaps where you got confused?). e.g.

```yaml
development:
  mysql41: 9306
```

Port 9306 is the default for the SphinxQL protocol, so it may be worth using 9307 or something else for the test environment (if you're using Sphinx in your tests).

Still, I don't believe that's related to the problem we're dealing with here!

**Comment by sbayona** [comment]
I removed the port setting and it now runs fine. However, whenever I run the `ts:regenerate` task the config has those duplicate entries.

**Comment by pat** [comment]
Can you share the full output of `rake ts:regenerate`?
