### ISSUE TITLE
indexes with a count

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1009]
Hi,

I have an index with a count, but it lists the index as a string in mysql:

```
  indexes "count(0)", as: :present_user_count, type: :integer, sortable: true
```

```
| present_user_count        | string    |
```

Any ideas?

**Comment by atomical** [comment]
Changed to:

``` 
  join audience.users
  has "count(mobile_offer_audience_users.mobile_offer_audience_id =
  mobile_offer_audiences.id)", as: :present_user_count, type: :integer
```

Now it is represented as an integer, but it still isn't sorting properly.

**Comment by pat** [comment]
`has` is definitely the right method - if you want the value to be treated as an integer, it must be an attribute, not a field.

I'm not sure the SQL snippet is correct, though? Would the comparison return a boolean value, or a 0/1 value? Is that what you're hoping to count? Have you tried that within a SQL statement and confirmed the right values are being returned?

**Comment by atomical** [comment]
Is there a way to dump the SQL statements that the indexer is running?

**Comment by pat** [comment]
In the generated Sphinx configuration file, you'll find a `sql_query` setting for each source (which is paired to an index). Within the WHERE clause there are variables for a window on the primary key - you'll need to change those for real values (or remove those conditions if you want _all_ records returned - likely that'll be very slow though!)
