### ISSUE TITLE
Sorting by custom model methods

### ISSUE THREAD

**Issue by dkey94** [pat/thinking-sphinx#1013]
Hi,
let's say I have a Specialist model with a custom boolean method:

`def is_awarded?
      Specialist.awarded.include?(self)
  end`

How can I sort my ThinkingSphinx results by this method? Awarded specialists first.

Thanks!

**Comment by pat** [comment]
If you're using real-time indices, then you could have this method as an attribute:

```ruby
has is_awarded?, :as => :is_awarded, :type => :boolean
```

And then you can sort by it:

```ruby
Specialist.search 'foo', :order => 'is_awarded DESC'
```

Sphinx stores boolean values as 0 and 1 integers, so, DESC should ensure the awarded specialists are first.

_But_ if you're using SQL-backed indices, then this is trickier… you'd need to somehow translate that method into a corresponding SQL snippet to use when defining an attribute. I'm not sure if this is even possible - it very much depends on how your `awarded` method is defined and whether there's a SQL equivalent.

**Comment by dkey94** [comment]
Thanks for your help, you're really fast!
I will try it with real-time indices. I've been using SQL-backed indices.

**Comment by dkey94** [comment]
I don't know why, but I get:

> rake aborted!
> ThinkingSphinx::SphinxError: unknown column: 'is_awarded'

**Comment by dkey94** [comment]
Solution was to remove db/sphinx/development.

**Comment by pat** [comment]
Just added a note to the docs about this: http://freelancing-gods.com/thinking-sphinx/real_time.html
