### ISSUE TITLE
undefined method `unscoped' for Object:Class

### ISSUE THREAD

**Issue by jvkiran** [pat/thinking-sphinx#1015]
gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:59:in `block in results_for_models': undefined method`unscoped' for Object:Class (NoMethodError)
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:57:in `each'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:57:in`inject'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:57:in `results_for_models'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:20:in`call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:6:in `block in call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:5:in`each'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/active_record_translator.rb:5:in `call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/inquirer.rb:19:in`call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/geographer.rb:11:in `call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/sphinxql.rb:14:in`call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/middlewares/stale_id_filter.rb:10:in `call'
    from gems/middleware-0.1.0/lib/middleware/runner.rb:31:in`call'
    from gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
    from gems/thinking-sphinx-3.1.2/lib/thinking_sphinx/search.rb:67:in`populate'
    **from app/controllers/banquet_halls_controller.rb:508:in `load_filters'**
    **from app/controllers/banquet_halls_controller.rb:465:in `meeting_capacity_filter'**
    from gems/actionpack-3.2.18/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    from gems/actionpack-3.2.18/lib/abstract_controller/base.rb:167:in`process_action'
    from gems/actionpack-3.2.18/lib/action_controller/metal/rendering.rb:10:in `process_action'
    from gems/actionpack-3.2.18/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:480:in `_run__3753153102422473802__process_action__1519032541872126632__callbacks'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in`__run_callback'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from gems/actionpack-3.2.18/lib/abstract_controller/callbacks.rb:17:in `process_action'
    from gems/actionpack-3.2.18/lib/action_controller/metal/rescue.rb:29:in`process_action'
    from gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    from gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in`block in instrument'
    from gems/activesupport-3.2.18/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in`instrument'
    from gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
    from gems/actionpack-3.2.18/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
    from gems/activerecord-3.2.18/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:34:in`block in process_action'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:268:in `block in perform_action_with_newrelic_trace'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/method_tracer.rb:240:in`trace_execution_scoped'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:263:in `perform_action_with_newrelic_trace'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:33:in`process_action'
    from gems/actionpack-3.2.18/lib/abstract_controller/base.rb:121:in `process'
    from gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:45:in`process'
    from gems/actionpack-3.2.18/lib/action_controller/metal.rb:203:in `dispatch'
    from gems/actionpack-3.2.18/lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
    from gems/actionpack-3.2.18/lib/action_controller/metal.rb:246:in `block in action'
    from gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:73:in`call'
    from gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
    from gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:36:in`call'
    from gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
    from gems/journey-1.0.4/lib/journey/router.rb:56:in`each'
    from gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
    from gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:608:in`call'
    from gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
    from gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in`call'
    from gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
    from gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in`call'
    from gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
    from gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in`call'
    from bundler/gems/omnicontacts-83d38cf720f4/lib/omnicontacts/middleware/base_oauth.rb:41:in `call'
    from bundler/gems/omnicontacts-83d38cf720f4/lib/omnicontacts/middleware/base_oauth.rb:41:in`call'
    from bundler/gems/omnicontacts-83d38cf720f4/lib/omnicontacts/middleware/base_oauth.rb:41:in `call'
    from bundler/gems/omnicontacts-83d38cf720f4/lib/omnicontacts/middleware/base_oauth.rb:41:in`call'
    from bundler/gems/omnicontacts-83d38cf720f4/lib/omnicontacts/builder.rb:27:in `call'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/rack/error_collector.rb:8:in`call'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/rack/agent_hooks.rb:14:in `call'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/rack/browser_monitoring.rb:12:in`call'
    from gems/rack-mobile-detect-0.4.0/lib/rack/mobile-detect.rb:164:in `call'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:140:in`forward'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:249:in `fetch'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:189:in`lookup'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:66:in `call!'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:51:in`call'
    from gems/rack-1.4.7/lib/rack/deflater.rb:13:in `call'
    from gems/galetahub-simple_captcha-0.1.5/lib/simple_captcha/middleware.rb:20:in`call'
    from gems/client_side_validations-3.1.4/lib/client_side_validations/middleware.rb:18:in `call'
    from gems/warden-1.2.4/lib/warden/manager.rb:35:in`block in call'
    from gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
    from gems/warden-1.2.4/lib/warden/manager.rb:34:in`call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
    from gems/rack-1.4.7/lib/rack/etag.rb:23:in`call'
    from gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/head.rb:14:in`call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/flash.rb:242:in`call'
    from gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
    from gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in`call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/cookies.rb:341:in `call'
    from gems/activerecord-3.2.18/lib/active_record/query_cache.rb:64:in`call'
    from gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `_run__1859333593928826372__call__637865999128437116__callbacks'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in`__run_callback'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
    from gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
    from gems/railties-3.2.18/lib/rails/rack/logger.rb:32:in `call_app'
    from gems/railties-3.2.18/lib/rails/rack/logger.rb:18:in`call'
    from gems/actionpack-3.2.18/lib/action_dispatch/middleware/request_id.rb:22:in `call'
    from gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in`call'
    from gems/rack-contrib-1.1.0/lib/rack/contrib/runtime.rb:18:in `call'
    from gems/activesupport-3.2.18/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
    from gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:140:in`forward'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:249:in `fetch'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:189:in`lookup'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:66:in `call!'
    from gems/rack-cache-1.5.1/lib/rack/cache/context.rb:51:in`call'
    from gems/railties-3.2.18/lib/rails/engine.rb:484:in `call'
    from gems/railties-3.2.18/lib/rails/application.rb:231:in`call'
    from gems/rack-1.4.7/lib/rack/urlmap.rb:64:in `block in call'
    from gems/rack-1.4.7/lib/rack/urlmap.rb:49:in`each'
    from gems/rack-1.4.7/lib/rack/urlmap.rb:49:in `call'
    from gems/rack-1.4.7/lib/rack/commonlogger.rb:33:in`call'
    from gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
    from gems/rack-1.4.7/lib/rack/chunked.rb:43:in`call'
    from gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
    from gems/unicorn-4.6.1/lib/unicorn/http_server.rb:552:in`process_client'
    from gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:52:in `process_client'
    from gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:92:in`process_client'
    from gems/unicorn-4.6.1/lib/unicorn/http_server.rb:632:in `worker_loop'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:18:in`call'
    from gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:18:in `block (4 levels) in <top (required)>'
    from gems/unicorn-4.6.1/lib/unicorn/http_server.rb:500:in`spawn_missing_workers'
    from gems/unicorn-4.6.1/lib/unicorn/http_server.rb:511:in `maintain_worker_count'
    from gems/unicorn-4.6.1/lib/unicorn/http_server.rb:277:in`join'
    from gems/unicorn-4.6.1/bin/unicorn:126:in `<top (required)>'
    from bin/unicorn:23:in`load'
    from bin/unicorn:23:in `<main>'

**Comment by pat** [comment]
Can you share the following details:

* The version of Sphinx you're using
* The search request you're making in your controller
* The index definitions for the models being searched on

Thanks!

**Comment by jvkiran** [comment]
**Sphinx version**: shared/bundle/ruby/1.9.1/gems/thinking-sphinx-3.1.2

**Search request** banquet_halls_controller#meeting
if params[:query].present? || params[:term].present?
      search_conditions = {:status => "published", :city => @current_city.name}
      search_conditions.merge!(:locality      =>  params[:term]) if params[:term].present?
      search_conditions.merge!(:name_ocasion => params[:query]) if params[:query].present?
      @establishments = Establishment.search(:per_page => 10, :page => params[:page] || 1, :sql => {:include => [:locality, :facilities, :amenities, :establishment_type, :venues, :packages]},:conditions => search_conditions, :order=>sort_order).populate
    else
      **@establishments = Establishment.search(:per_page => 10, :page => params[:page] || 1, :sql => {:include => [:locality, :facilities, :amenities, :establishment_type, {:venues => :venue_capacities}, :packages, :est_cost_ranges]},:conditions => conditions, :with => with, :order=> sort_order, :order => 'rand()').populate**
    end
    @lat_lng = @establishments.collect {|p|  [loc: [p.latitude, p.longitude], title: p.name] if p.name? & p.latitude?}.compact.flatten
    @establishment_count = @establishments.total_entries
    **if params["action"].split("_")[0] == "meeting"** #line 508, as per log fails at this line.
      find_meetings_headings
    else
      find_banquets_headings
    end

**indices definition** 

ThinkingSphinx::Index.define :establishment, :with => :active_record, :delta => true do

  indexes name
  indexes locality.name, :as => :locality, :sortable => true, :facet => true
  indexes locality.city.name, :as => :city
  indexes :status, :facet => true
  indexes [name, venues.best_for_hosting], :as => :name_ocasion
  indexes facilities.name, :as => :facility, :sortable => true
  indexes amenities.name, :as => :amenity_name
  indexes establishment_type.name, :as => :establishment_type, :sortable => true, :facet => true
  indexes venues.best_for_hosting, :as => :best_for_hosting, :sortable => true, :facet => true
  indexes packages.package_range, :as => :package_range, :sortable => true, :facet => true
  indexes available_from, :as => :start_time, :sortable => true
  indexes venues.min_group_size, :as => :min_group_size, :sortable => true
  indexes venues.name, :as => :venue_name, :sortable => true
  indexes est_cost_ranges.range, as: :price_range, :sortable => true, :facet => true

  indexes "DATE(establishments.created_at)", :as => :creation_date, :sortable => true
  
  has facilities.id, :as => :facility_id, :facet => :true
  has amenities.id, :as => :amenity_id, :facet => :true
  has establishment_type.id, :as => :establishment_type_id, :facet => true
  has est_cost_ranges.id, :as => :est_cost_range_id, :facet => true

  has venues.charge_per_hour, :as => :charge_per_hour, :sortable => true, :facet => true
  has venues.venue_capacities.range, :as => :capacity_range, :sortable => true, :facet => true

  has latitude,  :as => :latitude,  :type => :float
  has longitude, :as => :longitude, :type => :float

  has :created_at
end

Thanks for the quick reply.

**Comment by grouptable** [comment]
--- crashed SphinxQL request dump --- is shown in log records.

**Comment by pat** [comment]
Thanks for all of those details. The fact that Sphinx is crashing suggests the problem may not be in your code or mine, but in Sphinx itself? You're using Sphinx 2.2.6 - can you upgrade to 2.2.11 and see if that helps?

**Comment by pat** [comment]
Marking this issue as closed due to inactivity. Further comments are still welcome if the problem remains, though!
