### ISSUE TITLE
searching for utf8

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1016]
Hi,

I'm storing an emoji in a utf8 column (utf8mb4_bin encoding). When I search for it it's not matching: 

`SELECT * FROM `feedback_response_type_core`, `feedback_response_type_delta` WHERE MATCH('😃') AND `sphinx_deleted` = 0 ORDER BY `id` desc LIMIT 0, 20 OPTION max_matches=10000` 

Could this have something to do with the encoding of feedback_response_type_core?

**Comment by pat** [comment]
Hi Adam,

Which version of Sphinx are you using? I know recent versions (maybe 2.2.x onwards?) use utf8 _only_ - so I'd expect them to be fine? But earlier ones configuration is required for utf8… though earlier releases of TS did set that up for you.

**Comment by atomical** [comment]
Sphinx 2.2.11-id64-release (95ae9a6)

```
mysql> select emoji from feedback_response_type_core;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: *** NONE ***

+-------+
| emoji |
+-------+
| 😄      |
| 😐      |
| 😞      |
+-------+
3 rows in set (0.02 sec)```

It looks like the correct value is in there, but something about the query must be wrong?

**Comment by pat** [comment]
Hrm. Is emoji also a field, or only an attribute?

**Comment by atomical** [comment]
```mysql> describe feedback_response_type_core;
+-----------------------------+-----------+
| Field                       | Type      |
+-----------------------------+-----------+
| id                          | bigint    |
| name                        | field     |
| sample_detail_feedback_text | field     |
| emoji                       | field     |
| name                        | string    |
| sample_detail_feedback_text | string    |
| emoji                       | string    |
| sphinx_internal_id          | uint      |
| sphinx_internal_class       | string    |
| sphinx_deleted              | uint      |
| created_at                  | timestamp |
| updated_at                  | timestamp |
+-----------------------------+-----------+```

**Comment by pat** [comment]
I'm at a loss to what the cause here is. Perhaps it's worth asking on [the Sphinx forum](http://sphinxsearch.com/forum/)?

**Comment by graaff** [comment]
My assumption is that this is caused by the hard-coded "utf8" encoding that thinking sphinx sets in the mysql adapter. Contrary to the name this isn't a fully utf8 compatible encoding because it only supports up to 3 byte code points. The "utf8mb4" encoding also supports 4 byte code points and that is needed to work with e.g. emoji. My guess for this bug is that the emoji are never read from the database and thus not indexed because of the hard-coded utf8 encoding.

We are currently working around this with 
```
  sql_query_pre:
    - SET NAMES utf8mb4
```

in thinking sphinx 3.1, but as I'm investigating updating to a newer version (3.4 atm) I see that it now inserts SET NAMES utf8 after the sql_query_pre statement, negating our workaround.

**Comment by pat** [comment]
Thanks Hans, I wasn't aware that utf8 in MySQL is not true utf8.

I'd expect in TS v3.4 and possibly back to v3.1 you should be able to add `set_property :utf8? => false` within each index definition, plus the custom `sql_query_pre` as you've set, and should work well.

I've also just pushed a commit to the `develop` branch which allows configuration of the custom encodings via `mysql_encoding: utf8mb4` in `config/thinking_sphinx.yml`. In the next significant release I'll change the default to utf8mb4.

**Comment by graaff** [comment]
Thanks!

**Comment by DrobyshevAlex** [comment]
Hello! Help me please :) I can't set utf8mb4...

i create file thinking_sphinx.yml
```
production:
  workers: 2
  mysql_encoding: utf8mb4
```

I added 'workers' for test generate config.

after ts:configure i have 

```
searchd
{
  listen = 127.0.0.1:9306:mysql41
  log = /var/www/xxx/log/production.searchd.log
  query_log = /var/www/xxx/log/production.searchd.query.log
  pid_file = /var/www/xxx/log/production.sphinx.pid
  workers = 2
  binlog_path = /var/www/xxx/tmp/binlog/production
}

index article_core
{
  type = rt
  path = /var/www/xxx/db/sphinx/production/article_core
  docinfo = extern
  morphology = stem_ru
  dict = keywords
  min_infix_len = 2
  expand_keywords = 1
  rt_field = title
  rt_field = description
  rt_field = meta_keywords
  rt_field = meta_description
  rt_field = body
  rt_attr_uint = sphinx_deleted
  rt_attr_bigint = sphinx_internal_id
  rt_attr_timestamp = created_at
  rt_attr_timestamp = updated_at
  rt_attr_string = sphinx_internal_class
  rt_attr_string = title_sort
}
```

what am I doing wrong?

**Comment by pat** [comment]
@DrobyshevAlex the `utf8mb4` setting is only relevant if you're using SQL-backed indices with MySQL. You're using real-time indices, so there shouldn't be a problem to begin with?

Or, if you are using MySQL for your database, perhaps it's an encoding issue for all database communication, not just between your app and Sphinx? Can you talk us through the problem you were hoping to fix with this setting?

**Comment by DrobyshevAlex** [comment]
I get an error after executing the command

`rake ts:rebuild`

> mysql gone away

query size ~ 12Mb.

mysql Percona setting

```
[mysqld]
wait_timeout = 600

# GENERAL #
user                           = mysql
default-storage-engine         = InnoDB

# MyISAM #
key-buffer-size                = 128M
myisam-recover-options         = FORCE,BACKUP

# SAFETY #
mysqlx_max_allowed_packet      = 4096M
max_allowed_packet             = 4096MB
max-allowed-packet             = 4096M
max-connect-errors             = 1000000

tmp-table-size                 = 128M
max-heap-table-size            = 128M
#query-cache-type               = ON
#query-cache-size               = 32MB
max-connections                = 500
thread-cache-size              = 50
open-files-limit               = 10000
table-definition-cache         = 1024
table-open-cache               = 2048

# INNODB #
innodb-flush-method            = O_DIRECT
innodb-log-files-in-group      = 2
innodb-log-file-size           = 512M
innodb-flush-log-at-trx-commit = 1
innodb-file-per-table          = 1
innodb-buffer-pool-size        = 46G
```

> RAILS_ENV=production rake ts:rebuild --trace
> ** Invoke ts:rebuild (first_time)
> ** Invoke ts:stop (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute ts:stop
> Sphinx 3.0.2 (commit 2592786)
> Copyright (c) 2001-2018, Andrew Aksyonoff
> Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
> 
> using config file '/var/www/xxx.com/config/production.sphinx.conf'...
> WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: 1 more warnings skipped.
> stop: successfully sent SIGTERM to pid 22144
> Stopped searchd daemon (pid: 22144).
> ** Invoke ts:clear (first_time)
> ** Invoke ts:sql:clear (first_time)
> ** Invoke environment 
> ** Execute ts:sql:clear
> ** Invoke ts:rt:clear (first_time)
> ** Invoke environment 
> ** Execute ts:rt:clear
> ** Execute ts:clear
> ** Invoke ts:configure (first_time)
> ** Invoke environment 
> ** Execute ts:configure
> Generating configuration to /var/www/xxx.com/config/production.sphinx.conf
> ** Invoke ts:sql:index (first_time)
> ** Invoke environment 
> ** Execute ts:sql:index
> ** Invoke ts:start (first_time)
> ** Invoke environment 
> ** Execute ts:start
> Sphinx 3.0.2 (commit 2592786)
> Copyright (c) 2001-2018, Andrew Aksyonoff
> Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
> 
> using config file '/var/www/xxx.com/config/production.sphinx.conf'...
> WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
> WARNING: 1 more warnings skipped.
> listening on 127.0.0.1:9306
> precaching index 'article_core'
> WARNING: dict=keywords and prefixes and morphology enabled, forcing index_exact_words=1
> precaching index 'news_post_core'
> WARNING: dict=keywords and prefixes and morphology enabled, forcing index_exact_words=1
> precaching index 'service_core'
> WARNING: dict=keywords and prefixes and morphology enabled, forcing index_exact_words=1
> precached 3 indexes in 0.001 sec
> WARNING: No extra index definitions found in data folder
> Started searchd successfully (pid: 27535).
> ** Invoke ts:rt:index (first_time)
> ** Invoke environment 
> ** Execute ts:rt:index
> Generating index files for article_core
> rake aborted!
> ThinkingSphinx::SphinxError: MySQL server has gone away - REPLACE INTO article_core (id, `title`, `d

**Comment by DrobyshevAlex** [comment]
Sorry... I was looking for a solution for two days.

After the publication of the question I thought maybe it is a sphinx return the error. I create thinking_sphinx.yml with code

```
production:
  max_packet_size: 128M
```
and the error is gone :)
