### ISSUE TITLE
Detection of NOT operator while using stars

### ISSUE THREAD

**Issue by alexkuebo** [pat/thinking-sphinx#1017]
Hi,

I got a query like `S1-5` and when setting star: true in a query, it gets a query like this: `*S1*-*5*`.
In my opinion it has to get a query like this: `*S1-5*`. Am I wrong or could this please get fixed?

**Comment by pat** [comment]
Hi Alex

Hyphens are special characters in Sphinx's query syntax (the logical NOT), which is why Thinking Sphinx treats it as a query term separator. If you want to change the behaviour of this, you'll need to take a slightly different approach to wildcarding your query:

```ruby
query = "S1-5"
query = ThinkingSphinx::Query.wildcard query, /[\p{Word}-]+/ # default is /\p{Word}+/
Model.search query
```

**Comment by pat** [comment]
Or also, a slightly simpler approach: you can pass the regex pattern in as the `:star` option:

```ruby
Model.search "S1-5", :star => /[\p{Word}-]+/
```

**Comment by alexkuebo** [comment]
Hi Pat,

thank you very much, works great :)

**Comment by pat** [comment]
Great to hear … and I only just noticed the title of this issue, where you'd already noted that the logical NOT was part of it. Sorry for explaining what you already knew!
