### ISSUE TITLE
Geodistance search not working

### ISSUE THREAD

**Issue by dikey94** [pat/thinking-sphinx#1020]
Hello again, 
this time i'm trying to repair my geodistance filter. It use to work but during last 2 weeks i've made some changes in the code.

From the beggining...
Specialist index:
```
ThinkingSphinx::Index.define :specialist, with: :real_time do
  indexes :name
  indexes description
  indexes :service_names
  has is_awarded?, as: :is_awarded, type: :boolean
  has created_at, as: :join_date, type: :timestamp
  has number_of_comments, as: :number_of_comments, type: :integer
  has integer_ratings, as: :integer_ratings, type: :integer
  has float_ratings, as: :float_ratings, type: :float
  has comments_text, as: :comments_text, type: :string
  has ratings, as: :ratings, type: :float
  has 'RADIANS(latitude)', as: :latitude, type: :float
  has 'RADIANS(longitude)', as: :longitude, type: :float
  has services.ids, as: :service_ids, multi: true, type: :integer
  has places_text, as: :places_text, type: :string
  has full_address, as: :full_address, type: :string
  has random_comment, as: :random_comment, type: :string
end
```

Latitude and longitude are stored in DB in degrees.

First problem what I have is I can't properly generate indexes. Each time I remove db/sphinx/development directory and run rails ts:regenerate it stucks on "fsevent_watch <- ruby bin/rails ts:regenerate". I've been waiting over 10 minutes and nothing. I have to stop the task and run again "rails ts:regenerate". Then it takes about 5s and I get:

> searchd is not currently running.
> Stopped searchd daemon (pid: 4523).
> Generating configuration to /Users/dk/Desktop/rails/xyz/config/development.sphinx.conf
> Started searchd successfully (pid: 4691).
> Generating index files for specialist_core
> ...

Another problem is when I'm filtering by geo-position I get no results.

**Comment by dikey94** [comment]
Sample Sphinx Query:

>   Sphinx Query (1.0ms)  SELECT GEODIST(0.8737929831039081, 0.34810556849908936, latitude, longitude) AS geodist, * FROM `specialist_core` WHERE `geodist` BETWEEN 0.0 AND 25000.0 AND `sphinx_deleted` = 0 ORDER BY `is_awarded` DESC, `number_of_comments` DESC LIMIT 0, 15
>   Sphinx  Found 0 results

**Comment by pat** [comment]
It looks like the index definition was once SQL-based, but now is realtime - which means the SQL snippets for your latitude & longitude attributes are invalid. What you'll want to do instead is create methods in your model that translate the values to radians:

```ruby
def latitude_in_radians
  Math::PI * latitude / 180.0
end

def longitude_in_radians
  Math::PI * longitude / 180.0
end
```

And then use these methods in your index definition:

```ruby
has latitude_in_radians, as: :latitude, type: :float
has longitude_in_radians, as: :longitude, type: :float
```

**Comment by dikey94** [comment]
Thanks Pat! It works.

**Comment by pat** [comment]
Great to hear :)

**Comment by thimmaiah** [comment]
This one needs to be in the docs, would not have been able to get this to work without this post

**Comment by pat** [comment]
That's a fair point @thimmaiah, I will make sure that's part of a forthcoming docs update in the coming week or two.
