### ISSUE TITLE
Exclude records from being indexed

### ISSUE THREAD

**Issue by delphaber** [pat/thinking-sphinx#1022]
Let's say I have a `Post` ActiveRecord model. A post can be `archived` (boolean). I don't want to index archived posts, because I want to speed up the index process (`rake ts:index`).

Is there a way to do it? Should I mess with sphinx's `sql_query` parameter ?

Using thinking_sphinx v. 2.0.14 right now

Thanks!

**Comment by pat** [comment]
You can use the `where` method within an index definition to add a SQL clause.

```ruby
where "archived = true"
```

That should do the trick!

**Comment by delphaber** [comment]
Thanks!

This is how I did it

```ruby
class Post < ActiveRecord::Base
  define_index do
    where("posts.archived=0")
    indexes :title
  end
end
```
