### ISSUE TITLE
How to generate real time indices without MySQL?

### ISSUE THREAD

**Issue by hipertracker** [pat/thinking-sphinx#1024]
I don't use MySQL. I use Postgres. I use Rails 5. When I run `rails ts:generate` I get the error

```
hinkingSphinx::ConnectionError: Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61)

Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (61)
```

Why the heck it tries to connect to MySQL instead of Postgres? Maybe because the generated `development.sphinx.conf` file contains `listen = 127.0.0.1:9306:mysql41` inside? Does it have to use mysql??? Is thinking_sphinx hardcoded to work only with MySQL?

**Comment by pat** [comment]
Sphinx uses the MySQL protocol - not the MySQL database, just its protocol - for querying. It's why the mysql2 gem is required. The error you're getting is saying that TS hasn't been able to connect to your Sphinx daemon - is it running?

**Comment by hipertracker** [comment]
You are right. I just run `rails ts:regenerate` like before `rails ts:rebuild`. I needed to run `rails ts:start` first. It's working now.
