### ISSUE TITLE
Missing records after Sphinx indexing

### ISSUE THREAD

**Issue by hipertracker** [pat/thinking-sphinx#1025]
I found that Spinx is not indexing all my table records (with  3_288_369 records).

```ruby
db_found = Verse.where('text ~* ?', '\y[łŁ]ukasz\y').map(&:id).uniq.sort
db_found.size # => 74
ts_found = Verse.search('łukasz').map(&:id).sort
ts_found.size # => 20
```

I thought it's because I installed Sphinx without `--with-id64` option. But it was not that. After installing it again (`brew install sphinx --with-id64 --with-postgresql`) I still get the same results. 

I also checked if there is any difference between SQL and RT indexing, but it was not that either. It does not matter. Sphinx returns the same (too small) number of records.

I am not sure what is there, but when I compared missing record's `id`, I found that Sphinx ignored only records with higher `id` values. In my case it ignores all records with id = 2576172 and above...

**Comment by pat** [comment]
Sphinx (and thus, Thinking Sphinx) [paginates](http://freelancing-gods.com/thinking-sphinx/searching.html#pagination) search results. `Verse.search('łukasz').total_count` should return the total number of matches.

**Comment by hipertracker** [comment]
Aaaa. I see. Thanks.
