### ISSUE TITLE
Delta column is always set on save, regardless of dirty status of record

### ISSUE THREAD

**Issue by njakobsen** [pat/thinking-sphinx#1027]
In Rails, partial updates allow only the changed attributes to be written to the database. This, combined with dirty tracking means that if no attributes are changed, no writes need to be made to the database. Unfortunately, if delta indexes are enabled, this line https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb#L20 always dirties the object regardless of whether it has been modified or not. This breaks the convention established by ActiveRecord where calling `save` on a record with no changes will not trigger a write to the database.

If we were to only call the `before_save` that sets the delta, `:if => :changed?`, this issue should be avoided. Can anyone see potential bugs that would arise from this change?

**Comment by pat** [comment]
Good thinking, have just made this change: 6b0923c6db2e1b26e41f7505dfb0211a6b2ddf2d - feel free to give it a spin!

```ruby
gem 'thinking-sphinx', '~> 3.2',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '6b0923c6db'
```
