### ISSUE TITLE
geo search

### ISSUE THREAD

**Issue by leeson-w** [pat/thinking-sphinx#1029]
i'm using sphinx geo search to retrive  all services that distance is within 5 km from a specified location. i can get the results, but the number of records is not right compared with returned by geocoder.

The code is here:

> @lat = 39.8958
> @lon = 116.396
> #shpinx geo search
> @services = paginate(Service.search(:geo => [@lat, @lon], :with => {:geodist => 0.0..5_000.0}))
> #geocoder search
> #@services = paginate(Service.near([@lat, @lon], 5, :units => :km))

sphinx returns only one record, but geocoder returns 174 records.
i check the results, and confirm that geocoder is right.

i google for nearly a whole day, and rebuilt index, restart sphinx, done all things i can, but still not working.

here is index configures:

> ThinkingSphinx::Index.define :service, :with => :active_record, :delta => true do
>   #fields
>   indexes title
>   indexes description
> 
>   #attributes
>   has latitude, :as => :lat, :type => :float
>   has longitude, :as => :lng, :type => :float
> end

here is sphinx configures (now is in development):

> development:
>   mysql41: 9313
>   quiet_deltas: true
>   min_infix_len: 1
> test:
>   mysql41: 9313
>   quiet_deltas: true
>   min_prefix_len: 3
> production:
>   mysql41: 9313
>   quiet_deltas: true
>   min_prefix_len: 3

i appreciate anyone can help to solve this. thank you!

**Comment by pat** [comment]
It looks like you're searching with lat/lng values in degrees - they need to be in radians. This also applies to the attribute values as well - [the docs](http://freelancing-gods.com/thinking-sphinx/geosearching.html) cover how to convert them. Sphinx is very particular, it requires radians for all lat/lng values.

**Comment by leeson-w** [comment]
@pat 
Thank you for your quick response, i tried 'RADIANS()' by following that docs at the beginning, but it didn't work, and confused me, but you remind me that lat/lng values stored in DB is in degrees, and i thinking 'RADIANS()'  is to convert that values to radians, but my input still in degrees, so i also need to convert the input values to radians.

I make two changes:

index configures:
>has 'RADIANS(latitude)', :as => :lat, :type => :float
>has 'RADIANS(longitude)', :as => :lng, :type => :float

and the code:
>@lat = (39.8958/180) * Math::PI
>@lon = (116.396/180) * Math::PI

now i work like a charm, hhaha, thank you so much!

**Comment by pat** [comment]
Great to hear you got it working! :)
