### ISSUE TITLE
query error: no field 'is_published' found in schema

### ISSUE THREAD

**Issue by dikey94** [pat/thinking-sphinx#1030]
I'm trying to run Thinking Sphinx in my forum project.

Controller:
```
....
def search
    @discussions = Discussion.search ThinkingSphinx::Query.escape(params[:query]), :conditions => {:is_published => true}
end
....
```

Discussion model:
```
...
def is_published?
    Utterance.published.pluck(:discussion_id).include? self.id
end
...
```

Index:
```
ThinkingSphinx::Index.define :discussion, with: :real_time do
  indexes topic
  has is_published?, as: :is_published, type: :boolean
end
```

After "rails ts:regenerate" and running the search engine I've got:

> index discussion_core: query error: no field 'is_published' found in schema - SELECT * FROM `discussion_core` WHERE MATCH('kolejna @is_published true') AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META

I would be grateful for help.

**Comment by pat** [comment]
You've got it _almost_ correct - because `is_published` is (correctly!) an attribute, it belongs in the `:with` options in a search, rather than `:conditions`:

```ruby
Discussion.search(
  ThinkingSphinx::Query.escape(params[:query]),
  :with => {:is_published => true}
)
```

**Comment by dikey94** [comment]
Ha! Works. Thank you.
Each time I run "rails ts:regenerate" I have to delete db/sphinx/ directory and run the command twice. Is it normal?

**Comment by pat** [comment]
Can you give the latest code in the develop branch a spin? I think I've fixed this recently, but would be great to have confirmation before I publish a new gem version.

```ruby
gem 'thinking-sphinx', '~> 3.2',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => 'dc16d1c590'
```

**Comment by dikey94** [comment]
I think you've fixed this. Everything seems to be working fine. Thanks!

**Comment by pat** [comment]
Great - I'll try to get a new release out soon!

**Comment by dikey94** [comment]
Not sure if it's becouse of your branch but during a deployment I get:

> === Sphinx Regenerate ===
> 05:32 deploy:regenerate_sphinx
>       01 ~/.rvm/bin/rvm default do bundle exec rake ts:regenerate
>       01 searchd is not currently running.
>       01
>       01 Stopped searchd daemon (pid: ).
>       01
>       01 Generating configuration to /home/deploy/apps/fizjoterapiaclub/releases/20161201155337/config/production.sphinx.conf
>       01
>       01 Sphinx 2.2.11-id64-release (95ae9a6)
>       01
>       01 Copyright (c) 2001-2016, Andrew Aksyonoff
>       01
>       01 Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
>       01
>       01
>       01 using config file '/home/deploy/apps/fizjoterapiaclub/releases/20161201155337/config/production.sphinx.conf'...
>       01
>       01 listening on 127.0.0.1:9306
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 bind() failed on 127.0.0.1, retrying...
>       01 FATAL: bind() failed on 127.0.0.1: Address already in use
>       01
>       01 The Sphinx start command failed:
>       01   Command: searchd --pidfile --config "/home/deploy/apps/fizjoterapiaclub/releases/20161201155337/config/production.sphinx.conf"
>       01   Status:  0
>       01   Output:  See above
>       01
>       01 There may be more information about the failure in /home/deploy/apps/fizjoterapiaclub/releases/20161201155337/log/production.searchd.log.
>

**Comment by dikey94** [comment]
It was Sphinx issue.

**Comment by pat** [comment]
The error suggests Sphinx is already running - which you should be able to check with `ps aux | grep searchd`. However, TS _should_ be picking up the existing daemon by the PID file…

By looking at the paths, it seems you're using Capistrano for deployment? Or something else that has separate release directories? You'll need to configure TS to use consistent directories that don't change for each deploy - [the docs](http://freelancing-gods.com/thinking-sphinx/deployment.html) cover this pretty well, but if you've got any questions about it, do ask.

Once you make this change, you'll need to manually kill any existing `searchd` processes, and then run `ts:regenerate` again to ensure all Sphinx files are in their new, permanent location. This should include the PID file, and then TS and Sphinx will handle existing processes much more reliably :)

**Comment by dikey94** [comment]
The docs was helpful, I've done it. Thank you so much.

**Comment by pat** [comment]
Just pushed v3.3.0 which includes the fixes you've been using :)
