### ISSUE TITLE
Sphinx's output is verbose for rake ts:index in version 3.3.0

### ISSUE THREAD

**Issue by bentoncreation** [pat/thinking-sphinx#1032]
In the 3.3.0 release, it looks like the ts:index task (https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/tasks.rb#L9) no longer passes the silent option to the RakeInterface index method (https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/rake_interface.rb#L40). And since the verbose option there defaults to true, it's always passing true to the Sphinx controller.

So, now, when I run:
```
bundle exec rake ts:index --silent
```

It no longer puts:
```
Generating configuration to config/sphinx.conf
```

But it *does* put:
```
Sphinx 2.1.9-release (rel21-r4761)
Copyright (c) 2001-2014, Andrew Aksyonoff
Copyright (c) 2008-2014, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file 'config/sphinx.conf'...
indexing index 'subclip_core'...
```

etc, etc.

If I understand it right, the index rake task just needs to go back to:

```
task :index => :environment do
  interface.index(
    ENV['INDEX_ONLY'] != 'true',
    !Rake.application.options.silent
  )
end
```

**Comment by pat** [comment]
Thanks for that Jeremy - I didn't see your extra detail (only the pre-edited version via the email notification) until now, and it's all greatly appreciated! - but I've just pushed a fix that deprecates the second argument to `ThinkingSphinx::RakeInterface#index` and uses the Rake arguments (both `--silent` and `--quiet`) appropriately. You can give it a spin using the latest in the `develop` branch:

```ruby
gem 'thinking-sphinx', '~> 3.3.0',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '36094b528d'
```

**Comment by bentoncreation** [comment]
Hey, thanks Pat! (Sorry, I accidentally submitted the issue before all my details were in place.) :)

I switched to the `develop` branch for my project and everything looks good. The `--silent` argument is obeyed when I run the rake task manually and from the cron job.

And thanks for this! It'll be great having fewer cron emails.
