### ISSUE TITLE
"query is non-computable" error uses generic exception type

### ISSUE THREAD

**Issue by JasonBarnabe** [pat/thinking-sphinx#1034]
```ruby
Model.search('-test')
```
```
ThinkingSphinx::SphinxError: index model_core,model_delta: query is non-computable (single NOT operator)
```
This should have a specific exception type so I can catch this error caused by bad user input without catching other errors that I should care about more. Or make it use `ThinkingSphinx::SyntaxError`, because it seems syntax-errory.

**Comment by pat** [comment]
Hi Jason

I've just pushed a commit to the develop branch that captures that error as `ThinkingSphinx::ParseError`, as there was already a similar scenario - i.e. the query can't be parsed correctly by Sphinx. Does that make it easier for you to deal with this?

Cheers,

Pat

**Comment by JasonBarnabe** [comment]
Yes, that looks like it will work. Thanks.
