### ISSUE TITLE
Polymorphs and STI (regression)

### ISSUE THREAD

**Issue by ace** [pat/thinking-sphinx#1035]
Hi Pat. 

After upgrading versions, I'm having the same issue I had some time ago with polymorphs and STI, joins are not using the base class, #820. 

I've tracked the problem down to the `JoinAssociation` class. The solution is similar to that old issue. Changing `base_klass.name` to `base_klass.base_class.name` in line 8 in `join_association.rb` seems to solve it and not break anything else.

Regards

**Comment by pat** [comment]
Hi Andrés, thanks for that excellent debugging work! Just so I can confirm things from my side - which versions of TS did you upgrade from/to, and which version(s) of Rails/ActiveRecord are you using?

**Comment by ace** [comment]
Hi Pat. The upgrade was part of a greater one, from rails 4.0 to 4.2, we went from TS 3.1.2 to 3.2.0 (we had 3.1.4 in between but just for a few hours and can't confirm if the problem was there). We also went from version 0.2.0 to 0.3.4 of Joiner, maybe this is relevant (below). Those are our current versions.

As far as I have seen, the fix you added back in #820 is still there (in `filter_reflection.rb`, the `scope` method) but it's not reached because of the condition with the Joiner gem just above it. I've not gone into much detail, but I'd say the key moment was commit `50dc3d9` in Joiner. At that point the condition above the previous fix went true and caused the old fix to be skipped.

**Comment by pat** [comment]
Just pushed the fix into `develop`, and added a test for it as well :)

**Comment by ace** [comment]
Works perfectly. Thanks, Pat.

**Comment by pat** [comment]
My part was easy - you found the fix! :)
