### ISSUE TITLE
Reindexing a table after update_all()

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1039]
We're using update_all with a `delta: true` option and then calling this method to reindex the changed records:
```    
ThinkingSphinx::Deltas::SidekiqDelta::DeltaJob.perform_in(10.seconds, :table_name_delta)
```
Is this the right way to do this? Or should I be using table_name_core?

**Comment by pat** [comment]
What you're doing is correct - you want to call it with the delta index.

The other half of what delta updates do normally is mark the original records as 'deleted' in the core index. Doing this in a bulk manner isn't quite so elegant, but it's certainly possible - I've discussed a couple of approaches on the Thinking Sphinx Google group a few months ago: https://groups.google.com/d/msg/thinking-sphinx/8u3iS_wNfGA/zBQdvOXVBwAJ
