### ISSUE TITLE
Search with multiple-field operator

### ISSUE THREAD

**Issue by yijia-zhan** [pat/thinking-sphinx#1040]
Looks like this used to be a supported behavior, but it's taken out at some point. 

https://github.com/pat/thinking-sphinx/pull/471
https://github.com/pat/thinking-sphinx/issues/120

What I wanted to do is wildcard search across multiple fields, but **not all** indexed fields:

> @(field_a,field_b) *mike* *tyson*

But this code no longer works with v3 (v3.2.0):
```ruby
User.search condition: { [:field_a, :field_b] => "mike tyson" }, star: true
```

**Comment by pat** [comment]
Sorry, not sure why this feature disappeared, but just added it back in with a705d48dcb5e6d63cb6e38b81b7fb7c330acccb1 in the `develop` branch.

```ruby
gem 'thinking-sphinx', '~> 3.3.0',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => 'a705d48dcb'
```

You'll want to read the release notes for [v3.3.0](https://github.com/pat/thinking-sphinx/releases/tag/v3.3.0), but I think upgrading from v3.2.0 should be pretty painless. There's one change in `develop` that's of note, though: Thinking Sphinx will expect all attribute filter values to be casted to their appropriate types. This is particularly relevant if you're using params values in filters. An example:

```ruby
Article.search :with => {:user_id => params[:user_id]}
# should become:
Article.search :with => {:user_id => params[:user_id].to_i}
```

Currently (in `develop`), Thinking Sphinx will auto-cast values and print a deprecation warning, so upgrading without making any changes should still work now, this is more a note of the likely breaking change in future releases.

**Comment by yijia-zhan** [comment]
Thanks for the quick fix and the upgrade note @pat! 

I have another question. Please advise if I should move to a separation issue for discussion. 

The `star: true` option currently wraps each tokenized search term in wildcards. For example, 

This line
```ruby
User.search("mike tyson", star: true)
```
Will search by
> \*mike\* \*tyson\*

Is there a way to add wild card to a phrase? What I want is:
> \*mike tyson\*

I've also trying to get the proximity search operator `~10` work with wildcard, but without luck so far.

**Comment by yijia-zhan** [comment]
I have another question. Please advise if I should move to a separation issue for discussion. 

The `star: true` option currently wraps each tokenized search term in wildcards. For example, 

This line
```ruby
User.search("mike tyson", star: true)
```
Will search by
> \*mike\* \*tyson\*

Is there a way to add wild card to a phrase? What I want is:
> \*mike tyson\*

I've also trying to get the proximity search operator `~10` work with wildcard, but without luck so far.

**Comment by pat** [comment]
The `:star` option can also take a regular expression on the characters to match, so it is possible to customise the behaviour. Still, I think the logic in [lib/thinking_sphinx/wildcard.rb](https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/wildcard.rb) is written to expect whitespace as a separator. So the best approach here is for you to do the wildcarding yourself instead of using `:star`.
