### ISSUE TITLE
Issues performing full index on load balanced environment

### ISSUE THREAD

**Issue by johnkoht** [pat/thinking-sphinx#1042]
I'm having issues performing full indexes on a load balanced environment. I have two Rails application servers and another server that runs Sphinx. Sidekiq runs on all three servers and I use sidetiq for recurring jobs. I deploy with Capistrano.

- Sphinx 2.2.11-id64-release
- Thinking Sphinx Gem 3.3.0
- Ruby 2.1
- Rails 4.0.13

Here's my sidekiq worker
```ruby
class ThinkingSphinxIndexWorker
  include Sidekiq::Worker
  include Sidetiq::Schedulable
  sidekiq_options queue: :ts_full_index

  recurrence { hourly }

  def perform
    ThinkingSphinx::RakeInterface.new.index
  end
end
```

The sidekiq job keeps failing and the error is pretty vague: `SystemExit: exit`. When I try to run the sidekiq job on one of the application servers, I receive the following error:

```
Generating configuration to /var/www/releases/20170124015509/config/production.sphinx.conf
sh: indexer: command not found

The Sphinx indexing command failed:
  Command: indexer --config "/var/www/releases/20170124015509/config/production.sphinx.conf" district_core
  Status:  127
  Output:  See above

There may be more information about the failure in /var/www/shared/log/production.searchd.log.
```

I assume the error is because I don't have Sphinx installed on the application servers and sidekiq may be triggering the worker on one of these app servers. Is there a way around this? I'd rather not install Sphinx on all application servers if I don't need to. 

Thanks in advance!

**Comment by pat** [comment]
Hi John,

Your assumption is correct: indexing only works on machines which have Sphinx installed. You'll want to make sure that all indexing-related jobs are _only_ processed on the server that's running Sphinx.

Sphinx can't run indexing commands across a network, it always expects to be on the same machine as the data files (even though the database it talks to may be located elsewhere).

So yeah, you'll want to configure Sidekiq to use the appropriate queues for each server.

**Comment by johnkoht** [comment]
Hey Pat- Thanks for the quick response! That makes sense. Looks like sidekiq can handle a server-specific queue so that should work. Thanks!
