### ISSUE TITLE
"unknown column" errors with real-time but not SQL-backed indexing

### ISSUE THREAD

**Issue by ralphhaygood** [pat/thinking-sphinx#1043]
Several years ago, before real-time indexing was introduced, I used Thinking Sphinx successfully in a Rails 2 application. Now I'm trying to use it with real-time indexing in a Rails 4 application, and I'm not getting far at all.

Every time I do "rake ts:generate", I get "unknown column" errors. For example, given a model `Quote` with a string field `label`, if app/indices/quote_index.rb contains

    ThinkingSphinx::Index.define :quote, :with => :active_record do
      indexes label
    end

then all's well, but if I change "active_record" to "real_time", I get

    ThinkingSphinx::SphinxError: unknown column: 'label' - REPLACE INTO quote_core (id, `sphinx_internal_class_name`, `label`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`) VALUES (102, 'Quote', 'New quote', 51, 'Quote', 0), ...

Evidently, it isn't the `label` column of the `quotes` table that's unknown, because the error message actually contains values from that column; for example, the label of the quote whose ID is 51 is indeed "New quote". So, being unfamiliar with the innards of Sphinx, I hardly know where to begin solving this problem.

I'd greatly appreciate knowledgable advice. I'm using Rails 4.2.6 with Ruby 1.9.3, Thinking Sphinx 3.3.0, and Sphinx 2.2.9.

**Comment by pat** [comment]
Hi Ralph,

Does `rake ts:regenerate` get things working? `ts:generate` is only for updating data, but if you're making configuration/schema changes for your real-time indices, you'll need to use `ts:regenerate` instead.

To explain the error: if you were using an SQL-based index, then the Sphinx index files will be formatted in a particular way. Switching to real-time means that expected file format has changed, hence Sphinx can't find the `label` field in the necessary format. The **re**generate task stops Sphinx and clears out the old index files, starting again from scratch, which should resolve the issue.

**Comment by ralphhaygood** [comment]
Yes! I should have studied the new rake tasks. But thanks very much.

**Comment by pat** [comment]
Great to know it's now working as expected :)
