### ISSUE TITLE
Error/warn when using non-existant option

### ISSUE THREAD

**Issue by JasonBarnabe** [pat/thinking-sphinx#1044]
I spent the last 30 minutes trying to figure out why this wasn't doing eager loading:

```ruby
 Script.search('foo', include: :user).first(2).map(&:user).map(&:id)
```

Finally found the answer [here](http://freelancing-gods.com/thinking-sphinx/searching.html#advanced):

```ruby
Script.search('foo', sql: {include: :user}).first(2).map(&:user).map(&:id)
```

How about an error/warning when passing an option to `search` that doesn't exist?

**Comment by pat** [comment]
Thanks for the suggestion Jason, I haven't got to implementing anything just yet, but here's what I'm thinking:

* Option checker is a search middleware (thus, can be disabled easily enough if people wish to).
* Options to check should be configurable, in case other people are running custom middleware that take new options into account. 

Nothing particularly complex, just haven't had the time. If you want to take a stab at it, be my guest :)

**Comment by pat** [comment]
Finally got this sorted (in eb8b656bfbf171b5ce848754b2930ee8fcb86d10)
