### ISSUE TITLE
Capistrano monit support

### ISSUE THREAD

**Issue by Michsior14** [pat/thinking-sphinx#1045]
Hello,
Could you consider adding Monit support when deploying with Capistrano? 
It will be nice to have something like Puma has: [ here](https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/tasks/monit.rake).

**Comment by pat** [comment]
It would definitely be useful, but I don't think I want to add this to the Thinking Sphinx gem itself. It could be worth creating a separate gem for that specific purpose?

I realise the Capistrano configuration is within TS, but if I was to do things again, I would have that as a separate gem too.

**Comment by Michsior14** [comment]
Yes, separate gem is good idea and configuration is small enough so it's not a problem i think. I tried to do that, but I had lost in your Riddle gem (I would need more time to learn the way you connected it with TS).
I can help with new gem if you want :)

**Comment by pat** [comment]
I'm keen for you to create the gem - I'm not using Thinking Sphinx with monit myself, so it's much better if someone who actually needs the gem builds it :)

I'd expect `ThinkingSphinx::Configuration.instance` has all the information you need to generate a monit file? The methods will be the same name as the settings in `config/thinking_sphinx.yml` (as noted in the [deployment docs](http://freelancing-gods.com/thinking-sphinx/deployment.html)), so you shouldn't need to delve into Riddle's internals. That said, if you have any questions about Riddle or TS, do ask!

**Comment by Michsior14** [comment]
Ok, I've tried do it with configuration instance, but I always get instance for production environment so I can't generate proper monit config for server.
I could make another task to do it on server, but then the gem needs to be deployed before generating configuration and installed not in development group what I'd like to avoid.
Is there another solution for this problem?

**Comment by Michsior14** [comment]
Okey, seems like [this](https://github.com/Michsior14/thinking-sphinx-monit) works, but it's ugly :/

**Comment by pat** [comment]
Sorry for the very delayed response - February was particularly busy - but it's great to see you've built the gem! I'll certainly keep it in mind if/when I'm using the combination of monit/cap/TS, and if I hear of anyone else doing the same.
