### ISSUE TITLE
best practice to handle StaleIdsException ?

### ISSUE THREAD

**Issue by gingerlime** [pat/thinking-sphinx#1048]
Somehow related to #999 - we're bumping into this error, and I wonder about the best practice to deal with it.

## Some background / info:

We have a bunch of model objects that get "re-generated" some time. In our case, it's a list of exercises that belong to a quiz. We treat those exercises as immutable objects, a bit like cached entries that let us perform queries more effectively. So whenever a new quiz is uploaded, we discard of all the old exercises for the quiz, and re-generate them.

Since we also want to be able to find a quiz based on its exercises, we're using TS to index those exercises. However, when they get re-generated, we bump into this `StaleIdsException`.

## Question:

How should we deal with this? re-index every time we re-generate the exercises? (if so, is there a way to trigger a re-index directly from our app?) Is there a way to partially update the index?

Sorry if those are daft questions, but I'm not entirely sure where to begin, and I'm not that intimately familiar with TS...

**Comment by atomical** [comment]
The index should be updated when objects are deleted. Does your exercises table have a delta column?

http://freelancing-gods.com/thinking-sphinx/deltas.html

**Comment by gingerlime** [comment]
Thanks for the tip @atomical !

No, I wasn't aware of it... I'll look into it.

Would deltas work even if we do something like `Exercise.where(...).delete_all` (bypass any before/after destroy actions)?

**Comment by gingerlime** [comment]
I tried adding `delta` to the exercises table, and I can see in the log that when exercises are created, sphinx updates. It doesn't trigger however with `delete_all`. I'm not using `destroy_all` for both performance reasons, and also the `Exercise` model is set as write-once with

```ruby
def readonly?
  persisted? 
end
```

so calling `destroy_all` will throw a `ActiveRecord::ReadOnlyRecord: Exercise is marked as readonly` exception...

Is there a way around it?

**Comment by atomical** [comment]
See https://github.com/pat/thinking-sphinx/issues/1039 

That technically should update the delta index. I tried it yesterday and couldn't get it working so now we're back to iterating through records and updating them. I've been meaning to put together a test case or example application for @pat, but I haven't gotten around to it yet.

The other option you can try is force reindexing the whole table by using table_name_core for the reindex argument. We use Sidekiq deltas but the same method should be in TS.

**Comment by gingerlime** [comment]
Thanks for the additional info, @atomical.

For our particular use-case, this happens rather rarely, and I don't mind reindexing the whole table. This already runs in a sidekiq job. Also, since our model is readonly/immutable, we won't allow updating the delta flags anyway (we can bypass it by going directly to the database). So I think a re-index might more sense in this case, even if it's less efficient. But I'm happy to consider any approach. And more generally, it would be useful to understand the most efficient approach naturally :)

Sorry if this is a silly question (As I mentioned, I'm not super familiar with TS), but how exactly do I trigger a whole table reindex from inside the sidekiq job?

**Comment by gingerlime** [comment]
Looks like this works(?), even if I don't use deltas, but not sure if it's the right/best thing to call...

```ruby
ThinkingSphinx::Deltas::IndexJob.new(:exercise_core).perform
```

**Comment by pat** [comment]
Thanks @atomical for jumping in with all the solid references and suggestions 👍

@gingerlime: the link you're using will certainly work. An alternative that isn't part of the Deltas namespace is to do the following:

```ruby
ThinkingSphinx::Configuration.instance.controller.index 'exercise_core'
```

**Comment by gingerlime** [comment]
Thanks @pat. I saw this one too after digging into the code, but felt like it's going really deep into the object (My Law-of-Demeter alarm was beeping), so I though the `Delats::IndexJob` is a more safe approach (??).

In any case, it works for us for this particular use-case. Thanks both for your help and patience. Much appreciated.

**Comment by pat** [comment]
Completely fair point on the Law of Demeter. I'll consider that in future refactoring and try to provide a more direct interface.
