### ISSUE TITLE
ts mutex deadlock under sidekiq.

### ISSUE THREAD

**Issue by lizard2010** [pat/thinking-sphinx#1051]
Ruby version: 2.3.1
Thinking-sphinx: 3.3.0
Sidekiq version: 4.2.10
rails: 5.0.0, 5.0.2

I have models, which have ts indices. 
The sidekick run [attached worker](https://github.com/pat/thinking-sphinx/files/886540/run_search_doubles_worker.rb.txt) as several jobs at the same time.
And all they are blocked on updating the record, which calls thinking-sphinx.
As you can see in [attached trace](https://github.com/pat/thinking-sphinx/files/886555/trace.txt) for one of the jobs, ActiveRecord update_attribute call thinking-sphinx callback, which try get indices configuration.
[thinking_sphinx/configuration.rb#L78](https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/configuration.rb#L78)
I have no idea, how to use Sidekiq with thinking-sphinx simultaneously.
As I understand, thinking-sphinx configuration block inside mutex protect take a relatively much time, but why all threads got deadlock?
For test I commented  @@mutex.synchronize, and get success update.
This issue is affected only sidekiq worker,  manual call this worker from console works well.

**Comment by pat** [comment]
I'm really not sure why this deadlock is happening… I'd expect the first run would preload indices, and then everything else would be allowed to run after that.

Can you try adding the following to an initialiser - which will preload the indices fully when the app boots, and hopefully that'll avoid the deadlocks when the jobs are being processed by Sidekiq.

```
unless Rails.env.development?
  ThinkingSphinx::Configuration.instance.preload_indices
end
```

**Comment by lizard2010** [comment]
Thank you for your help. 
With preload_indices job  now works as expected.
