### ISSUE TITLE
Update index after soft delete

### ISSUE THREAD

**Issue by chris-roerig** [pat/thinking-sphinx#1057]
Pat,

I introduced soft delete to a couple models using [ActsAsParanoid](https://github.com/rubysherpas/paranoia). 

Strangely, I have one record that has been destroyed (has a "deleted_at" value) but it still shows up in the TS query. I read on another thread that TS has its own post destroy hook to update the indexed record. I'm guessing that hook was not called for this particular record. I've tried `ts:rebuild` and `ts:reindex` but I can't get that record to stop showing up. Any ideas?

**Comment by pat** [comment]
Hi Chris

Thinking Sphinx won't automatically ignore soft-deleted records when indexing - you'll want to have [a WHERE clause in your index definition](http://freelancing-gods.com/thinking-sphinx/indexing.html#conditions) to ensure that.

As for the callbacks - Thinking Sphinx will mark a record as 'deleted' when `destroy` (and the corresponding callbacks) is called, but this is just a temporary measure until the next indexing happens. I'm not sure if ActsAsParanoid invokes those callbacks, so it could be that this isn't happening? If you want to invoke this callback manually, use `ThinkingSphinx::ActiveRecord::Callbacks::DeleteCallbacks.after_destroy(instance)`

**Comment by chris-roerig** [comment]
Hi Pat, 

The callback you noted is what I was looking for and it fixed my issue. It appears as long as the record is marked as deleted in Sphinx no additional query options are needed to filter out "deleted" records.

Thanks for your help.

**Comment by akostadinov** [comment]
Unfortunately there seems to be no clean way to delete instance in case callbacks are disabled. For example disable all callbacks and insert own callbacks.

**Comment by pat** [comment]
Hi @akostadinov - can you provide an example of the callbacks you're using instead? Also, may be worth continuing this discussion as a new issue (and if you can, do let me know what versions of Thinking Sphinx and Rails you're using - callbacks in TS have evolved in the last few years).

**Comment by akostadinov** [comment]
This is current background worker that we use:
```ruby
class SphinxAccountIndexationWorker < SphinxIndexationWorker
  def perform(account)
    if account.will_be_deleted?
      to_delete = account.buyers.pluck(:id) << account.id
      # This is how deletion is performed by ThinkingSphinx::ActiveRecord::Callbacks::DeleteCallbacks#delete_from_sphinx
      # Alternatively, we could delete individual records one by one with:
      # ThinkingSphinx::ActiveRecord::Callbacks::DeleteCallbacks.after_destroy(instance)
      indices(account).each do |index|
        ThinkingSphinx::Deletion.perform index, to_delete
      end
    else
      super
    end
  end
end
```

This is thinking-sphinx 3.4, upgrading to 5.4 right now, seems to work the same as far as I can tell.

I opened a related issue #1215, I can open another one for the soft-delete use case.
