### ISSUE TITLE
Documentation: tell about ThinkingSphinx::Connection.pool.clear!

### ISSUE THREAD

**Issue by cmaion** [pat/thinking-sphinx#1060]
Hi there,

I didn't see in the installation documentation a reference to ThinkingSphinx::Connection.pool.clear.

On unicorn (and others, probably), a call to ThinkingSphinx::Connection.pool.clear after_fork is absolutely necessary when a sphinx request is performed by the master process before forking (which happens in my case to check the actual Sphinx server version being used).

Without that, workers will all inherit/share a persisted connection, without locking (and thus requests/replies will get mixed between workers).

Might help others! ;)

**Comment by cmaion** [comment]
BTW ThinkingSphinx::Connection.pool.clear doesn't close current connections when ThinkingSphinx::Connection.persistent is true, it just removes them from the pool.

See https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/connection.rb#L69

Not sure why you wouldn't want to always close the connection when removing it from the pool!

**Comment by pat** [comment]
Thanks :) just added this to the docs (52cb285c4e21254bf0b6f26c21764371dc0f457b) plus fixed the closing of persistent connections (827c1f4ab91a5b28dac9468ad0191c0a4abf17e9)

**Comment by cmaion** [comment]
:thumbsup:
