### ISSUE TITLE
Eager-loading associations

### ISSUE THREAD

**Issue by craigsheen** [pat/thinking-sphinx#1062]
Hi,

I am trying to eager load an association to avoid N+1 and I have followed the docs (specifically http://freelancing-gods.com/thinking-sphinx/real_time.html) but it doesn't seem to be working.

I have;
```
ThinkingSphinx::Index.define :item, with: :real_time do
  # scopes
  scope { Item.preload(:user) }
  # I have also tried scope { Item.includes(:user) }
  ...
```

When I do this the scope doesn't seem to be used in the generated SQL and it is still then hitting the DB when doing `item.user.email`.

I have looked through the issues and on google and can't seem to find anything related. Am I missing something?

**Comment by pat** [comment]
Hi Craig,

This looks right to me - though it's worth noting that the scope only applies for the `ts:generate`/`ts:regenerate` rake tasks, not for single-record inserts/updates. Are you finding the eager loading isn't working for the rake tasks?

**Comment by craigsheen** [comment]
Hi,

Yeah I was using `ts:regenerate`, but I suppose that won't work if then they update singularly after via the `after_save`?

I see in https://github.com/pat/thinking-sphinx/issues/796 that there was something added around avoiding this N+1, was this actually added to the main branch and is it usable?

Sorry if I have misread somewhere.

**Comment by pat** [comment]
The block syntax described in that issue for the callbacks is indeed in the master branch (develop is where commits go first, then they end up in master once there's been a gem release - and there's definitely been releases since 2014!)

Just to be clear: I'd expect the `scope` to apply consistently for the rake tasks. If you're not finding that's the case, sounds like there's a problem.

**Comment by craigsheen** [comment]
I think maybe I am misunderstanding somewhere. I have created a super small and simple repo https://github.com/craigsheen/sphinx-issue-repo which shows the issue.

Setup;
```
bundle exec rake db:drop db:create db:migrate db:seed
rake ts:regenerate
```

Then just load the initial page does a search and I see;
```
Processing by PagesController#index as HTML
  Sphinx Query (3.5ms)  SELECT * FROM `item_core` WHERE MATCH('bar') AND `sphinx_deleted` = 0 LIMIT 0, 20
  Sphinx  Found 2 results
  Item Load (0.4ms)  SELECT "items".* FROM "items" WHERE "items"."id" IN (2, 4)
  Rendering pages/index.html.erb within layouts/application
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Rendered pages/index.html.erb within layouts/application (29.8ms)
Completed 200 OK in 377ms (Views: 341.4ms | ActiveRecord: 2.2ms)
```

Any help would be appreciated.

**Comment by pat** [comment]
Oh, I think I know what the misunderstanding might be.

The `scope` in the index definition is purely for the rake tasks, when doing batched loading of data into the indices. When you're making search queries and want eager loading to happen there, you instead should use [the `:sql => :include` option](http://freelancing-gods.com/thinking-sphinx/searching.html#advanced):

```ruby
Item.search "bar", :sql => {:include => :user}
```

**Comment by craigsheen** [comment]
That makes so much sense! 🤦‍♂️  It works perfectly.

Sorry about that and thank you very much for your help!

**Comment by pat** [comment]
No need to apologise! And great to know it's working as you expect now :)
