### ISSUE TITLE
Failed to start searchd daemon.

### ISSUE THREAD

**Issue by cis-kamlesh** [pat/thinking-sphinx#1063]
When I run,

<code>rake ts:start</code>

it gives,

Failed to start searchd daemon. Check /project/log/development.searchd.log.
Failed to start searchd. Check the log files for more information.

and there is no any file with name 'development.searchd.log'  in project folder

**Comment by pat** [comment]
Hmm, not quite sure what the cause of this problem is. Which versions of Thinking Sphinx, Rails and Sphinx do you have installed? Has this worked in the past, or is this your first time using Thinking Sphinx?

**Comment by cis-kamlesh** [comment]
pat, I have got the solution and it is working for me. Thank you for replying.

**Comment by pat** [comment]
Good to know :) Is it possible to share how you fixed things, just in case others hit the same problem? (And/or maybe there's something I can improve in TS)

**Comment by cis-kamlesh** [comment]
Yes sure, as it was failing due to it couldn't able to find the file with name 'development.searchd.log' and it was not creating itself, so I have just tried that made it manually with that name and while searching it started to take it and it worked for me.
