### ISSUE TITLE
FATAL: failed to create TLS for connection ID

### ISSUE THREAD

**Issue by fernandomcunha** [pat/thinking-sphinx#1067]
Hi,

I'm hopping someone would  be able to point me in the right direction. I got an Amazon EC2 instance and i'm getting trouble trying to start sphinx with `bundle exec rake ts:start`. My config:

```
base: &general_settings
  min_infix_len: 1
  mem_limit: 1024M
  write_buffer: 16M
  charset_table: "\
      U+00C0->a, U+00C1->a, U+00C2->a, U+00C3->a, U+00C4->a, U+00E0->a, U+00E1->a, U+00E2->a, U+00E3->a, U+00E4->a, \
      U+00C7->c, U+00E7->c,  \
      U+00C8->e, U+00C9->e, U+00CA->e, U+00CB->e, U+00E8->e, U+00E9->e, U+00EA->e, U+00EB->e, \
      U+00CC->i, U+00CD->i, U+00CF->i, U+00EC->i, U+00ED->i, \
      U+00D2->o, U+00D3->o, U+00D4->o, U+00D5->o, U+00D6->o, U+00F2->o, U+00F3->o, U+00F4->o, U+00F5->o, U+00F6->o,  \
      U+00D9->u, U+00DA->u, U+00DC->u, U+00F9->u, U+00FA->u, U+00FB->u, U+00FC->u, U+0168->u, U+0169->u,
      U+FF10..U+FF19->0..9, U+FF21..U+FF3A->a..z, U+FF41..U+FF5A->a..z,  \
      0..9, A..Z->a..z, a..z"

development:
  <<: *general_settings
  mysql41: 3312

test:
  <<: *general_settings
  mysql41: 3319

<%= ENV["RAILS_ENV"] %>:
  <<: *general_settings
  address: <%= ENV["SPHINX_HOST"] %>
```

When I execute the rake i got:

```
searchd is not currently running.
Stopped searchd daemon (pid: ).
Failed to start searchd daemon. Check /path/to/log/training.searchd.log.
Failed to start searchd. Check the log files for more information.
```

   And in `training.searchd.log` I just got:

```
[Mon Sep 11 16:26:04.149 2017] [17464] FATAL: failed to create TLS for connection ID
[Mon Sep 11 16:26:04.150 2017] [16442] watchdog: main process 17464 exited cleanly (exit code 1), shutting down
```

I don't know what to do cause two days ago it was working fine.

Thanks,
Best Regards

**Comment by pat** [comment]
Hi Fernando,

How are you deploying Sphinx to this server? Is it via capistrano or something similar with versioned releases? If so, you'll want to make sure you use shared paths for all Sphinx-related files - this will ensure they're in a consistent location across deploys.
https://freelancing-gods.com/thinking-sphinx/deployment.html

You'll then want to make sure any existing searchd processes are stopped before running the rake tasks again.

If this is not the case, and the paths are consistent in your environment, then I'm really not sure what's going on - I'm not familiar with that particular error message. But I'd be confirming whether searchd is actually already running.

Also, if you can let me know what versions of Thinking Sphinx and Sphinx you're using, that might provide further clues as well :)

**Comment by fernandomcunha** [comment]
Sorry about my mistake @pat. I'm using Thinking Sphinx 3.1.4 and Sphinx 2.2.10-id64-release. On the EC2 instance I tried `ps -ef | grep searchd` but no processes found.

**Comment by pat** [comment]
I'm afraid I'm at a loss as to what's causing this. I'd recommend asking on the Sphinx forum, particularly with a focus on "failed to create TLS for connection ID".

You may want to try invoking Sphinx directly, just in case that's different (because the folks on the Sphinx forum mostly won't know/care about Thinking Sphinx's behaviour as a wrapper - but I feel that this is an underlying Sphinx thing, not a bug in TS). The relevant command is `searchd --pidfile --config config/training.sphinx.conf`.

**Comment by pat** [comment]
Actually, now that I think of it, I'm keen to know the output of that command - perhaps it provides more information that'll help me understand the cause as well :)

**Comment by fernandomcunha** [comment]
Well, I just make an image of the production server, launched it and change the ENV and it works now. Don't know what happened. Thanks for your time @pat

**Comment by pat** [comment]
Glad to hear it's working again - hope this issue doesn't crop up again :)
