### ISSUE TITLE
Multiple string values as attributes

### ISSUE THREAD

**Issue by JasonBarnabe** [pat/thinking-sphinx#1069]
I see in https://freelancing-gods.com/thinking-sphinx/indexing.html#fields there is an example of using multiple string values as a field.

https://freelancing-gods.com/thinking-sphinx/indexing.html#attributes includes an example of multi-valued integer attribute. When I try this with a string, I get `expected attr type ('uint' or 'timestamp' or 'bigint') in sql_attr_multi, got 'string applies_tos from field'`. Reading some other places around the internet, it seems like you can't multi-valued string attributes?

If this is the case, can you update the documentation to explicitly state this, and perhaps recommend alternative methods to search on multi-valued strings?

**Comment by pat** [comment]
Hi Jason,

I've just pushed a change for the documentation (though the cache for the deployed site is taking a while to update) which makes it clear that String MVAs aren't possible in Sphinx, as well as making some comment on a workaround.

If you're dealing with strings that are from an association, then I'd recommend using the id column instead as an MVA, and when you want to filter, translate the string values into their related integer id. It means potentially one extra query to the database, but at least you'll get the specific filtering ability that just isn't possible by using fields.

You're probably across this already, but just in case, on the topic of fields: TS and Sphinx just concatenate all string values together to populate the field's value. There's no data structure, no delimiters between each of the original values. Hence it's not really possible to use them reliably as a replacement for string attribute filters.

**Comment by JasonBarnabe** [comment]
What you suggest is pretty much what I learned after reading between the lines of the documentation. It's great to have this explicitly stated. Thanks!
