### ISSUE TITLE
Rails enum leads to zero

### ISSUE THREAD

**Issue by jakubonty** [pat/thinking-sphinx#1070]
I have model with column state type integer and in model there is enum for this column:

`enum state: { active: 0, unavailable: 1, deleted: 2 }`

state then returns string and after indexing everything has state 0 in index.

I fixed that changing the getter:
```
  def state
    self.attributes['state']
  end
```

Is there better solution for this situation?

**Comment by pat** [comment]
Hmm, I've not used enums before, but I can investigate. Are you using SQL-backed indices, or real-time indices? And what's the index definition looking like?

**Comment by jakubonty** [comment]
I am using real-time with following definition:
```
ThinkingSphinx::Index.define :entity, :with => :real_time do
  ...
  has state, :type => :integer
end
```

**Comment by pat** [comment]
As far as I understand the Rails enum feature, this makes sense to me - `state` should return a string, and hence when the real-time access goes to get an integer, it calls to_i on it, and `"active".to #=> 0`. I _could_ make TS smarter about enums and try to figure out whether the string or integer value is preferred depending on the attribute data type (or if it's wanted for a field), but I feel like that's more hassle than its worth.

If you want the integer value stored by Sphinx while keeping the enum in place, I'd recommend creating a separate method which returns the underlying integer, and use that in your index:

```ruby
# in model:
def state_to_i
  attributes["state"]
end

# in index:
has state_to_i, :type => :integer
```

**Comment by jakubonty** [comment]
Thank you.
This is nice solution.
