### ISSUE TITLE
Best procedure for starting sphinx on boot

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1071]
What's the best command/setup for automatically starting sphinx when the server is rebooted? If I call rake ts:start every minute is there a chance it could interfere with a rebuild or reindex?

**Comment by pat** [comment]
Hi Adam,

Firstly: `ts:start` could definitely interfere with `ts:rebuild` - but I'd certainly be recommending that `ts:rebuild` isn't called on a scheduled basis. Instead, it's really only needed when your Sphinx schema changes (new or changed indices, fields, attributes). It shouldn't interfere with `ts:index` though.

But as for general approaches for booting Sphinx with the server: it depends on your hosting environment. I'm somewhat familiar with Ubuntu, so I'd be looking at adding an appropriate script to `/etc/init.d/`, and adding it to the boot process with `update-rc.d` - something along the lines of `sudo update-rc.d thinking-sphinx defaults`. I presume there's similar approaches for other Linux distros.

**Comment by atomical** [comment]
Thanks, will look into this.
