### ISSUE TITLE
Searching for record with no values in MVA

### ISSUE THREAD

**Issue by JasonBarnabe** [pat/thinking-sphinx#1074]
Say a `Document` has zero to many `Author`s. If a `Document` an MVA of `author_id`, is there a way of searching for `Document`s with **no** `author_id`s other than creating a separate boolean attribute like `no_authors`?

I have tried setting `with[:author_id]` to `nil`, `0`, `[]`, and empty string.

**Comment by pat** [comment]
I _think_ the following should work:

```ruby
Document.search :select => "*, LENGTH(author_id) AS author_count", :with => {:author_count => 0}
```

**Comment by JasonBarnabe** [comment]
Thanks, that appears to work. Something to document?

**Comment by pat** [comment]
Done :)
https://freelancing-gods.com/thinking-sphinx/searching.html#zero-counts
