### ISSUE TITLE
thinking_sphinx not giving the near by match results

### ISSUE THREAD

**Issue by santoshbt** [pat/thinking-sphinx#1075]
Hello,

I am trying to implement the functionality similar to MySQL Like, but after trying lot of options, still unable to get the desired results. I am using thinking-sphinx-3.4.2.

Please help.

**Comment by pat** [comment]
Hi Santosh

Can you provide an example of what you're trying to do, and the behaviour you'd like to see?

**Comment by santoshbt** [comment]
For Example, I am indexing on article title, which has Ruby, Java, Book123 etc. I want the search output for "rub" string to be Ruby and "boo" has to give Book123 result. But it is returning 0 results. If I search for full word, I get the proper results. I have tried, star option, match_mode, min_infix option etc.. But no luck..

**Comment by pat** [comment]
I would expect the following to work:

In your `config/thinking_sphinx.yml`

```yml
development:
  min_infix_len: 1

# repeat for each environment
```

Don't forget to run `rake ts:rebuild` once you've made that change. And then when searching:

```
Article.search "rub", :star => true
```

**Comment by santoshbt** [comment]
Hi Pat,

Thanks this worked.. 👍

**Comment by pat** [comment]
Great :)
