### ISSUE TITLE
Error with geodist

### ISSUE THREAD

**Issue by thimmaiah** [pat/thinking-sphinx#1076]
Im running the following in the rails console
`User.search "Mohith", :geo => [@lat, @lng], :with => {:geodist => 0.0..10_000.0}`

I get the following error
```
ThinkingSphinx::SyntaxError: sphinxql: syntax error, unexpected ',' near ', , latitude, longitude) AS geodist, * FROM `user_core` WHERE MATCH('Mohith') AND `geodist` BETWEEN 0.0 AND 10000.0 AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META' - SELECT GEODIST(, , latitude, longitude) AS geodist, * FROM `user_core` WHERE MATCH('Mohith') AND `geodist` BETWEEN 0.0 AND 10000.0 AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/connection/client.rb:44:in `rescue in perform'
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/connection/client.rb:47:in `perform'
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/connection/client.rb:30:in `check_and_perform'
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/connection/client.rb:15:in `query_all'
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/search/batch_inquirer.rb:17:in `block in results'
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/connection.rb:39:in `block in take'
	from /home/thimmaiah/.rvm/gems/ruby-2.4.0/gems/innertube-1.1.0/lib/innertube.rb:138:in `take'

```

My index is as follows

```
ThinkingSphinx::Index.define :user, :with => :real_time do
  # fields
  indexes first_name
  indexes last_name
  indexes postcode
  indexes speciality

  # attributes
  has lat, :as => :latitude,  :type => :float 
  has lng, :as => :longitude,  :type => :float
  has verified, :type=>:boolean
  has phone_verified, :type=>:boolean
  has role, :type=>:string
  has auto_selected_date, :type => :timestamp
end
```

**Comment by pat** [comment]
It looks like `@lat` and `@lng` are nil - can you confirm if they're being set to float values?

**Comment by thimmaiah** [comment]
Confirmed Pat, they are not nulltext in the response when I search just for the name

.4.0 :020 >   users = User.search "Mohith"
 => [#<User id: 953, provider: "email", uid: "thimmaiah@gmail.com", first_name: "Mohith", last_name: "Thimmaiah", email: "thimmaiah@gmail.com", role: "Care Giver", nurse_type: nil, created_at: "2017-09-10 18:36:08", updated_at: "2017-10-08 16:22:21", sex: "F", phone: "2125555351", address: "7721 Willa Canyon", languages: nil, pref_commute_distance: 1000, occupation: nil, speciality: nil, experience: nil, referal_code: nil, accept_terms: true, care_home_id: nil, active: true, image_url: nil, sort_code: "255733", bank_account: "15045561", verified: true, auto_selected_date: nil, **lat: 0.558609883573854e2, lng: -0.424865379052141e1**, postcode: "G2 9SG", total_rating: 5, rating_count: 2, push_token: nil, deleted_at: nil, unsubscribe_hash: "b5e4e21de22d7d6f1f5bc5c74ca570f5", subscription: true, verified_on: "2017-09-10", verification_reminder: nil, locale: nil, phone_verified: true, accept_bank_transactions: nil, accept_bank_transactions_date: nil, sms_verification_code: nil, title: "Miss", ready_for_verification: nil>]

**Comment by pat** [comment]
Sorry, I meant when you're searching:

```ruby
User.search "Mohith", :geo => [@lat, @lng], :with => {:geodist => 0.0..10_000.0}
```

If there are situations where the `:geo` arguments are going to be nil, you should not include that or the `:geodist` filter in your search query. For example:

```ruby
if @lat.nil? || @lng.nil?
  User.search "Mohith",
else
  User.search "Mohith", :geo => [@lat, @lng], :with => {:geodist => 0.0..10_000.0}
end
```

**Comment by thimmaiah** [comment]
Pat you nailed it, sorry about reporting this, just plain dumb that I had those set to nil. Thanks for all the help & sorry for the bother.

Cheers

**Comment by pat** [comment]
No worries :)
