### ISSUE TITLE
4GB it's max size index table? Really?

### ISSUE THREAD

**Issue by nihe33** [pat/thinking-sphinx#1079]
My first using Sphinx and Thinking Sphinx... Ohh... After run my first rake task ts:rebuild I'm see this message:

> indexing index 'xdocument_core'...
> ERROR: index 'xdocument_core': too many string attributes (current index format allows up to 4 GB).
> total 1425236 docs, 3530943631 bytes
> total 331.702 sec, 10644895 bytes/sec, 4296.72 docs/sec

Many string attributes.... Ok, I'm read [manual](https://freelancing-gods.com/thinking-sphinx/common_issues.html#string_filters) and added crc32, but it's not solved this problem. This my indices:

```
ThinkingSphinx::Index.define :xdocument, delta: true, with: :active_record do
  indexes url,        sortable: true
  indexes content,    sortable: true
  indexes sysname,    sortable: true
  indexes is_checked,      sortable: true
  indexes source_content,  sortable: true

  indexes author.name,        as: :field_author_name, sortable: true
  indexes author.ip,          as: :field_author_ip
  indexes author.description, as: :field_author_comment

  has id,         as: :attr_sort_document_id,         type: :integer
  has created_at, as: :attr_sort_document_created_at, type: :timestamp
  has empl_name,  as: :attr_sort_document_empl_name,  type: :string
  has sys_role,   as: :attr_sort_document_sys_role,   type: :string
  has sys_type,   as: :attr_sort_document_sys_type,   type: :string

  has author.room_num,                   as: :attr_sort_author_room_num,         type: :integer
  has 'CRC32(authors.team)',             as: :attr_sort_author_team,             type: :string
  has 'CRC32(authors.country)',          as: :attr_sort_author_country,          type: :string
  has 'CRC32(authors.city)',             as: :attr_sort_author_city,             type: :string
  has 'CRC32(authors.group_name)',       as: :attr_sort_author_group_name,       type: :string
  has 'CRC32(authors.type_machi)',       as: :attr_sort_author_type_machi,       type: :string
  has 'CRC32(authors.office_type)',      as: :attr_sort_author_office_type,      type: :string
  has 'CRC32(authors.version_product)',  as: :attr_sort_author_version_product,  type: :string
  has author.last_change_at,             as: :attr_sort_author_last_change_at, type: :timestamp
end  
```

and this model:

```
class Xdocument < ApplicationRecord
  belongs_to :author

  # .... scopes
end


class Author < ApplicationRecord
  has_many :x_documents, dependent: :delete_all

  # .... scopes
end
```

I'm trying make a big filter like this one for example:

https://www.drupal.org/files/project-images/exposed_form_layout_0.png
![image](https://user-images.githubusercontent.com/34854100/34351374-2b991e46-e9d1-11e7-920b-e29e12de2f02.png)

Maybe there are some tips? I have two tables with data. In the first about 300 million documents (Xdocuments table), and in the second about 20 thousand items (authors table).

I hope for your help, because I can not solve the problem for many hours ...

P.S. debian 8.1, sphinx 2.3.2-id64-beta, thinking sphinx - last release.

**Comment by pat** [comment]
I didn't realise Sphinx had a limit, but still, I think there's potential to change your index to reduce the size.

For every field where you're specifying `:sortable => true`, it's worth considering whether you actually need to sort by that field. When they're sortable, there's also a corresponding string attribute. For example: are you sorting by content anywhere? source_content? They sound like large text fields, and I find those are rarely useful for sorting.

Also, for your CRC'd columns, there's two things to note. Firstly, the CRC32 function will return an integer, so you can set the attribute types to integer rather than string. Secondly, if you want to filter by those specific values, the versions of TS and Sphinx that you're using should allow that to happen - and so, you don't actually need to use the CRC32 approach.

One more thing, though this is unrelated to string attributes: is `is_checked` a boolean column? If so, I think it'd make more sense as an attribute, rather than a field. Generally it only makes sense to use string/text columns for fields, as they're the textual data that Sphinx matches query terms on. Anything that's only used for sorting/filtering (the common use-case for boolean values) should be an attribute.

**Comment by nihe33** [comment]
Can there be other solutions? Split indexes or change the limit? Now this is an incomplete table. It contains about 5-10% of all data (it is planned that it will be about 500-900GB of text for one table).

> For every field where you're specifying :sortable => true, it's worth considering whether you actually need to sort by that field. When they're sortable, there's also a corresponding string attribute. For example: are you sorting by content anywhere? source_content? They sound like large text fields, and I find those are rarely useful for sorting.

Yes, many fields for sorting (from 10 and more), and many fields for search (6 for search and about 12 for filtering). Text fields can sometimes contain as one word, so can contain 10 megabytes of text. Yes, I understand that it is idiocy, but alas - such a legacy.


> Also, for your CRC'd columns, there's two things to note. Firstly, the CRC32 function will return an integer, so you can set the attribute types to integer rather than string. Secondly, if you want to filter by those specific values, the versions of TS and Sphinx that you're using should allow that to happen - and so, you don't actually need to use the CRC32 approach.

It did not help :(

**Comment by pat** [comment]
> Text fields can sometimes contain as one word, so can contain 10 megabytes of text. Yes, I understand that it is idiocy, but alas - such a legacy.

The joys of legacy systems. One workaround could be to create truncated versions of these long columns? How accurate does the sorting need to be - down to 10 characters? 20? Could help reduce the index size.

> Split indexes or change the limit?

I don't think this limit is configurable, but yes, you could potentially have many indices. You'd need to do that in a somewhat manual sense:

```ruby
# tweak these numbers, or possibly source them
# from the db based on the total number of records?
shard_size = 1_000_000
shards = 300

shards.times do |shard|
  ThinkingSphinx::Index.define :xdocument, delta: true, name: "xdocument_{shard}", with: :active_record do
    # ...

    where "id > #{shard * shard_size} AND id <= #{(shard + 1) * shard_size}"
  end
end
```

I have a feeling any update to a single record with deltas will result in delta updates to _all_ shard indices, though. Still, maybe it's worth it, if you can find the right balance of the number of shards?

**Comment by nihe33** [comment]
I solved the problem... Removed sorting from content field and sysname. Now all is well. The customer still wants sorting, but I think I will be better to sort the search result. Then I will need to sort only 10 000 items. But I guess I still do shards, as you suggested. Just in case.


@pat , thanks for the help. Tell me, where you can see the list of rake tasks? I created the configuration (ts:rebuild) and did the indexing (ts:index). Now I want to start a reindexing delta indexes, but ts:in:delta not working. Then I tried the ts:index, but started a full indexing of the data. 


Also, I do not understand where a rake command: merge and rotate.

**Comment by pat** [comment]
Great to hear you've found an approach that works. I've answered the delta questions in #1080, so I'll close this issue.

**Comment by nihe33** [comment]
Thanks for the help!
