### ISSUE TITLE
SSL connection error

### ISSUE THREAD

**Issue by LTran1231** [pat/thinking-sphinx#1081]
I'm trying to connect sphinx with SSL and getting the following error. Rails was able to connect with SSL just fine. 

ERROR: index 'dataset_core': sql_connect: SSL connection error: SSL_CTX_set_default_verify_paths failed (DSN=mysql://***:***@******.amazonaws.com:3302/***).

**Comment by pat** [comment]
I don't work with MySQL much myself, but my understanding is that Sphinx needs to have certificate details to connect. You can specify these using [the mysql_ssl_* settings for Sphinx](http://sphinxsearch.com/docs/current.html#conf-mysql-ssl), and these can be set per-environment in `config/thinking_sphinx.yml`.
