### ISSUE TITLE
[Every 24 Hours]Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1'

### ISSUE THREAD

**Issue by elorest** [pat/thinking-sphinx#1083]
I'm getting the Error `Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1'` Every 24 hours running `rake ts:rebuild` fixes it. The application has worked fine for year and now for the last 2 weeks it's been giving me this error. 

Can you think of any reason that it would have started doing this? Also from reading similar issues it looks like it's actually searchd that is missing. Why does it say `via the Mysql protocol`?

In my crontab I have it set to run `ts:rebuild` on reboot. and run `rake ts:index` every 10 minutes.

**Comment by pat** [comment]
Hi Isaac,

Firstly, the "via the MySQL protocol" part of the message: Sphinx uses the MySQL protocol for connections (hence the mysql2 gem requirement), and all connection errors bubble up from mysql2.

I'm not sure what's causing the problem though. Does it always happen at the same time? Are there any clues in the Sphinx logs? (i.e. does it seem that the searchd process has actually stopped? Did it crash, or was it stopped gracefully?). Do you have the output from when you run `ts:rebuild`? (As that may suggest whether searchd was already running when it's executed).

**Comment by elorest** [comment]
Thanks Pat,

It indeed seems that the process is no longer running. The only thing I'm running which should affect it at all is `ts:index` every 10 minutes. If I also run `ts:start` it errors about already being running but restarts the process when it dies.

Where would I look for information it it crashed. I've grep'd through all the thinking-sphinx logs but maybe I'm not looking for the right thing. In the past there was a `ts:reindex` but it seems that plain `ts:index` swaps out indexes on running processes now.

**Comment by pat** [comment]
`ts:index` should be the only thing you need to run regularly, so that part sounds fine. Using `ts:start` like you've suggested is a feasible workaround, though it'd be nice to find the underlying problem.

The Sphinx logs I'm referring to are configured in `config/thinking_sphinx.yml` per environment using the `log` key - and it ends up within the `searchd` section of the generated configuration file as `log` as well. It generally covers events like the daemon starting and stopping and indices being rotated - given you're doing a full index every ten minutes (and that'll finish with the rotation), it could be a little busy, but would be good to trawl back through it to when the daemon seems to have stopped.

Also, which version of Sphinx are you using?

**Comment by pat** [comment]
Oh, and while I'm asking about versions - which version of Thinking Sphinx are you using?

**Comment by elorest** [comment]
Sphinx: 2.2.6
TS: 3.1.4

**Comment by pat** [comment]
If you find crashes in the logs of Sphinx, it could be worth upgrading to 2.2.11 (indeed, might be worthwhile anyway?).

And wouldn't hurt to investigate upgrading TS up to something more recent (the [release notes](https://github.com/pat/thinking-sphinx/releases) cover off required changes quite well, I feel) - though I don't think this will change anything related to the issue you're dealing with.

**Comment by elorest** [comment]
Here's one from my birthday. :)
Is a TS upgrade required for to upgrade sphinx to 2.2.11? This is a legacy project that just needs to run for now. Not a lot of development going on right now.

```
[Mon Feb  5 17:10:05.961 2018] [ 4921] caught SIGHUP (seamless=1, in queue=1)
------- FATAL: CRASH DUMP -------
[Mon Feb  5 17:10:05.961 2018] [ 4921]

--- crashed SphinxAPI request dump ---

--- request dump end ---
Sphinx 2.2.6-id64-release (r4843)
Handling signal 11
-------------- backtrace begins here ---------------
Program compiled with x86_64-linux-gnu-gcc 4.8
Configured with flags:  '--host=x86_64-linux-gnu' '--build=x86_64-linux-gnu' '--prefix=/usr' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--localstatedir=/var/lib/sphinxsearch' '--sysconfdir=/etc/sphinxsearch' '--with-mysql' '--with-pgsql' '--enable-id64' '--with-libstemmer' '--with-re2' '--with-unixodbc' '--with-syslog' 'CFLAGS=-Wall -g -O3' 'LDFLAGS=-Wl,-z,defs  -pthread' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu'
Host OS is Linux trusty64 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Stack bottom = 0x7fffc04eea8f, thread stack size = 0x100000
Trying manual backtrace:
Something wrong with thread stack, manual backtrace may be incorrect (fp=0xb)
Wrong stack limit or frame pointer, manual backtrace failed (fp=0xb, stack=0x7fffc04f0000, stacksize=0x100000)
Trying system backtrace:
begin of system symbols:
searchd[0x58bba0]
searchd[0x40eddd]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f8005987340]
searchd[0x438950]
searchd[0x43c1e9]
searchd[0x45afbc]
searchd[0x45c6c6]
searchd[0x408977]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f80040cdec5]
searchd[0x408e15]
-------------- backtrace ends here ---------------
Please, create a bug report in our bug tracker (http://sphinxsearch.com/bugs) and attach there:
a) searchd log, b) searchd binary, c) searchd symbols.
Look into the chapter 'Reporting bugs' in the documentation
(/usr/share/doc/sphinx/sphinx.txt or http://sphinxsearch.com/docs/current.html#reporting-bugs)
--- BT to source lines (depth 10): ---
--- BT to source lines finished ---
--- 3 active threads ---
thd 0, proto sphinxql, state net_idle, command update
thd 1, proto sphinxql, state net_idle, command update
thd 2, proto sphinxql, state net_idle, command update
------- CRASH DUMP END -------
```

**Comment by pat** [comment]
Nothing like crashing software as a birthday present ;)

There shouldn't be any issues with upgrading Sphinx and keeping TS on 3.1.4. And given it's Sphinx at fault, I think upgrading Sphinx is definitely the right place to start.

**Comment by elorest** [comment]
Cool. I upgraded that. I'll keep and eye on it and see if it crashes again. Thanks for your help.

You've been running this project what like 10 years now? I've been using it since 2009.

**Comment by pat** [comment]
Yup, passed the 10 year mark in early September last year :) Great to know you're still finding it useful!

**Comment by elorest** [comment]
Yep I've been fighting the good fight against elastic search :)

**Comment by elorest** [comment]
I've been a core member of a pretty ambitious open source project for about a year if you have an interest in Crystal Lang.

https://amberframework.org/

**Comment by pat** [comment]
Oh interesting. I've not yet played with Crystal… but will have to find some time to give Amber a spin 👍

**Comment by elorest** [comment]
I think you'll like it we've tried to keep all the best parts of Rails.
