### ISSUE TITLE
checking for nil value of a column in 'with' or 'without'

### ISSUE THREAD

**Issue by aakashhs** [pat/thinking-sphinx#1086]
I intend to search for rows where one of the columns should not be nil. I am using with, without , select , conditions but nothing is giving me results.

My code is something like this,

options: {without: {person_id: nil}}
@results = Model.search(search_string, options)

I am using version 3.3 .

Is there sonthing i am missing. Some online forums say sphinx doesnt check for null values

**Comment by pat** [comment]
Sphinx will store nil values in attributes as the value zero, so try the following:

`Model.search search_string, :without => {:person_id => 0}`

**Comment by aakashhs** [comment]
Thanks for the quick response! .. But it doesnt seem to work! 

Sphinx Query (2.0ms)  SELECT * FROM `accounts` WHERE MATCH('Mss scho') AND `sphinx_deleted` = 0 AND `person_id` <> 0 LIMIT 0, 20

It generated an above query and returned zero results .. however rows exist in database starting with 'Mss scho' and person_id present.

**Comment by pat** [comment]
Hmm. What does your index definition look like?

**Comment by aakashhs** [comment]
ThinkingSphinx::Index.define 'accounts', :with => :active_record, :delta => true  do
  indexes name, :weight => 100, :sortable => true
  has id, :as => :account_id
  has department(:id), :as => :department_id
  has active
  # we are applying the golbal search for the message reciepients, across the models attributes should be available.
  # So here we are creating dummy null attributes to filter the records
  has 'null', :as => :peer_or_community_id, :type => :integer
  has 'null', :as => :peer_or_member_id, :type => :integer
  has 'null', :as => :msg_department_id, :type => :integer
  has 'null', :as => :msg_community_id, :type => :integer

end

**Comment by pat** [comment]
There's no `person_id` attribute in there - you're going to need that if you want to filter by it :)

**Comment by aakashhs** [comment]
Dunno How  i missed it!!! Thanks Pat. Closing Issue!

**Comment by pat** [comment]
No worries, great to have it sorted :)
