### ISSUE TITLE
ts:rebuild destroys charset_table

### ISSUE THREAD

**Issue by hipertracker** [pat/thinking-sphinx#1089]
Is thinking-sphinx still using `config/sphinx.yml` file for Rails? After upgrading Sphinx Server every time I run `rails ts:rebuild` it creates  `production.sphinx.conf` file **without `charset_table` section**. 

And if 'sphinx.yml' file is no longer used, where to define my custom `charset_table` rules?

**Comment by pat** [comment]
Hi @hipertracker - which version of Thinking Sphinx are you using? If you're using any v3 release, the file has to be named `config/thinking_sphinx.yml`.

**Comment by hipertracker** [comment]
I am using version 3.0.4. It was that! I also found that I can use `set_property` like here https://github.com/pat/thinking-sphinx/blob/develop/spec/internal/app/indices/city_index.rb#L7 (although I could not set mem_limit this way because it is not a part of the index, but indexer setting)
