### ISSUE TITLE
Starting sphinx on box restart

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1093]
Hi Pat,

Do you start searchd when the box is first booted? Or do you defer to one of the thinking sphinx rake tasks?

**Comment by pat** [comment]
I would personally feel comfortable interacting with `searchd` directly, but then I've had a lot of practice with that :) Certainly, go with what you're most comfortable with - the rake task is fine, it's just a bit slower (as it involves loading the Rails app).
