### ISSUE TITLE
Too may files open

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1095]
Hi Pat,

Have you ever seen this in the searchd log?
```
[Thu Apr 12 10:45:01.596 2018] [21282] rotating index 'activation_description_core': started
[Thu Apr 12 10:45:01.597 2018] [21282] WARNING: rotating index 'activation_description_core': prealloc: failed to open file '/var/www/shared/db/sphinx/activation_description_core.new.spm': 'Too many open files'; using old index
[Thu Apr 12 10:45:01.597 2018] [21282] rotating index: all indexes done
```

**Comment by pat** [comment]
I may have seen it in one situation where a Flying Sphinx customer had several dozen indices (at the very least, it sounds like a similar issue). One thing that helped is starting `searchd` after `ulimit` has been set to allow a higher number of open files for the process.

Are you dealing with a large number of indices? Or, possibly, such a large amount of data that there is a significant number of tmp files generated through the indexing process?

Also, which versions of Sphinx and Thinking Sphinx are you using?

**Comment by pat** [comment]
Adam, I'm going to close this issue given it's gone quiet - but still, feel free to comment further and I'll help where I can :)
