### ISSUE TITLE
ID UUID type exception

### ISSUE THREAD

**Issue by lukaszsliwa** [pat/thinking-sphinx#1096]
**id** column is **uuid** type. How to configure/index?

```
CREATE TABLE public.projects
(
  id uuid NOT NULL DEFAULT gen_random_uuid(),
...
```

It seems that no **uuid** type was defined for sphinx

```ruby
Generating configuration to /home/t/Work/ai/app/config/development.sphinx.conf
rake aborted!
ThinkingSphinx::UnknownAttributeType: Unable to determine an equivalent Sphinx attribute type from Symbol for attribute sphinx_internal_id. You may want to manually set the type.

e.g.
  has my_column, :type => :integer
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/active_record/attribute/type.rb:91:in `type_from_database'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/active_record/attribute/type.rb:19:in `type'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/active_record/attribute.rb:6:in `type'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/configuration/consistent_ids.rb:10:in `block in reconcile'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/configuration/consistent_ids.rb:9:in `any?'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/configuration/consistent_ids.rb:9:in `reconcile'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/configuration.rb:165:in `normalise'
/home/t/.rvm/gems/ruby-2.4.0/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/configuration.rb:94:in `block in preload_indices'

```

**Comment by pat** [comment]
Sphinx has no UUID type, I'm afraid - it only allows integers for its primary keys.

To use Thinking Sphinx with a UUID primary key, you need to create a column with unique integer values (functioning the same way as the standard integer primary id column), and then you can tell Thinking Sphinx to use that column as a reference instead:

```ruby
ThinkingSphinx::Index.define :project, :primary_key => :integer_id do
  # ...
end
```

**Comment by lukaszsliwa** [comment]
Thank you @pat . It seems i will have to forget about uuid.

**Comment by pat** [comment]
Just to be clear: you can use UUIDs in your app as much as you'd like - it's just you _also_ need an unique integer column for any models that have Sphinx indices.

**Comment by lukaszsliwa** [comment]
Thanks @pat and thank you for the work you do here for such a long time. Some projects couldn't start without your gem.

**Comment by vkeziah** [comment]
has "followers.id, :as => :follower_id, type: :integer 

Where follower.id is string type(for ex: "bSv_K-X4g5duJQsV83Bzaw"). 

I couldnt make it work with Sphinx , Can any one help me ? its works fine with integer ids but I need to do it with ids I mentioned above ? is there any proper way to do it sphinx search? 

Thanks

**Comment by pat** [comment]
Hi @vkeziah - I'm afraid you can't have multi-value string attributes in Sphinx. You'd perhaps want to use a field instead:

```ruby
indexes followers.id, :as => :follower_ids
```

… but that means you'd probably also want to [tweak `charset_table`](https://freelancing-gods.com/thinking-sphinx/v4/advanced_config.html#character-sets-and-tables) to allow for _ and - and any other non-alphanumeric characters - but this will impact all fields, not just this specific field.

An alternative approach if you need to filter by specific followers is to have a unique integer column in the followers table and use that in an attribute instead (much like what's been discussed here already). I know that's not ideal either, but these are the limitations of Sphinx.

**Comment by vkeziah** [comment]
Thanks @pat I agree with your solution and only way I have now :) 

> An alternative approach if you need to filter by specific followers is to have a unique integer column in the followers table and use that in an attribute instead (much like what's been discussed here already)

**Comment by lunaru** [comment]
@pat Sorry for resurrecting this old thread, but I figure I might as well keep the question contained within an existing thread:

So as you mentioned above, UUID is not supported by Sphinx out of the box. Is there any reason something like this doesn't work?

```
has relation.some_id, as: :relation_id, type: :string
```

I just tried doing this and everything seems to work on the surface, but when inspecting the actual index, the column is always empty. It also doesn't match NULL, '', or IS NOT NULL. Quite weird. Any ideas?
```

**Comment by lunaru** [comment]
It looks like this solution works:

```
has relation.some_uuid, type: :string
```

This gets sphinx to index the UUID as a string attribute for querying. However, it doesn't handle NULLs very well, so this is further needed if querying on NULL values is necessary:

```
has "coalesce(\"relation\".\"some_uuid\"::VARCHAR(250), '-')", :as => :relation_uuid, type: :string 
```

This turns NULL values into "-" in the index, so that they can be matched against.

**Comment by pat** [comment]
I think the workaround you've got is the best way forward - Sphinx doesn't have a concept of NULL, so yeah, what you've done is necessary, I'm afraid. Glad to you you got it figured out! :)
