### ISSUE TITLE
How to use ThinkingSphinx::Distributed::Index

### ISSUE THREAD

**Issue by chris-roerig** [pat/thinking-sphinx#1097]
Hi Pat, 

Is there documentation on creating distributed indexes? We are moving to a distributed setup and from what I've researched it appears in addition to updating the main config, each index file will also need to specify its type (distributed) and agent addresses etc. 

Something like the following: 

```
index master
{
  type = distributed
  local = items
  agent = 192.168.1.2:9312:items-2
}
``` 

I found this https://www.rubydoc.info/github/pat/thinking-sphinx/ThinkingSphinx/Distributed/Index but I'm not clear on when and where to use that class.

Thanks

**Comment by pat** [comment]
Hi Chris,

At this point in time, the distributed index support in TS is only there to collect both core and delta indices. It doesn't handle Sphinx instances in other locations.

I'm certainly not against adding something more useful for you. Can you talk through how you're thinking of structuring servers and indices, so I can get a better idea of what's needed?

**Comment by chris-roerig** [comment]
Thanks for the reply. I'm putting a load balancer in front of multiple machines serving the same Rails app. The app uses real time indexing and employs TS for filtering and search from the app's index pages. Ideally the configuration would follow the distributed model provided by Sphinx. http://sphinxsearch.com/docs/current/distributed.html

What other info can I provide that you would find helpful? Thanks!

**Comment by pat** [comment]
I'm presuming in this setup you're going to have Sphinx on each of the Rails servers? Have you considered just pointing them to a single Sphinx server instead? Or are you expecting the load to be too much for a single server?

**Comment by chris-roerig** [comment]
I haven't found a way to set them up to use a single server. My understanding is the indices are created locally regardless of where the mysql database is. Do you have any insight or docs on that?

**Comment by pat** [comment]
mmm, this is something that could definitely be documented in more detail.

You'll want to have a copy of your Rails app deployed to your Sphinx server, and have [`address`](https://freelancing-gods.com/thinking-sphinx/v4/advanced_config.html#daemon-address) in the appropriate environment within `config/thinking_sphinx.yml` set to its public IP (public within the context of your Rails servers, at least). From there, make sure you invoke all TS-related rake tasks on that Sphinx server, and the address setting will be picked up on the Rails machines and they'll send all Sphinx-related requests to that.

**Comment by chris-roerig** [comment]
Thanks for your help Pat, I'll continue to investigate this.
