### ISSUE TITLE
geo_args with multiple addresses

### ISSUE THREAD

**Issue by dikey94** [pat/thinking-sphinx#1099]
Hi Pat,
I'm looking for some help with geo_args; I have to search with multiple addresses. My model (Specialist) has many Places and many Workplaces. I need to find find all specialists with Places or Workplaces in my location. 

What's the correct way to do this?
Thanks.

**Comment by pat** [comment]
Sphinx can't take multiple geo locations into account per record, so I think the better approach here is to search on Place and/or Workplace, using their single geo points, and then refer to their specialists from there.

You may want to bring in specialist information into fields/attributes within the place/workplace index definitions so the search has everything required.

Does that all make sense?

**Comment by dikey94** [comment]
I think so.

I've searched for Places or Workplaces using their geopoints. I've end up with an array of Specialist ids. The ids must be passed into Specialist search query.

Is it  necessary to set 'id' attribute inside the Specialist index?

Thanks.

**Comment by pat** [comment]
There's already an id attribute available, added by Thinking Sphinx itself - called `sphinx_internal_id` - so you can use that.

A couple of other things to note:

* You can use `ThinkingSphinx.search "foo", :classes => [Place, Workplace]` if you want to search across both models at once.
* There's also the option of adding `:sql => {:includes => :specialist}` to your search call as well, which will load the Specialist objects which loading Place/Workplace instances. Thus, you can use just the one search call and have pagination and ordering working as expected.

**Comment by dikey94** [comment]
Yep. Works as expected. Thank you Pat.

The issue can be closed.
