### ISSUE TITLE
Define index with name

### ISSUE THREAD

**Issue by kortirso** [pat/thinking-sphinx#1102]
I have index file and I can run search by `Element.search`

    ThinkingSphinx::Index.define :element, with: :active_record do
      # fields
      indexes letter_code, sortable: true
      indexes name, sortable: true
      # properties
      set_property min_infix_len: 1
    end

but I'd like to split it for 2 with different properties, if one of them will be with name like

    ThinkingSphinx::Index.define :element, name: 'name_element', with: :active_record do
      # fields
      indexes name, sortable: true
      # properties
      set_property min_infix_len: 3
    end

How can I run search for such index?

**Comment by pat** [comment]
You'll want to use the `:indices` option, which takes an array of index names - including the _core/_delta suffixes. So, in this case:

```
Element.search "foo", :indices => ["name_element_core"]
```

**Comment by kortirso** [comment]
Works great, thanks
