### ISSUE TITLE
Sharing DB files across multiple servers

### ISSUE THREAD

**Issue by chris-roerig** [pat/thinking-sphinx#1103]
Hi Pat,

Are there any negative implications to sharing indexed DB files across many servers? My situation involves handling a failover situation where one server becomes unavailable and traffic is sent to another box. In this case I would want the DB files to be up to date as if nothing happened. Each server would mount the same NFS share where the files would live. What do you think?

**Comment by pat** [comment]
Hi Chris

I _think_ this would be fine, with a couple of caveats:

* Indexing (if you're using SQL-backed indices) should only happen on one machine (I'm guessing the current primary) to avoid the index files being manipulated concurrently.
* Having index files stored on an external server will definitely slow down indexing (in the past I've experimented with EBS volumes versus local disks on EC2 instances, and the latter is definitely faster - even more-so when SSDs are in play).

Another option could be to have a single dedicated Sphinx server, and have all Rails app servers talk to that - you'll still need a copy of the Rails app to run on that Sphinx server though (so you can invoke all of the `ts` rake tasks there). But that doesn't address the situation of that Sphinx server having a failover.

**Comment by chris-roerig** [comment]
Thanks Pat.
