### ISSUE TITLE
Issues with UTF8 queries 

### ISSUE THREAD

**Issue by sesaretah** [pat/thinking-sphinx#1108]
Hi,
In order for some of the UTF8 queries to work, we need to set 
`sql_query_pre = SET CHARACTER_SET_RESULTS=utf8`

How can we do that in ts?

**Comment by pat** [comment]
Hi @sesaretah - can you let me know which versions of Sphinx, thinking-sphinx and Ruby you are using? This setting may have been useful in the past, but recent versions of Sphinx should be communicating with UTF8 by default.

**Comment by sesaretah** [comment]
Hi,

ruby 2.5.1p57
rails 4.2.8
ts 4.0
Sphinx 2.2.11-id64-release (95ae9a6)

searches only get result when I change ts's deafult `sql_query_pre` to `SET CHARACTER_SET_RESULTS=utf8` and index it manually

**Comment by pat** [comment]
I guess it's an issue for Sphinx talking to your database I guess?

Still, to answer your original question - which I should have done in my previous message! - you can put the following in `config/thinking_sphinx.yml` for each environment:

```yml
production:
  sql_query_pre:
  - "SET CHARACTER_SET_RESULTS=utf8"
```

**Comment by sesaretah** [comment]
Thank you. It worked.
For any future references, the following config worked for me when indexing "Arabic, Persian and Urdu"
`production:
      charset_table: 0..9, a..z, _, A..Z->a..z, U+621..U+63a, U+640..U+64a,U+66e..U+66f, U+671..U+6d3, U+6d5, U+6e5..U+6e6, U+6ee..U+6ef, U+6fa..U+6fc, U+6ff
      sql_query_pre:
        - "SET CHARACTER_SET_RESULTS=utf8"`
And the database's collation is `utf8_general_ci`

**Comment by pat** [comment]
Great to know - thanks for the solution and the extra details :)
