### ISSUE TITLE
Problem with UTF8

### ISSUE THREAD

**Issue by sesaretah** [pat/thinking-sphinx#1109]
The following Rails query:
```ruby
Article.search 'book'
```
turns into 
```sql
SELECT * FROM `article_core` WHERE MATCH('book') AND `sphinx_deleted` = 0 LIMIT 0, 20
```
but
```ruby
Article.search 'روسیه'
```
turns into 
```sql
SELECT `articles`.* FROM `articles` WHERE `articles`.`id` IN (1, 3)
```
Why this happens?

**Comment by pat** [comment]
Can you re-check your logs on this? I think the second query you have there (on `articles`) is an ActiveRecord query, whereas the first (on `article_core`) is to Sphinx.

**Comment by pat** [comment]
Also, it's worth noting: each search call results in a query to Sphinx, and _then_ a query to your database to translate the Sphinx results into ActiveRecord objects. Hence why you're seeing both types of queries.

**Comment by pat** [comment]
Thanks for sharing the solution :)
