### ISSUE TITLE
Ignoring soft deleted records when indexing

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1110]
Hi,

Is there a way to have the indexer ignore certain records? We have a boolean value that indicates soft deletes. We shouldn't need to index those rows.

**Comment by pat** [comment]
Hi Adam

Yup, this is possible for both SQL-backed and real-time indices:
https://freelancing-gods.com/thinking-sphinx/v4/indexing.html#conditions

It's worth noting that if you're using real-time indices you probably want to customise the callback approach as well, to avoid processing soft-deleted records:
https://freelancing-gods.com/thinking-sphinx/v4/indexing.html#callbacks

If any of this isn't clear, do let me know!
