### ISSUE TITLE
How to filter by virtual attribute?

### ISSUE THREAD

**Issue by w0st** [pat/thinking-sphinx#1115]
Hello, 

As far I know I can't use `OR` with attribute filters (https://freelancing-gods.com/thinking-sphinx/v4/searching.html#filters) inside `WHERE` . SphinxQL doesn't support it. So I'm trying to go with a virtual attribute.

I want to build a query to Sphinx similar to below one's using `thinking-sphinx`:

```
SELECT *, ((attr >= min AND attr <= max) OR (another_attr > min AND another_attr <= max)) AS virtual_attr FROM `entity_core`, `entity_delta` WHERE virtual_attr = 1 ORDER BY `sort_date` DESC LIMIT 0, 24 OPTION field_weights=(title=10, category=8, description=3), max_query_time=1000;
```
where `min` and `max` are numbers.

How can I achieve the same effect using `thinking-sphinx` API?

**Comment by pat** [comment]
You can do this using the `:select` option:

```ruby
Entity.search(
  :select => "*, ((attr >= min AND attr <= max) OR (another_attr > min AND another_attr <= max)) AS virtual_attr"
  :with => {:virtual_attr => 1}
)
```

**Comment by manticoresearch** [comment]
Or you can use Manticore where this problem is solved, i.e. you can do OR with attribute filters.

**Comment by w0st** [comment]
Thanks for confirmation the best way to achieve it.

**Comment by pat** [comment]
While Thinking Sphinx can be used with Manticore, Thinking Sphinx has no ability at this point in time to send through OR conditions. PRs are welcome though!
