### ISSUE TITLE
Rebuild Part of indexes

### ISSUE THREAD

**Issue by mtamhankar1** [pat/thinking-sphinx#1117]
I may have just missed this in the docs. Is it possible to rebuild the indexes for one model, but not others?

**Comment by pat** [comment]
It is in the documentation, but not particularly obvious - it's right at the bottom of the page:
https://freelancing-gods.com/thinking-sphinx/v4/indexing.html#processing

Use the `INDEX_FILTER` environment variable to specify certain index names:

```
rake ts:index INDEX_FILTER=article_core,user_delta
```

**Comment by mtamhankar1** [comment]
Thanks for the quick responses!
