### ISSUE TITLE
Greater/less than and contains

### ISSUE THREAD

**Issue by MiselAdemi** [pat/thinking-sphinx#1118]
I am using Sphinx in my app and now I need to implement filter form. User can select from form dropdown inputs which field he want to filter and how. For example user can select that he want's to filter by title where title contains some string. 
I don't see option in sphinx to manage greater/less than or contains condition for searching. 
Is there some way to make this work with sphinx?

**Comment by pat** [comment]
@MiselAdemi ah, did you figure out how this is done?

In case you didn't (or for anyone else who comes across this issue): it's possible by using dynamic attributes and then filtering upon them. Here's an example:

```
Model.search "foo",
  :select => "*, IF(cost < 1000, 1, 0) AS maximum_cost",
  :with   => {:maximum_cost => 1}
```
