### ISSUE TITLE
Load balanced app servers and sphinx

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1119]
We are load balancing our application servers, but we think it would be easier to put searchd and indexer on one server.

Each box would have Redis. Jobs should be picked up by Sidekiq workers that only run on the same server as searchd and indexer.

Aside from setting the address of the server in thinking_sphinx.yml is there anything else we should do?

**Comment by pat** [comment]
I think this is implicit in your understanding (given you're talking about running Sidekiq on the Sphinx server), but just in case: you'll want a full copy of your Rails app on the Sphinx server, and that's where all the ts rake tasks should operate (along with, as you've noted, delta jobs).

And yes, setting the address is correct too :)

Beyond that, I think that's the essentials covered!
