### ISSUE TITLE
Bin log not found during deploy

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1122]
Hi Pat,

We've seen this a lot during deploys. I might have mentioned it in a few other issues. Any ideas on what might cause this show stopper?

We're using Thinking Sphinx 4.0.0 and Sphinx 2.3.2-id64-beta.

```
[f@current]$ tail -n 10000 /var/www/shared/log/searchd.log
[Wed Nov 14 09:46:39.317 2018] [11243] watchdog: main process 11244 forked ok
[Wed Nov 14 09:46:39.318 2018] [11244] listening on 127.0.0.1:9306
[Wed Nov 14 09:46:39.583 2018] [11244] binlog: replaying log /var/www/shared/config/binlog/binlog.001
[Wed Nov 14 09:46:39.583 2018] [11244] FATAL: binlog: log open error: failed to open /var/www/shared/config/binlog/binlog.001: No such file or directory
[Wed Nov 14 09:46:39.603 2018] [11243] watchdog: main process 11244 exited cleanly (exit code 1), shutting down
```

**Comment by pat** [comment]
Hrm. Maybe Sphinx has crashed at some point? There's nothing in the log prior to that indicating when it was last stopped it happened unexpectedly?

I presume you've got past it? The easiest way to do so is to delete everything in the binlog directory - and if you're using any real-time indices, reprocess the data to be on the safe side.

**Comment by pat** [comment]
Just to elaborate slightly: I feel like the binlog files being missing/invalid could happen due to Sphinx crashing… but if you're not seeing that, I'm less certain what the cause is in your case.

**Comment by atomical** [comment]
Possibly a crash. Closing this for now until I have more information.
