### ISSUE TITLE
Deploys and Sidekiq workers

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1130]
Hi Pat,

I'm wondering about how you do deploys. Do you shutdown the Sidekiq workers, copy the code, and then restart them or do you do rolling deploys where workers with new code are started before the old workers are shutdown?

I'm thinking of strategies to do zero downtime for Sidekiq workers in general.

Adam

**Comment by pat** [comment]
Hi Adam,

Most of my stuff runs on Heroku, so I don't have fine-grained control over that process. In the one case where I am managing things myself (Flying Sphinx's servers), I roll out the new code, and then tell  Sidekiq to stop accepting new jobs and stop itself once the current ones are done. Monit then gets it running again after that with the new code. So, it's not really zero downtime.

And within the TS context: I'm not using sidekiq deltas anywhere these days, opting for real-time indices instead.

**Comment by pat** [comment]
Closing this issue as it's been dormant for over a month. Feel free to add more comments though if further questions crop up :)
