### ISSUE TITLE
OS X Brew formulae no longer supports options, and only handles mysql. 

### ISSUE THREAD

**Issue by gorj-tessella** [pat/thinking-sphinx#1133]
The maintainers of brew have decided they will no longer support options, and are in the process of removing all of them (https://github.com/Homebrew/homebrew-core/issues/31510). This includes Sphinx, which as of Jan 13th now treats mysql as a dependency, does not handle postgresql at all, or indeed support any of the previously available options (https://github.com/Homebrew/homebrew-core/commit/42ad547dd443d8d541bd2f30c37d9313abcb77d4). 

At a minimum the installation documentation needs to be updated.  More generally, instructions for supporting postgresql need to be provided, either removing the brew instructions or providing an alternative. I have filed an issue with homebrew at https://github.com/Homebrew/homebrew-core/issues/39506 but I anticipate that they will not address the problem directly and insist that someone else should maintain a separate tap supporting sphinx with the necessary options.

**Comment by pat** [comment]
Thanks for bringing this to my attention! I've just updated the docs to recommend people use Sphinx's pre-built binaries, or compile things by hand.

It's a shame about the stance Homebrew have taken - and as an extra annoyance, they're still on Sphinx 2.2.11 - which makes sense to some extent, given the source for the v3.x releases isn't available, but also, it's broken with MySQL v8.
