### ISSUE TITLE
Distributed indices can't be used with .facets

### ISSUE THREAD

**Issue by gorj-tessella** [pat/thinking-sphinx#1135]
`ThinkingSphinx::Distributed::Index` does not provide a `facets` method. 

If you are using delta indexing for `Item` you will have two `ThinkingSphinx::ActiveRecord::Index`, `item_core` and `item_delta`. These will be in `ThinkingSphinx::Configuration`'s list of indices, along with a `ThinkingSphinx::Distributed::Index` `item`, which references both the core and delta indices. 

Note that `item` refers the the reference model `Item`, and is _not_ based on the original index name; if we had multiple indices for `Item`, we would still have only one `item` index. This goes against the common example where we want to search the core and delta indices for many different defined indices. 

If you want to perform `ThinkingSphinx.search` using the `:indices` option you can use any of the three indices, and they all work. However, if you want to do `ThinkingSphinx.facets` the `item` index work, because the `Distributed` index does not provide a `facets` method.

**Comment by pat** [comment]
I've just pushed a commit that should resolve this, into the `develop` branch. If you're able to test it and confirm it meets your needs, that'd be great!

And thanks for reporting this :)

**Comment by pat** [comment]
This fix is available in the newly-released v4.3.0 🎉
