### ISSUE TITLE
Problem when upgrading SphinxSearch from 2.x to 3.x

### ISSUE THREAD

**Issue by larryh** [pat/thinking-sphinx#1136]
Hi Pat,

First things first: Have been using your gem for years and love it - thanks a lot! (Have even weighed in on some previous issues.)

I recently upgraded your gem to 4.2, took advantage of your new real-time indices, and was able to successfully use them, along with the old active-record ones.

That was with SphinxSearch (SS) 2.x; just upgraded to the latest (3.1.1, as you can see from the output below) and, like many other updates, after having spent hours trying to get it to work, wish I had just left it alone. :-(

Anyway, that's life. And I need to upgrade SS on my server as well => might as well get 3.1.1 working.

The output below is from trying to do a ts:rebuild. The problem seems to be with the failure to install the libmysqlclient package. I don't know if this is a new requirement for SS 3.x; like I said, things worked fine with SS 2.x

I googled the error message and saw that someone said they installed 'libmysqlclient-dev' on their machine and it worked fine. (There was no just 'libmysqlclient' package listed.)

I tried that and got the second error message listed below. I've searched around for that and have spent hours trying to figure this out with no success. Since I'm sure a bunch of your users must have gone through this upgrade, I'm hoping you recognize this problem and remember a (simple, I hope) solution.

Any help you can give me will be greatly appreciated, as I am kinda at my wit's end on this. I have also pasted the contents of my development.sphinx.conf file in case that helps.

BTW, I am running on the latest Ubuntu: 19.04

Thanks,
Larry

================= ERROR RUNNING TS:REBUILD =================

Sphinx 3.1.1 (commit 612d99f)
Copyright (c) 2001-2018, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/home/larry/RubyMine/StupidTuesday/config/development.sphinx.conf'...
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.

stop: successfully sent SIGTERM to pid 1551
Stopped searchd daemon (pid: 1551).

Generating configuration to /home/larry/RubyMine/StupidTuesday/config/development.sphinx.conf
Generating configuration to /home/larry/RubyMine/StupidTuesday/config/development.sphinx.conf

Sphinx 3.1.1 (commit 612d99f)
Copyright (c) 2001-2018, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/home/larry/RubyMine/StupidTuesday/config/development.sphinx.conf'...

WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.

skipping non-plain index 'act_act_core'...
indexing index 'person_pol_core'...

ERROR: index 'person_pol_core': sql_connect: failed to load libmysqlclient (or libmariadb) (DSN=mysql://root:***@localhost:3306/stuptues_dev).

total 0 docs, 0.0 Kb
total 0.0 sec, 0.0 Kb/sec, 0 docs/sec

skipping non-plain index 'person_user_core'...
skipping non-plain index 'act_act'...
skipping non-plain index 'person_pol'...
skipping non-plain index 'person_user'...

The Sphinx indexing command failed:
  Command: /usr/local/bin/indexer --config "/home/larry/RubyMine/StupidTuesday/config/development.sphinx.conf" --all
  Status:  1
  Output:  See above

There may be more information about the failure in /home/larry/RubyMine/StupidTuesday/log/development.searchd.log. 
(MY NOTE: I deleted the contents of this file before running ts:rebuild to see if any specific information was written that could be helpful. Nothing was written into the log file.)

Process finished with exit code 1

=============== ERROR TRYING TO INSTALL LIBMYSQLCLIENT-DEV ===========

E: /var/cache/apt/archives/libmysqlclient-dev_5.7.26-0ubuntu0.19.04.1_amd64.deb: trying to overwrite '/usr/bin/mysql_config', which is also in package mysql-devel 5.5.50-2

============================= DEVELOPMENT.SPHINX.CONF ==============

indexer
{
}

searchd
{
  listen = 127.0.0.1:9306:mysql41
  log = /home/larry/RubyMine/StupidTuesday/log/development.searchd.log
  query_log = /home/larry/RubyMine/StupidTuesday/log/development.searchd.query.log
  pid_file = /home/larry/RubyMine/StupidTuesday/tmp/pids/development.sphinx.pid
  workers = threads
  binlog_path = /home/larry/RubyMine/StupidTuesday/tmp/binlog/development
}

index act_act_core
{
  type = rt
  path = /home/larry/RubyMine/StupidTuesday/db/sphinx/development/act_act_core
  docinfo = extern
  min_infix_len = 3
  rt_field = description
  rt_attr_uint = sphinx_deleted
  rt_attr_uint = pol_id
  rt_attr_bigint = sphinx_internal_id
  rt_attr_string = sphinx_internal_class
}

source person_pol_core_0
{
  type = mysql
  sql_host = localhost
  sql_user = root
  sql_pass = baron
  sql_db = stuptues_dev
  sql_sock = /var/run/mysqld/mysqld.sock
  sql_query_pre = SET TIME_ZONE = '+0:00'
  sql_query_pre = SET NAMES utf8
  sql_query = SELECT SQL_NO_CACHE `person_pols`.`id` * 6 + 1 AS `id`, CONCAT_WS(' ', `person_pols`.`first_name`, `person_pols`.`last_name`) AS `name`, `person_pols`.`id` AS `sphinx_internal_id`, 'Person::Pol' AS `sphinx_internal_class`, 0 AS `sphinx_deleted` FROM `person_pols` WHERE (`person_pols`.`id` BETWEEN $start AND $end AND status IN ('incumbent' ,'no_incumbent' ,'seeking_senate' ,'retiring')) GROUP BY `person_pols`.`id`, `person_pols`.`first_name`, `person_pols`.`last_name`, `person_pols`.`id` ORDER BY NULL
  sql_query_range = SELECT IFNULL(MIN(`person_pols`.`id`), 1), IFNULL(MAX(`person_pols`.`id`), 1) FROM `person_pols`
  sql_attr_uint = sphinx_internal_id
  sql_attr_uint = sphinx_deleted
  sql_attr_string = sphinx_internal_class
}

index person_pol_core
{
  type = plain
  path = /home/larry/RubyMine/StupidTuesday/db/sphinx/development/person_pol_core
  docinfo = extern
  min_infix_len = 3
  source = person_pol_core_0
}

index person_user_core
{
  type = rt
  path = /home/larry/RubyMine/StupidTuesday/db/sphinx/development/person_user_core
  docinfo = extern
  min_infix_len = 3
  rt_field = name
  rt_field = status
  rt_field = username
  rt_attr_uint = sphinx_deleted
  rt_attr_bigint = sphinx_internal_id
  rt_attr_string = sphinx_internal_class
  rt_attr_string = username_sort
}

index act_act
{
  type = distributed
  local = act_act_core
}

index person_pol
{
  type = distributed
  local = person_pol_core
}

index person_user
{
  type = distributed
  local = person_user_core
}

**Comment by pat** [comment]
Hi Larry,

Great to know the gem's mostly been working well for you for a long time! But yeah, this problem is certainly frustrating.

I'm not quite sure of the resolution, but it does sound like it's related to MySQL, and especially to particular versions/packages. Is it possible to remove the `mysql-devel` package? Seems like that's getting in the way of libmysqlclient-dev.

For what it's worth, v3.1.1 is the first Sphinx release to support MySQL v8 (which is the version that's immediately followed 5.7… 🤷‍♂) and I know some people who have updated MySQL without updating Sphinx have hit issues… but this seems to be a different problem. 🤔

**Comment by adriannuta** [comment]
The error `failed to load libmysqlclient (or libmariadb) ` states it can't find the library.

`/var/cache/apt/archives/libmysqlclient-dev_5.7.26-0ubuntu0.19.04.1_amd64.deb: trying to overwrite /usr/bin/mysql_config, which is also in package mysql-devel 5.5.50-2` 
Sounds like you have installed mysql from some other source than ubuntu official repos, hence the conflict.
It's possible that you have the libmysqlclient, but it's not on the paths searchd search for to find it.

Check also this article : https://manticoresearch.com/2019/06/05/mysql-source-wasnt-initialized-wrong-name-in-dlopen/ .

**Comment by larryh** [comment]
Hi guys,

Thanks for the quick replies - they certainly did help!

This whole process has been more of a `pita` than I anticipated (Huh. Probably the very first time a developer has had that experience about updating software.) (Or writing it.) (Or debugging it.)  ;-)

Since it has been, I will document what I finally got working for me, in case someone else runs into the same problem. 

Note that I am using Ubuntu 19.04, so all you Mac and Windows users gotta change over to what works on your platform.

It turns out I did have `libmysqlclient-dev` installed (in a couple of places, actually - more on that later), and the reason that they couldn't  be found was because I didn't have a `LD_LIBRARY_PATH` environment variable defined. So I had to do that... but what was "that", exactly?

First of all, here are some links that I found useful:

http://sphinxsearch.com/docs/sphinx3.html
Search for "libmysql" and you will see that you need the `libmysqlclient.so` driver so the indexer can connect to your MySQL database.

But there can be different versions of this driver (like I said, there was on my system) so how to resolve?

https://sphinxsearch.com/forum/view.html?id=15745
On this site, someone from "team sphinx" made the following comment:

> Sphinx currently just tries loading libmysqlclient.so (and libmariadb.so now) but does
*not* yet attempt to scan for all the different .so.18 or so.19 or so.20 etc versions.
The thought is starting to cross my mind though :)
>
NOTE: It still doesn't attempt to search for different version numbers.

So before setting your `LD_LIBRARY_PATH` you need to create a symlink called `libmysqlclient.so` (since that is the only thing Sphinx searches for) which points to the actual driver. 

In my `user/lib64` I had the following 3 files:
`libmysqlclient.so --> libmysqlclient.so.18 --> libmysqlclient.so.18.0.0` (actual program)

Since the correct symlink already existed, I added the following line to `~/.profile`:
`LD_LIBRARY_PATH="/usr/lib64:$LD_LIBRARY_PATH"`

Google says you need only run `sudo ldconfig` for the change to "take", but that didn't work for me; I had to actually log out and log back in before `echo $LD_LIBRARY_PATH` showed what I wanted.

Then I cd'd into my app directory and ran `bundle exec rake ts:index` and... wait for it... IT WORKED!!!

Then I noticed that the dates on my `libmysqlclient.so` files in `/usr/lib64` were May 2016, and that I had the following 2 files in `/usr/lib/x86_64-linux-gnu`, which were created in April 2019:
`libmysqlclient.so.20 --> libmysqlclient.s0.20.3.13`

Again, since Sphinx doesn't try load files with version numbers, I created the following in the same directory:
`libmysqlclient.so --> libmysqlclient.so.20`

Then I changed my `~/.profile` file to:
`LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"`

Then I logged out and logged back in and verified the new `LD_LIBRARY_PATH` setting. And cd'd into my app's directory, and... `bundle exec rake ts:index` still worked!

Hopefully this will save folks some of the hours it took me to finally get this to work.

Thanks for the great gem!

**Comment by KenBotwinick** [comment]
Hi All,

I'm having this issue on Mac when running indexer. searchd starts no problem.

I've set LD_LIBRARY_PATH to the location of my newly installed brew mysql-client: /usr/local/Cellar/mysql-client/8.0.33_1/lib/. The library is called libmysqlclient.21.dylib on Mac. The folder does have a libmysqlclient.dylib symlink to .21. Doesn't matter. I didn't know if Sphinx was hardcoded to .so instead of .dylib so I also created a symlink libmysqlclient.so to the same .21.

This is pretty frustrating. Would love to start experimenting with indexing today. Is there any debug so that indexer can just tell me exactly where it is looking for this file so I can just put a symlink there? Because it seems to ignore LD_LIBRARY_PATH on Mac.

Thanks for any help.

**Comment by KenBotwinick** [comment]
Wow. Already fixed it. :)

I needed to set DYLD_LIBRARY_PATH.

**Comment by atomical** [comment]
@KenBotwinick What exactly was your `DYLD_LIBRARY_PATH` set to?

**Comment by mecsu** [comment]
> Wow. Already fixed it. :)
> 
> I needed to set DYLD_LIBRARY_PATH.

Hi @KenBotwinick 

May I know how you fixed it? :)

Thanks

**Comment by KenBotwinick** [comment]
My DYLD_LIBRARY_PATH was:

export DYLD_LIBRARY_PATH=/usr/local/Cellar/mysql-client/8.0.33_1/lib

That worked on my old mac, but now I have a new Mac and I’m trying to use the built in Mamp path:

export DYLD_LIBRARY_PATH=/Applications/MAMP/Library/bin/mysql80/lib/

But that doesn’t work even though the files are there. And it seems the difference between my two mac is that my old one had SIP disabled. SIP seems to be breaking this:

https://wissel.net/blog/2022/01/maven-jna-macos-and-ld_library_path.html
