### ISSUE TITLE
Merging of Delta Indices Failed

### ISSUE THREAD

**Issue by pantajosef** [pat/thinking-sphinx#1145]
I use sphinxsearch version 2.2.11 and thinking-sphinx version 4.3.0. I've configured thinking_sphinx to use SQL-based Indices with a delta index. The deltas are processed with Delayed::Job.
Every night at 2:30am GTM+1, [clockwork](https://github.com/Rykian/clockwork/tree/v2.0.0) issues the Rake task 'ts:merge' to merge all the delta into their core indices. Lately however, the merges seem to fail due to the guard files (the indices being locked or something while being searched, I guess?). Then, Delayed::Job receives a `SystemExit` Error, and tries to process the merge-task later again.
The output of thinking-sphinx is the following:

```
The Sphinx merge_and_update command failed:
  Command: /usr/bin/indexer --config config/production.indexer.sphinx.conf --merge coreindex deltaindex --merge-dst-range sphinx_deleted 0 0
  Status:  1
  Output:  See above
There may be more information about the failure in /app/app/config/production.indexer.sphinx.conf.
```

I know, that the merge command is done in pairs (core index and delta index).
The error thrown from the last issued merge command that failed, which caused the entire rake task to fail is the following: 

```
ERROR: index 'deltaindex' is already locked; lock: failed to lock
/.../deltaindex.spl: Resource temporarily unavailable
```

After a bit of research and testing, it turns out that this issue is solved by adding the `--rotate` option to the merge command.

The same goes for the index command or the "ts:index" task (with INDEX_ONLY=1).

```
/usr/bin/indexer --config production.indexer.sphinx.conf (--all | coreindex deltaindex ...)
```

Without the `--rotate` command, the error saying that an index is already locked (see above), occurs very frequently.

I looked in the source code, and I recognized that there is no possibility to configure that the `--rotate` option should be added. I also believe, that this should be added per default since it does not do any harm (in the following, there is an excerpt from the [indexer command reference](http://sphinxsearch.com/docs/current/ref-indexer.html): 

```
--rotate is used for rotating indexes. Unless you have the situation where you can take the search function offline without troubling users, you will almost certainly need to keep search running whilst indexing new documents. --rotate creates a second index, parallel to the first (in the same place, simply including .new in the filenames). Once complete, indexer notifies searchd via sending the SIGHUP signal, and searchd will attempt to rename the indexes (renaming the existing ones to include .old and renaming the .new to replace them), and then start serving from the newer files. Depending on the setting of seamless_rotate, there may be a slight delay in being able to search the newer indexes. 
```

**Comment by pat** [comment]
Hi Joe, thanks for reporting this issue.

The rotate flag _should_ be being used - it's actually managed by Riddle (which does the heavy-lifting of Sphinx command line calls):
https://github.com/pat/riddle/blob/develop/lib/riddle/controller.rb#L31
https://github.com/pat/riddle/blob/develop/lib/riddle/controller.rb#L45

So, it seems there's something in your setup that's stopping Riddle/Thinking Sphinx from properly detecting if Sphinx is running. Can you tell me more about your hosting setup? Are you using Capistrano? And in particular, have you got Sphinx paths set up to be separate from specific releases? I'm wondering if the pid file might be getting lost between deploys…
https://freelancing-gods.com/thinking-sphinx/v4/deployment.html

**Comment by pantajosef** [comment]
Hi Pat!
Thanks a lot for your quick answer! I see. Though I thought of myself to have read your documentation thoroughly, I somehow seem to have missed the "Deployment" part of your docs.

I am not using Capistrano, but Dokku: thus, there is a web container in which the rails app is running, and a sphinx container in which searchd is running together with a worker processing all sphinx related jobs. We are using the `socket` option to connect to the sphinx container which works. However, the `indices_location` is definitively separate from specific releases. But neither the `binlog_path` nor the `pid_file` (which is set to being in `/tmp/searchd.pid`) nor the `configuration_file` are set to be separate from specific releases. So, I do believe, the pid file gets lost during deployments as you suggested. So, the first step is to set those correctly and mount them to the physical storage, right?

Since dokku is a docker-based mini heroku, I guess `flying-sphinx` should also be included, shouldn't it?

Right now, we had issues with setting up sphinx correctly. It would not start correctly and stuff. So we are using `supervisord` to manage the `searchd` as well as the worker processing sphinx related jobs. Also, we do not use zero-downtime-deploys as this also caused issues by having two instances running on the same port, which means that there is no searchd running for a couple of seconds.

**Comment by pat** [comment]
Don't use the `flying-sphinx` gem - that's only useful if you're using the Flying Sphinx add-on on Heroku (and thus aren't managing the daemon directly).

And yeah, if you can persist all the Sphinx files so they're not lost in deployments, that definitely sounds like the right place to start.

As for the slight downtime - I don't think that can be avoided, unfortunately - I can't think of any other way to work around the port conflict.

**Comment by pantajosef** [comment]
Alright, I will try this and post an update as soon as possible FYI.
Thanks a lot for your quick help!

**Comment by pantajosef** [comment]
I am here with an update: Persisting the pid_file or binlog files did not make any difference. Sadly, I could not narrow down the problem at all. Now it works again, which is why I will close this issue. Thanks a lot for your help, though!

**Comment by pat** [comment]
Glad to know it's working, but yeah, a bit frustrating that it's not clear why. Here's hoping the problem doesn't return 🤞
