### ISSUE TITLE
IndexJob generates 500 error

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1147]
Hi Pat,

We were calling this in a callback but it was generating an error (only on production): 

```rb
ThinkingSphinx::Deltas::IndexJob.new("location_delta").perform
```

Can you think of any idea why this would work but not the abovementioned code:

```rb
ThinkingSphinx::Deltas::SidekiqDelta::DeltaJob.perform_in(2.seconds, "location_core")
```

**Comment by pat** [comment]
I'm not sure… I don't suppose you've got the stacktrace for the error? :)

**Comment by atomical** [comment]
It looks like a race condition. Let me get back to you on that.
