### ISSUE TITLE
Is Manticore worth it?

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1149]
What's your opinion on Manticore? It's compatible with ThinkingSphinx, correct?

It doesn't seem like the performance is worth it. We're currently running Sphinx 2.3.2-id64-beta (4409612).

https://manticoresearch.com/2019/01/28/manticore-2-7-5-vs-sphinx-3-1-1/

**Comment by pat** [comment]
I'm not sure how performance has changed with Manticore in their 3.x releases, but yes, Thinking Sphinx supports Manticore as well - well, for the core functionality that Sphinx has as well. Manticore seems to be more active at the moment in terms of development, and they're adding additional features that TS doesn't take advantage of.

Sphinx is perhaps adding other things too, but - likely prompted by Manticore being a fork - it's gone closed source, so it's harder to get a sense of progress.

Right now: it may be worth trying both and seeing which performs better for your setup. In the future: if you see features in Manticore that you'd like TS to support, do let me know :) Same goes for any new Sphinx features too, of course!

**Comment by atomical** [comment]
Thanks Pat!
