### ISSUE TITLE
Delta column index?

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1151]
Would any performance be gained by adding an index on the delta column in each model?

**Comment by pat** [comment]
I would expect so, yes :)

**Comment by pat** [comment]
I've no idea why it wasn't in the docs… I had presumed it would be. Definitely a mistake on my part. But I've just added it in now.

**Comment by atomical** [comment]
Awesome! We have a few large tables and I'm curious to see the performance change. Would this change only effect the performance of the indexer (i.e. when the sidekiq worker processes the delta)?

**Comment by pat** [comment]
Yeah, I think it's just going to improve delta processing. The core index doesn't filter by the delta column, so I wouldn't expect any changes there, and I can't think of other situations where it might be used for SQL WHERE clauses.
