### ISSUE TITLE
Setting sql_mode for indexer

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1154]
Is there a way to set additional options, like sql_mode, for the indexer? Something like init_command with mysql2?

**Comment by atomical** [comment]
We solved it by using _set_property_ in the index definition.

```ruby
  set_property :sql_query_pre => ["SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"]
```

**Comment by pat** [comment]
This is the solution I would have suggested as well :) Glad to see you got it figured out.
