### ISSUE TITLE
add multiple "listen" instructions in the configuration file

### ISSUE THREAD

**Issue by deneuxa** [pat/thinking-sphinx#1159]
Hello,
for monitoring correctly our sphinx status, we would need to generate a sphinx configuration, with double "listen" instruction

listen                 = 127.0.0.1:9312
listen                 = 127.0.0.1:9313:mysql41

We can't find how to set-up our thinking_sphinx.yml to do so :/ 

It seems it isn't possible to add a "listen" instruction.
https://gist.github.com/pat/a7d73376dd657b4457092efc9e9c418a

Is it ?

**Comment by pat** [comment]
It's technically possible, though certainly not recommended - to get the settings you've listed, you'll need to specify both `mysql41` and `port`, with the latter being for the old binary protocol:

```
development:
  port: 9312
  mysql41: 9313
```

But I'm curious: what is using the old binary protocol for monitoring Sphinx?

**Comment by deneuxa** [comment]
We want to use the command "searchd --status", using CLI and not a specific script.
It seems the official documentation indicates that "searchd --statut" require this protocol :/

**Comment by pat** [comment]
As a potential replacement, it is possible to use the MySQL CLI tool to talk to Sphinx over the more modern SphinxQL protocol (you'll need to specify both port and host to ensure it doesn't default to a Unix socket instead): `mysql --port 9306 --host 127.0.0.1 -e 'SHOW STATUS;`

**Comment by pat** [comment]
This issue's been dormant for a while, so I'm going to close it just to keep things tidy - but if there's further questions around this topic, still feel free to comment here, and we can re-open if required :)
