### ISSUE TITLE
Unsupported filter type 6 (MVA) for acts-as-taggable-on

### ISSUE THREAD

**Issue by happychriss** [pat/thinking-sphinx#1162]
I am aware issue #1116 - but I am not able to solve the problem by changing type.
I am running thinking-sphinx (4.4.1) with index:

ThinkingSphinx::Index.define(:document, :with => :active_record) do
indexes comment, :as => :comment
indexes pages.content, :as => :page_content
**has taggings.tag_id, :type => :integer, :as => :tags**
has created_at, :sortable => true
end

Getting the following error message:
`index document_core: unsupported filter type '(filter-type-6)' on MVA column`

With SQL:

`SELECT * FROM document_core WHERE tags IN ('10') AND sphinx_deleted = 0 ORDER BY created_at desc, id DESC LIMIT 0, 30; SHOW META;`

My problem seems related to #1116, if I remove above qoutes '10' manually, it works.

I tried several combination in the index definition., but  thinking-sphinx keeps adding the quotes (regardless the "type" I am using) :-(

**Comment by pat** [comment]
Hi Christian - I think what might need to change is the search call you're running?

For some historical context: Sphinx used to support just integer-based attributes - ints, booleans, timestamps. And so Thinking Sphinx would automatically cast any string values provided for filters into integers. However, then Sphinx added support for string attributes, and Thinking Sphinx could no longer make assumptions about filter value types - and so stopped auto-casting.

This change was first made optional in v3.4.0, and then enforced in v4.0.0 - and it's particularly relevant with filter values provided via request params, which are strings by default.

Which is all to say: the tag id that you're filtering on - is it a string, or an integer? If it's an integer, then this definitely sounds like a bug, but if it's a string, then you'll need to call `to_i` on it to ensure it's the correct type for Thinking Sphinx.

**Comment by pat** [comment]
Oh… sorry, just saw your last point:

> regardless the "type" I am using

… so, sounds like a bug! I'll have a look into reproducing the issue.

**Comment by pat** [comment]
Investigating further, and I can't reproduce the issue… but, I think there's some confusion here about the typing. Given you're using SQL-backed indices (`:with => :active_record`), you don't need to worry about specifying the type for the attribute definition. What matters is using the appropriate types for the filters in the search call. e.g.

```ruby
Document.search "foo", :with => {:tags => [values_here_should_be_integers]}
```

**Comment by happychriss** [comment]
Pat, thank you! I was looking  into the wrong direction, changing the "tags" to integer with `{:tags => keyword_id.map!{|k| k.to_i}` solved my problem. 

Hope that's OK to say here:  I really appreciate the work you are doing, using Thinking Sphinx for a private project since 2012.

**Comment by pat** [comment]
Ah, great to know both the issue's fixed, and that Thinking Sphinx has been working well for you for so many years! :) I really appreciate hearing that.
