### ISSUE TITLE
Has one association

### ISSUE THREAD

**Issue by pinkal-bacancy** [pat/thinking-sphinx#1163]
I am doing indexing for Listing model. And listing model has one association, has_one location.
I wanted to send multiple location ids in index, then how I need to define it in index.
location_ids = [3,25,15,45,67]
I would like to search with this for listing model.
Can anyone suggest?

**Comment by pat** [comment]
Hi @pinkal-bacancy - you'll need to add an attribute with the location id to your index definition - probably along the lines of:

```ruby
has location.id, :as => :location_id
```

And then when you're searching you can specify multiple values, and it should return listings that match any of the locations:

```ruby
Listing.search :with => {:location_id => [3, 25, 15, 45, 67]}
```

**Comment by pinkal-bacancy** [comment]
Thank you for a quick response!
Yes, I used the same. But it doesn't give me the records based on these location ids.

D, [2020-04-24T14:50:17.365503 #6044] DEBUG -- :   Sphinx Query (1.6ms)  SELECT * FROM `listing_core`, `listing_delta` WHERE `community_id` = 1 AND `location_id` IN (3, 25, 11, 30, 33, 34, 35, 37, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 85, 89, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 115, 116, 117, 118, 119, 122, 123, 124, 125, 126, 127, 128, 129, 131, 132, 133, 135, 136, 137, 138, 140, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 161, 162, 167, 70, 83, 84, 86, 87, 88, 90, 91, 107, 108, 109, 110, 111, 112, 114, 156, 157, 166, 27, 31, 32, 52, 9, 10, 17, 163, 164, 165, 4, 5, 19, 20, 21, 160, 168, 169, 170, 120, 24, 121) AND `sphinx_deleted` = 0 ORDER BY `sort_date` DESC LIMIT 0, 10 OPTION field_weights=(title=10, category=8, description=3), max_query_time=1000
D, [2020-04-24T14:50:17.366363 #6044] DEBUG -- :   Sphinx  Found 129 results
D, [2020-04-24T14:50:17.377255 #6044] DEBUG -- :   Listing Load (9.4ms)  SELECT `listings`.* FROM `listings` WHERE `listings`.`id` IN (207, 206, 205, 184, 183, 179, 178, 174, 173, 171)
D, [2020-04-24T14:50:17.488634 #6044] DEBUG -- :   Person Load (3.4ms)  SELECT `people`.* FROM `people` WHERE `people`.`id` IN ('Zo32jxuMcrZ5UZExr0sMog', 'sBfz9IWTd6KdWz7vDJ_EmA')
D, [2020-04-24T14:50:17.521495 #6044] DEBUG -- :   ListingImage Load (23.0ms)  SELECT `listing_images`.* FROM `listing_images` WHERE (error IS NULL) AND `listing_images`.`listing_id` IN (171, 173, 174, 178, 179, 183, 184, 205, 206, 207) ORDER BY position
D, [2020-04-24T14:50:17.535922 #6044] DEBUG -- :   Testimonial Load (4.5ms)  SELECT `testimonials`.* FROM `testimonials` WHERE `testimonials`.`blocked` = 0 AND `testimonials`.`receiver_id` IN ('Zo32jxuMcrZ5UZExr0sMog', 'sBfz9IWTd6KdWz7vDJ_EmA') ORDER BY id DESC
D, [2020-04-24T14:50:17.544265 #6044] DEBUG -- :   HABTM_Categories Load (3.2ms)  SELECT `categories_listings`.* FROM `categories_listings` WHERE `categories_listings`.`listing_id` IN (171, 173, 174, 178, 179, 183, 184, 205, 206, 207)
D, [2020-04-24T14:50:17.554028 #6044] DEBUG -- :   Category Load (3.6ms)  SELECT `categories`.* FROM `categories` WHERE `categories`.`id` IN (4, 8, 2, 3, 1, 5, 6, 7, 9, 12, 11, 10)
D, [2020-04-24T14:50:17.560558 #6044] DEBUG -- :   Location Load (3.4ms)  SELECT `locations`.* FROM `locations` WHERE `locations`.`listing_id` IN (171, 173, 174, 178, 179, 183, 184, 205, 206, 207)
D, [2020-04-24T14:50:17.610158 #6044] DEBUG -- :   FavouriteListing Load (3.5ms)  SELECT `favourite_listings`.* FROM `favourite_listings` WHERE `favourite_listings`.`listing_id` IN (171, 173, 174, 178, 179, 183, 184, 205, 206, 207)

**Comment by pinkal-bacancy** [comment]
Is there any way to display listing based on the order of the location ID? For exampple if 3 is the first element of location id then, it should give the listing of that location first.

**Comment by pat** [comment]
Yes, [you can sort by any attribute](https://freelancing-gods.com/thinking-sphinx/v4/searching.html#sorting) - just use the `:order` option in your search call. To expand on the previous example:

```ruby
Listing.search(
  :with => {:location_id => [3, 25, 15, 45, 67]},
  :order => :location_id
)
```

**Comment by pinkal-bacancy** [comment]
It is working for only one record of location. The association is, the listing has_on location. 
If I am sending an array of location id then it is not giving record in order by location ids.

**Comment by pinkal-bacancy** [comment]
I would like to display listings records in following manner, 
if I have array of location_id = [3,25,15,45]
then it should give the listing of location 3 first and second is of 25's listing and so on....

**Comment by pat** [comment]
Ah, I'm afraid that's not possible with Sphinx or Thinking Sphinx (or ActiveRecord, I believe). You'll need to do that sorting yourself once you have the results.

**Comment by pinkal-bacancy** [comment]
Yeah... you are right. But after applying sphinx search, it's converting records based on pagination. I want listing with id 14 into the result, but it is giving me [205, 207, 206, 205, 203] like this due to pagination and ordering. So I am finding if there is any way to do custom ordering with sphinx or not. So i can get the listing which I need.

**Comment by pat** [comment]
I think you might need to conduct the search with each single location separately, to ensure you're paginating through one entirely before moving on to the next.

**Comment by pat** [comment]
You _could_ change the pagination page size to something very large, but that's only useful if you're always sure that you'll never be over that limit.

**Comment by pinkal-bacancy** [comment]
Oops, I can't define size statically.

**Comment by pinkal-bacancy** [comment]
Issue resolved.
I removed pagination from sphinx search and give dynamic limit. And apply pagination on the result of sphinx search. 
And this works for me.

**Comment by pat** [comment]
Good to know you've found a way through :)
