### ISSUE TITLE
sql_attr_timestamp was removed in Sphinx 3.3.1

### ISSUE THREAD

**Issue by JasonBarnabe** [pat/thinking-sphinx#1183]
Trying to upgrade to Sphinx 3.3.1. Starting daemon gives:

```
Sphinx 3.3.1 (commit b72d67b)
Copyright (c) 2001-2020, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/www/greasyfork/shared/config/production.sphinx.conf'...
ERROR: key 'sql_attr_timestamp' was permanently removed (see documentation for details) in /www/greasyfork/shared/config/production.sphinx.conf line 39 col 21.
FATAL: failed to parse config file '/www/greasyfork/shared/config/production.sphinx.conf'
shutdown complete
```

**Comment by pat** [comment]
This sounded familiar, and then I realised I had PR #1177 ready to go with the required changes 😅 I've just merged it into the `develop` branch - and if CI's all good (it takes a while), I'll release 5.1.0 tomorrow with the changes.

If you want to give it a spin straight from the repo in the meantime, you're very welcome to! I'd certainly appreciate the confirmation that it works well for your app :)

**Comment by JasonBarnabe** [comment]
I already went ahead and used 3.2.1 so won't be able to confirm it, but good it'll be fixed for the next round of upgrades!

**Comment by pat** [comment]
Fair enough :)
