### ISSUE TITLE
Rails 6.1.4 throws NameError: uninitialized constant ThinkingSphinx::ActiveRecord when running tasks

### ISSUE THREAD

**Issue by jasongorst** [pat/thinking-sphinx#1199]
Rails 6.1.4 with thinking-sphinx 5.2.0 throws a NameError when running tasks.

I created a bare application having just a single model having 2 attributes and an index file, and got the same error on ts:rebuild (or ts:clear or whatever).

**Comment by pat** [comment]
Thanks @jasongorst for reporting this - I've put together a fix that works in my test app, but perhaps you want to bundle from the `develop` branch to confirm it's fine by you? @jdelStrother would appreciate your eyes over this too if you have a chance, given it's an evolution of your improvements :) (See ea35340e3cd0a6cbbc4acb86a366cf1ee83ac961)

**Comment by jasongorst** [comment]
Thanks for the quick fix, @pat!

That seems to have done the trick. Works fine in my test app.

Jason

**Comment by pat** [comment]
Thanks for that confirmation Jason - I've just published v5.2.1 with the fix :)

**Comment by jdelStrother** [comment]
> Thanks @jasongorst for reporting this - I've put together a fix that works in my test app, but perhaps you want to bundle from the `develop` branch to confirm it's fine by you? @jdelStrother would appreciate your eyes over this too if you have a chance, given it's an evolution of your improvements :) (See [ea35340](https://github.com/pat/thinking-sphinx/commit/ea35340e3cd0a6cbbc4acb86a366cf1ee83ac961))


Yeah, think this is OK. It's a shame that it forces ActiveRecord to load for unrelated things like assets:precompile, but in practice it probably doesn't have much noticeable impact, and I don't see a clean alternative. 😕

**Comment by pat** [comment]
Yeah, it's not as neat as your solution, but I guess this is what we're stuck with. Thanks for the confirmation Jonathan :)
