### ISSUE TITLE
Disabling in Development

### ISSUE THREAD

**Issue by DaAwesomeP** [pat/thinking-sphinx#1212]
Hello,

Is it possible to disable/ignore errors for Thinksing Sphinx when in a certain Rails env? I'm trying to add an option to not have Sphinx installed in the development environment. Specifically seeing `Riddle::CommandFailedError: Sphinx command failed to execute`.

Thanks!

**Comment by pat** [comment]
There's no global option for this. But I'm curious: at what points are you seeing these errors? Is it via real-time/delta callbacks?

**Comment by DaAwesomeP** [comment]
Yeah, callbacks when creating or modifying a model that gets indexed (delta is enabled). If I disabled the index I guess that would do it.

**Comment by pat** [comment]
If you're using real-time indices (as opposed to deltas) you could add `real_time_callbacks: false` for the development environment in `config/thinking_sphinx.yml`, which should do the trick.

There's not an equivalent setting for deltas though.

**Comment by pat** [comment]
Ah, you've said you're using deltas! Sorry… you could change it that deltas aren't enabled in development, in each index file. e.g.

```
ThinkingSphinx::Index.define :article, :with => :active_record, :delta => !Rails.env.development? do
```

**Comment by DaAwesomeP** [comment]
Yup, that did the trick! Thanks!
