### ISSUE TITLE
Tag 5.4.0 not visible

### ISSUE THREAD

**Issue by kalsan** [pat/thinking-sphinx#1218]
Hi Pat!

Just a quick note to inform you that version 5.4.0 does not show up on the GitHub pat/thinking-sphinx Tags overview.

Great work with Rails 7 support BTW!

Cheers
Kalsan

**Comment by pat** [comment]
Ah, thanks for pointing that out! Just published it :)
https://github.com/pat/thinking-sphinx/releases/tag/v5.4.0
