### ISSUE TITLE
Socket Permissions

### ISSUE THREAD

**Issue by DaAwesomeP** [pat/thinking-sphinx#1223]
Hello!

I currently have Sphinx listen on a socket with `socket: /path/to/my/socket.sock`. However, I have noticed that this socket has permissions of `777`, which means it is readable/writable by anyone. How can I limit the permissions of the socket?

Thanks!

**Comment by pat** [comment]
Hi Perry - unfortunately, it doesn't seem that Sphinx has a configuration option for this (and it's not something that Thinking Sphinx can control directly). I guess you could try modifying the permissions directly with `chmod` and see if that has an impact?

**Comment by DaAwesomeP** [comment]
Ah, darn! I'll open an issue there. Another way I thought about would be to use a SystemD socket activation. I'll close this since both of those are more of issues with Sphinx. I'll report back what I find. Thanks for taking a look!
