### ISSUE TITLE
MariaDB throws error string not caught by ThinkingSphinx::SphinxError.new_from_mysql

### ISSUE THREAD

**Issue by fabrizioq** [pat/thinking-sphinx#1227]
Some time after upgrading some packages on a linux machine, our rails test suite started to fail due to connection errors to Sphinx. 

The sphinx callback triggered after destroying a mode were not finding a running sphinx demon. Indeed I run the suite without starting the sphinx demon. However these fails were new to me. (In fact, I had never thought about the sphinx implications about destroying the model!)

Strangely, the same tests did not fail on a mac machine -- with mysql installed.

After some time I realized that MariaDB had changed its connection error message by removing "MySQL": "Can't connect to server on '%-.64s' (%d)"

https://github.com/mariadb-corporation/mariadb-connector-c/commit/a08fd79afd07a75687f6186caf3d6e3f5724764f#diff-8e895496dc9b58b3a7076d64c920b6e739a16b6be753cd24e31ce149b2feb7f3L88
  
This message is not caught by the case statement inside ThinkingSphinx::SphinxError.new_from_mysql.

```ruby
class ThinkingSphinx::SphinxError < StandardError
  def self.new_from_mysql(error)
    case error.message


    when /Can't connect to MySQL server/,
      /Communications link failure/,
      /Lost connection to MySQL server/
      replacement = ThinkingSphinx::ConnectionError.new(
        "Error connecting to Sphinx via the MySQL protocol. #{error.message}"
      )
      end
   end
end
```

I tried changing the case statement and my tests again started to pass (or to fail silently :).

I hope this helps someone. Thanks Pat for your incredible work.

**Comment by pat** [comment]
It took me half a year 🤦🏻‍♂️ but finally published a new release (v5.5.0) with this fix. Sorry for the delay!
