### ISSUE TITLE
how to discover searchd from manticore running inside docker container

### ISSUE THREAD

**Issue by 34code** [pat/thinking-sphinx#1243]
It appears `ts:rebuild` and `ts:index` expects `searchd` in path. What if it is not available in the path and instead running inside a docker container?

I'm running an arch linux based distro so cannot install manticore natively on the system, hence the docker route..

**Comment by pat** [comment]
I'm not super familiar with Docker, but the best solution here is to have a copy of your app within the container as well, and then invoke all the rake tasks within the container, rather than talking to the container externally. Is this possible in your case?

**Comment by 34code** [comment]
yes I can copy my rails code into the container, thanks for the tip
