### ISSUE TITLE
Equivalent of `#none` from ActiveRecord?

### ISSUE THREAD

**Issue by pdany1116** [pat/thinking-sphinx#1248]
Hi, I want to always return an empty result set for a search. Active Record has `#none` method that does this (https://apidock.com/rails/v4.0.2/ActiveRecord/QueryMethods/none).

Is there any way to achieve this with Thinking Sphinx?

Thanks!

**Comment by pat** [comment]
It only took me a year, but: I've just released v5.6.0 which has `search_none` available on models, as well as simply `none` that can be called on an existing search request, as well as via `ThinkingSphinx.none`. #1e8a666e
