### ISSUE TITLE
SystemExit

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1260]
Hi Pat,

I'm seeing a `SystemExit: exit` error when I try to run an index job:

```
    ThinkingSphinx::Deltas::IndexJob.new("tickets_core").perform
```

This should work? I tried with deltas too.

**Comment by pat** [comment]
Belated response, but: yes despite the class hierarchy, I would expect this to work with core indices as well as delta indices.

I don't suppose you've got a stacktrace of where the exception happens (if it's still happening)? Also, perhaps not what you were actually running, but the above example has `tickets` (plural), and TS uses singular names by default.

**Comment by atomical** [comment]
It's not still happening but if we see it again I'll reopen the issue. Thanks!
