### ISSUE TITLE
Rails 7.1 LogSubscriber color() deprecation

### ISSUE THREAD

**Issue by rpheath** [pat/thinking-sphinx#1261]
In Rails 7.1 the `color(...)` method no longer accepts `true` as the third argument for "bold". Instead, you have to pass `bold: true`.

* https://api.rubyonrails.org/classes/ActiveSupport/LogSubscriber.html#method-i-color

The `LogSubscriber` in thinking-sphinx has log output using the deprecated format, which results in a billion deprecation messages in application logs.

Is it possible to make an update to address this? Thanks!

**Comment by rpheath** [comment]
Oh! I see that PR #1252 addresses this. Any chance it will be merged/released?

**Comment by pat** [comment]
Closing this as #1252 is merged (and hopefully will be released shortly!)
