### ISSUE TITLE
Not indexing in test mode.

### ISSUE THREAD

**Issue by antekpiechnik** [pat/thinking-sphinx#154]
Hey,

So I've installed thinkingsphinx, and it's working for me perfectly in development. However, as I tried writing and running tests, I realized I'm having huge problems with getting it to collect docs.

My index in the _Article_ model:

```
  define_index do
    indexes :title
    indexes :excerpt
    indexes :body
    where "articles.visible = 1"
  end
```

I'm using this in my Gemfile:

```
gem 'thinking-sphinx', '2.0.0', :require => 'thinking_sphinx'
```

So I run

```
ThinkingSphinx::Test.init
```

in my _test_helper.rb_ file and then my test looks like this

```
def setup
  super
  ThinkingSphinx::Test.start
end

def teardown
  ThinkingSphinx::Test.stop
  super
end
```

And when I run a test, it fails, and debugger provides me with the following info:

```
article_1 = Article.make(:title => "john is a god")
article_2 = Article.make(:excerpt => "john is not a god")
ThinkingSphinx::Test.index
using config file '/Users/tph/Work/gup-mag/config/test.sphinx.conf'...
indexing index 'article_core'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.006 sec, 0 bytes/sec, 0.00 docs/sec
distributed index 'article' can not be directly indexed; skipping.
total 3 writes, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
rotating indices: succesfully sent SIGHUP to searchd (pid=4563).

ThinkingSphinx.search('john')
=> []
```

Any ideas on why this is not working? Did I forget something ?

**Comment by harshad26** [comment]
Any solution found? @antekpiechnik

**Comment by pat** [comment]
@harshad26: this ticket's pretty old - indeed, it's referencing TS v2, and the v3 releases are _much_ different. If you're having problems with TS tests, perhaps it's worth opening a new ticket :)
