### ISSUE TITLE
support real-time indexing

### ISSUE THREAD

**Issue by ghost** [pat/thinking-sphinx#186]
Sphinx made rea-time available when they released Sphinx 1.10-beta. It would be great if Thinking-Sphinx supported it.

**Comment by som4ik** [comment]
i do have something similar 

 rake ts:configure

Generating configuration to /home/somar/news_blog/config/development.sphinx.conf
rake aborted!
Unknown attribute type ''

do any one have an idea how to fix it 
my post_index.rb is :
kingship::Index.define :post, :with => :real_time do
   indexes title, :sortable => true
   indexes body, cached_tag_list
    indexes user.id,       :as => :user,     :sortable => true
    indexes category.name,   :as => :category, :sortable => true
  	has confirm, :type => :integer, :multi => false
  	has created_at

  
end
----- 
if i put has created_at , :type => :datetime i got undifine :(

**Comment by pat** [comment]
Try `timestamp` instead:

```ruby
has created_at, :type => :timestamp`
```

**Comment by som4ik** [comment]
@pat  Thanks It works like Rocket !!!!
