### ISSUE TITLE
String Attributes, TS3

### ISSUE THREAD

**Issue by barkerja** [pat/thinking-sphinx#422]
On the edge branch, it looks like in the configuration file that is generated, attributes that are strings are no longer CRC'ed. Currently, there's no way to use attributes that are of the string type (at least that I'm aware of).

**Comment by mjsommer** [comment]
Pat, above you mention "direct your search against all the relevant fields using the following syntax: @(name,description,location) foo".

Can you please give an example, of what you mean by:

    @(name,description,location) foo

**Comment by pat** [comment]
You'd use that syntax in your query string, specifying the field names you want the search to cover (in this case, name, description, and location) within the parentheses, and then the query itself (foo) after.

```ruby
Model.search "@(name,description,location) foo"
```

Does that help?

**Comment by mjsommer** [comment]
Nice, is this the same functionality as the conditions option? 

Martin

--
Sent from my G4 phone.

**Comment by pat** [comment]
That's correct - the `:conditions` option is just a shortcut for simple field-to-query pairings.

**Comment by mjsommer** [comment]
Thanks!

Martin

--
Sent from my G4 phone.
