### ISSUE TITLE
Using blank password for postgres

### ISSUE THREAD

**Issue by lunks** [pat/thinking-sphinx#442]
In our company the database.yml is [the same for every project](https://github.com/Helabs/rails-template/blob/master/files/config/database.yml), and I'd like to keep it this way.

I'm  installing thinking-sphinx on a Rails 3.0.x project (which is currently tied to thinking-sphinx v2) and I'd like to keep my database.yml as the same. but I'm receiving `fe_sendauth: no password supplied` whenever I run `rake ts:index`

Can I somehow keep my database.yml the way it is and make thinking-sphinx work?

**Comment by som4ik** [comment]
@pat  i had the same problem with connection sphinx to my postgres ( even i leave sql_pas empty )!
i changed pg_hba.conf form this: 
```
# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```
to this 
```
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32           trust
# IPv6 local connections:
host    all             all             ::1/128                  trust
```
and restart the postgres service. and its worked perfectly
