### ISSUE TITLE
ts only uses ranges, not greater than/less than symbols

### ISSUE THREAD

**Issue by wedy** [pat/thinking-sphinx#584]
Hi,
ive been trying to do 'less than' on sphinx scope, and no luck

{code}
sphinx_scope(:sphinx_published) {
   {:where => ["published_at <= ?, Time.now"] }
}
{code}

can someone please confirm, ts doesnt support these symbols, only using range

it works if i do with it using range (below)

{code}
sphinx_scope(:sphinx_published) {
     {:conditions =>  {:published_at => 200.years.ago..Time.now}}
}
{code}

thank you

**Comment by ngan** [comment]
Hey @pat, just wondering if this was by design, or you just haven't gotten around to implementing it? I'd love to help out if it's the latter case.  Also, I noticed Riddle's Query::Select has an `OR`.  I thought SphinxQL doesn't support `OR` yet...?
```
175   def exclusive_filter_comparison_and_value(attribute, value)
176     case value
177     when Array
178       if !value.flatten.empty?
179         "#{escape_column(attribute)} NOT IN (#{value.collect { |val| filter_value(val) }.join(', ')})"
180       end
181     when Range
182       "#{escape_column(attribute)} < #{filter_value(value.first)} OR #{attribute} > #{filter_value(value.last)}"
183     else
184       "#{escape_column(attribute)} <> #{filter_value(value)}"
185     end
186   end
```

I'm def seeing an error right now when I use `without: 0...4`.  I'm on sphinx 2.2.8.

**Comment by pat** [comment]
Sphinx's docs say it still doesn't support OR yet, which is annoying. I guess `without` and a range isn't going to work for the moment - but if you can think of a way to rejig the logic to avoid the OR, I'm open to patches :)

**Comment by pat** [comment]
As for greater/less-than, I'd be open to seeing an implementation of `:with`/`:without`/etc accepting arrays of SphinxQL to sanitise (and perhaps it's possible to borrow ActiveRecord's `sanitize_sql` method for this purpose).
