### ISSUE TITLE
Index when child model is saved.

### ISSUE THREAD

**Issue by vicovictor** [pat/thinking-sphinx#595]
Using Rails 3.2, Riddle 1.5.7, Thinking Sphinx 3.0.4. Below is my model association:

```
# country.rb
class Country < ActiveRecord::Base
  has_many :states
  has_many :shops, :through => :states
end

# state.rb, with country_id
class State < ActiveRecord::Base
  belongs_to :country
  has_many :state_shops
  has_many :shops, :through => :state_shops
end

# state_shop.rb, with state_id, shop_id
class StateShop < ActiveRecord::Base
  belongs_to :state
  belongs_to :shop
end

# shop.rb
class Shop < ActiveRecord::Base    
end
```

I put `after_save ThinkingSphinx::RealTime.callback_for(:country)` in `country.rb` which works fine. When a new `state_shop` is created/destroyed, I want TS to index the `shop` that is wrapped in it. I tried to play around with the `after_save` above and associations, but I couldn't get TS to update the index. How should I make it work?

Noob suggestion: initially I thought by touching the `country` model, it would get the new changes indexed, but it didn't. Do you think this is a good suggestion - as long as the indexed model is touch, then it will be reindexed?

**Comment by atomical** [comment]
Hi Pat, 

What would be the solution for deltas?

**Comment by pat** [comment]
@atomical you'll probably want a callback that sets the delta flag to true for the parent object and then saves it (in a way that would fire its own callbacks):
http://freelancing-gods.com/thinking-sphinx/deltas.html#deltas-and-associations

**Comment by atomical** [comment]
Sorry about not creating a separate issue for this. In hindsight I should have done that.

I seem to recall that Sphinx checks attributes to see if they are changed. Is that correct? If I set delta: true and then save the parent object will it update a reference to another table if no other AR attributes have been changed:

```
 indexes "date(tracking_numbers.ship_date)", as: :ship_date_txt, sortable: true
```

**Comment by pat** [comment]
That callback you've highlighted is for updating attribute values directly in Sphinx. For deltas, however, it only checks `changed?` rather than any specific attributes - so, setting delta to true will be enough to prompt a delta update.

I think in TS v2 the behaviour was more what you were thinking (with attribute/field value checks happening), but that's relatively intensive and rarely worth it.

**Comment by atomical** [comment]
I got it working. Thanks.
