### ISSUE TITLE
postgres:  integer out of range

### ISSUE THREAD

**Issue by igorbernstein** [pat/thinking-sphinx#610]
I think I found a regression related to: #97 

When using deltas & rails fixtures with postgresql I get the error: "ERROR: index 'catalog_edition_core': sql_range_query: ERROR:  integer out of range"

I tracked the problem down to my sphinx.conf:
sql_query = SELECT "catalog_editions"."id" \* 4 + 0 AS "id".....

updating the sql_query to
 sql_query = SELECT "catalog_editions"."id"::bigint \* 4 + 0 AS "id".....

fixes the issue.  My temporary workaround is to monkey patch thinking sphinx:

``` ruby
ThinkingSphinx::ActiveRecord::SQLBuilder.class_eval do
  def document_id
    quoted_alias = quote_column source.primary_key
    "#{quoted_primary_key}::bigint * #{config.indices.count} + #{source.offset} AS #{quoted_alias}"
  end
end
```

which obviously breaks mysql.

**Comment by Envek** [comment]
I've seen such an error today when someone inserted `20014-12-25` in indexed date field :bomb:

**Comment by pat** [comment]
@Envek you may want to set `64bit_timestamps` to true for each environment in `config/thinking_sphinx.yml` - and/or have some validation on dates to avoid those massive values ;)
