### ISSUE TITLE
Sphinx crashing when delta indexed in parallel randomly

### ISSUE THREAD

**Issue by AnandChronus** [pat/thinking-sphinx#612]
Sphinx is crashing and the details are given below.

Scenario:
1. A hourly cron runs for indexing (does ts:in)
[Question here: Does ts:in need to run core index only or both core and delta indexes?]
2. 'searchd' process continuously run
3. delta indexing is done by delayed jobs continuously, example searchd log follows (just to get idea the frequency of operation)
---searchd log snip--
[Tue Sep 17 22:16:46.113 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:16:46.115 2013] [11673] rotating index 'user_delta': started
[Tue Sep 17 22:16:46.117 2013] [11673] rotating index 'user_delta': success
[Tue Sep 17 22:16:46.118 2013] [11673] rotating index: all indexes done
[Tue Sep 17 22:17:07.329 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:17:07.368 2013] [11673] rotating index 'user_delta': started
[Tue Sep 17 22:17:07.371 2013] [11673] rotating index 'user_delta': success
[Tue Sep 17 22:17:07.371 2013] [11673] rotating index: all indexes done
[Tue Sep 17 22:17:26.890 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:17:26.952 2013] [11673] rotating index 'user_delta': started
[Tue Sep 17 22:17:26.954 2013] [11673] rotating index 'user_delta': success
[Tue Sep 17 22:17:26.955 2013] [11673] rotating index: all indexes done
[Tue Sep 17 22:17:29.661 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:17:29.673 2013] [11673] rotating index 'article_delta': started
[Tue Sep 17 22:17:29.675 2013] [11673] rotating index 'article_delta': success
[Tue Sep 17 22:17:29.675 2013] [11673] rotating index: all indexes done
[Tue Sep 17 22:17:42.458 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:17:42.474 2013] [11673] rotating index 'group_delta': started
[Tue Sep 17 22:17:42.476 2013] [11673] rotating index 'group_delta': success
[Tue Sep 17 22:17:42.476 2013] [11673] rotating index: all indexes done
---searchd log snip--

Note:
The indexing was running by hourly cron was running at the same instant when the crash happened. But we cannot deduce that this concurrent operation causes the crash because this cron runs hourly but the searchd doesnt crash every hour. It happens rarely.

---cron log snip--
indexing index 'user_core'...
collected 51623 docs, 16.8 MB
collected 22354959 attr values
sorted 44.7 Mvalues, 100.0% done
sorted 15.9 Mhits, 100.0% done
total 51623 docs, 16776796 bytes
total 190.955 sec, 87856 bytes/sec, 270.34 docs/sec
indexing index 'user_delta'...
FATAL: failed to lock ../../sphinx_index/env/user_delta.spl: Resource temporarily unavailable, will not index. Try --rotate option.
---cron log snip--

Crashed searchd log:

[Tue Sep 17 22:18:02.196 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:18:02.221 2013] [11673] rotating index 'user_delta': started
[Tue Sep 17 22:18:02.224 2013] [11673] rotating index 'user_delta': success
[Tue Sep 17 22:18:02.225 2013] [11673] rotating index: all indexes done
[Tue Sep 17 22:18:19.417 2013] [11673] caught SIGHUP (seamless=1, in queue=1)
------- FATAL: CRASH DUMP -------
[Tue Sep 17 22:18:19.417 2013] [11673]

--- crashed SphinxQL request dump ---

--- request dump end ---
Sphinx 2.0.8-id64-release (r3831)
Handling signal 11
-------------- backtrace begins here ---------------
Program compiled with gcc 4.4.3
Host OS is Linux ip-192-168-25-222 2.6.32-342-ec2 #43-Ubuntu SMP Wed Jan 4 18:22:42 UTC 2012 x86_64 GNU/Linux
Stack bottom = 0x7fff626e563f, thread stack size = 0x10000
begin of manual backtrace:
Something wrong with thread stack, backtrace may be incorrect (fp=7fff626e563f)
Stack looks OK, attempting backtrace.
0
begin of system backtrace:
begin of system symbols:
/usr/local/bin/searchd(_Z12sphBacktraceib+0x89)[0x5a81a9]
/usr/local/bin/searchd(_ZN16SphCrashLogger_c11HandleCrashEi+0x196)[0x46f036]
/lib/libpthread.so.0(+0xf8f0)[0x7f50ec2d68f0]
/usr/local/bin/searchd(_Z19ReloadIndexSettingsR16CSphConfigParser+0x130)[0x493a20]
/usr/local/bin/searchd(_Z11CheckRotatev+0x95)[0x494555]
/usr/local/bin/searchd(_Z8TickHeadP22CSphProcessSharedMutex+0x75)[0x4af8a5]
/usr/local/bin/searchd(_Z11ServiceMainiPPc+0x3175)[0x4b3015]
/usr/local/bin/searchd(main+0x52)[0x4b34a2]
/lib/libc.so.6(__libc_start_main+0xfd)[0x7f50eb7b1c4d]
/usr/local/bin/searchd[0x46aff9]
Backtrace looks OK. Now you have to do following steps:
1. Run the command over the crashed binary (for example, 'indexer'):
    nm -n indexer > indexer.sym
2. Attach the binary, generated .sym and the text of backtrace (see above) to the bug report.

Also you can read the section about resolving backtraces in the documentation.
-------------- backtrace ends here ---------------
--- 8 active threads ---
thd 0, proto sphinxql, state net_read, command update
thd 1, proto sphinxql, state net_read, command update
thd 2, proto sphinxql, state net_read, command show_meta
thd 3, proto sphinxql, state net_read, command show_meta
thd 4, proto sphinxql, state net_read, command show_meta
thd 5, proto sphinxql, state net_read, command show_meta
thd 6, proto sphinxql, state net_read, command show_meta
thd 7, proto sphinxql, state net_read, command show_meta
------- CRASH DUMP END -------
[Tue Sep 17 22:18:19.485 2013] [11672] Child process 11673 has been finished by CRASH_EXIT (exit code 2), will be restarted
[Tue Sep 17 22:18:19.486 2013] [11672] Child process 24658 has been forked
[Tue Sep 17 22:18:19.486 2013] [24658] Reloading the config
[Tue Sep 17 22:18:19.488 2013] [24658] Reconfigure the daemon
[Tue Sep 17 22:18:19.488 2013] [24658] FATAL: 'searchd' config section not found in '/mnt/app/releases/20130917094849/config/env.sphinx.conf'
[Tue Sep 17 22:18:19.489 2013] [11672] Child process 24658 has been finished, exit code 1. Watchdog finishes also. Good bye!
[Tue Sep 17 22:20:15.539 2013] [24958] Child process 24959 has been forked
[Tue Sep 17 22:20:15.540 2013] [24959] listening on 192.168.25.222:9312
[Tue Sep 17 22:20:15.824 2013] [24959] WARNING: index 'user_core': lock: failed to lock ../../sphinx_index/env/user_core.spl: Resource temporarily unavailable; NOT SERVING
[Tue Sep 17 22:20:15.827 2013] [24959] rotating index 'user_delta': success
[Tue Sep 17 22:20:15.837 2013] [24959] binlog: replaying log /mnt/app/releases/20130917094849/tmp/binlog/env/binlog.001
[Tue Sep 17 22:20:15.837 2013] [24959] WARNING: binlog: update: unexpected tid (index=group_core, indextid=0, logtid=1418, pos=44)
[Tue Sep 17 22:20:15.837 2013] [24959] binlog: index group_core: recovered from tid 0 to tid 1669
[Tue Sep 17 22:20:15.837 2013] [24959] binlog: replay stats: 0 rows in 0 commits; 252 updates; 1 indexes
[Tue Sep 17 22:20:15.837 2013] [24959] binlog: finished replaying /mnt/app/releases/20130917094849/tmp/binlog/env/binlog.001; 0.0 MB in 0.000 sec
[Tue Sep 17 22:20:15.837 2013] [24959] binlog: finished replaying total 1 in 0.000 sec
[Tue Sep 17 22:20:15.838 2013] [24959] accepting connections
[Tue Sep 17 22:20:24.265 2013] [24959] caught SIGHUP (seamless=1, in queue=1)
[Tue Sep 17 22:20:24.287 2013] [24959] rotating index 'group_delta': started
[Tue Sep 17 22:20:24.305 2013] [24959] rotating index 'group_delta': success
[Tue Sep 17 22:20:24.305 2013] [24959] rotating index: all indexes done

**Comment by pahnin** [comment]
@pat is there any chance that delta indexes might be lock the .spl file? I'm trying to do a full index, I can see that deltas are running from the resque dashboard(resque worker is handling deltas), I'm getting the error ```FATAL: failed to lock /home/deploy/sphinx/product_delta.spl: Resource temporarily unavailable, will not index. Try --rotate option.``` repeatedly

**Comment by deneuxa** [comment]
@pat same problem here
@pahnin did you find a solution ?

**Comment by pat** [comment]
Hi Alex - given a lot of the discussion in this issue is quite old, can you let us know which versions of Sphinx, Thinking Sphinx and Rails you're using, and what approach you're using for delta indices (default, Sidekiq, Resque, DJ or something else?)

And are you seeing Sphinx actually crash? Or are the symptoms of the problem different?

**Comment by deneuxa** [comment]
Hello @pat ,
I'm using Sphinx 2.3.1-id64-beta, thinking-sphinx 3.1.0, delayed job and rails 4.1.8.

The problem occurs when a delta-job is run when the task ts:index is still running.

It's not the job that fails but the indexing task itself.

The main issue is that when this problem occur, the main-index remains empty... so only the results of the delta-index are displayed... until a new index could be run successfully.

I tried to update to thinking-sphinx 3.2.0 and didnt succeed to reproduce yet.
Maybe it solved the issue !

**Comment by pat** [comment]
Keep us posted if it crops up again, but I'm hoping something somewhere between 3.1.0 and 3.2.0 sorted it out! :)
