### ISSUE TITLE
sh: 1: indexer: not found

### ISSUE THREAD

**Issue by TheStranjer** [pat/thinking-sphinx#623]
I try rake "ts:index" and "RAILS_ENV=production rake ts:index."

I do not get any changes when I try SPHINX_VERSION=2.0.6 or INDEX_ONLY=true or both.

What do?

**Comment by bipashant** [comment]
This is because your system  doesn't have installed sphinx. 
If you're on Linux try this

`sudo apt-get install sphinxsearch`

**Comment by faisalrazap** [comment]
Sphinx is not installed on your system.
For Mac, following command is used with mysql:

`brew install sphinx --mysql`
