### ISSUE TITLE
Duplicate sections in test environment configuration file

### ISSUE THREAD

**Issue by beatrichartz** [pat/thinking-sphinx#764]
Regarding #523  

I had the same error, it occurs when the index files are preloaded - therefore executed before `ThinkingSphinx::Test.start` is called. Hence the indices are already present in `ThinkingSphinx::Configuration.instance.indices` when `ThinkingSphinx::Configuration#render_to_file` is called in `ThinkingSphinx::Test#start`, which in turn evaluates `ThinkingSphinx::Configuration::ConsistentIds#sources`, which loads eachs index source a second time.

The index file should not have been preloaded in my case in the first place, so I fixed it by not preloading the index file.

Since this results in relatively cryptic behaviour in test environments exclusively, maybe you want to add an entry to the FAQ. To prevent this in the library would most likely be overkill since there is hardly a usecase for preloading index files.

**Comment by eduardoj** [comment]
This issue can be reproduced with Rails 5, after ed37e9e was applied.

The files that create the indexes can be found here: https://github.com/openSUSE/open-build-service/tree/master/src/api/app/indices/

An example of the error can be found in the CircleCI tests run here: https://github.com/openSUSE/open-build-service/pull/7822

**Comment by pat** [comment]
Just released v4.3.2 with @eduardoj's fix for the issue in Rails 5 :)
