### ISSUE TITLE
Doc: thinking_sphinx.yml example / description

### ISSUE THREAD

**Issue by klippx** [pat/thinking-sphinx#812]
I would love to have seen a descriptive thinking_sphinx.yml.example file describing the possible configuration. 

Right now we are upgrading from 2.1 to 3.1 and we are not sure which old settings are deprecated, and which new settings are available, etc.

The information for this is spread out over the FAQ, the changelog, installation instructions, common issues... And it's probably not 100% covering the config.

**Comment by pat** [comment]
Almost four years late, but here we go:
https://gist.github.com/pat/a7d73376dd657b4457092efc9e9c418a

It'll be linked to in the forthcoming documentation update (which is part of the TS v4.0.0 release - which in turn is just waiting on Rails 5.2).
