### ISSUE TITLE
Support of Unix sockets for SphinxQL protocol

### ISSUE THREAD

**Issue by lloeki** [pat/thinking-sphinx#817]
`ThinkingSphinx::Connection` passes options straight to the `mysql2` gem, yet the latter expects `:socket` and `:address` to differ, reserving the first one for the host name. The following monkey patch works around that and ultimately gives Mysql2::Client the socket path in `:socket`.

``` ruby
# 
module ThinkingSphinx::Connection
  def self.new
    configuration = ThinkingSphinx::Configuration.instance
    # If you use localhost, MySQL insists on a socket connection, but Sphinx
    # requires a TCP connection. Using 127.0.0.1 fixes that.
    address = configuration.searchd.address || '127.0.0.1'
    address = '127.0.0.1' if address == 'localhost'

    options = {
      :reconnect => true
    }

    if address.index('/').nil?
      options.merge!(:host => address,
                     :port => configuration.searchd.mysql41)
    else
      options.merge!(:socket => address)
    end

    options.merge!(configuration.settings['connection_options'] || {})

    connection_class.new options
  end
end
```

Note that `thinking_sphinx.yml` should be configured this way:

``` yaml
development:
    listen: tmp/pids/sphinx.sock:mysql41
    address: tmp/pids/sphinx.sock
```

**Comment by blackjid** [comment]
this would be awesome! :+1:

**Comment by pat** [comment]
Like #816, this took me far too long to get to, but it's done: if you set `socket` in the appropriate environments within `config/thinking_sphinx.yml`, TS will use that value in the generated configuration file, and also when connecting to the daemon for search requests. Relative socket values will be translated to absolute paths under the hood.

The one caveat: if you want to use this with JRuby, you will also need to provide an explicit address and/or mysql41 value (Sphinx will be available by both TCP and socket connections). JDBC doesn't seem to support socket connections, so search queries from within TS will still operate over TCP. Thus, it's not really useful from a JRuby perspective.

Should that be a particularly annoying problem for anyone (I'm doubtful), I do welcome pointers on using JDBC/MySQL with sockets, or PRs with solutions!

The changes for all of this exist in the `develop` branch, and will be part of the next gem release (I'm as yet undecided whether it'll be 3.5.0 or 4.0.0).

**Comment by lloeki** [comment]
@pat That's fantastic, big cheers for tackling both of those, thank you!
