### ISSUE TITLE
Real-time vs Plain index consistency

### ISSUE THREAD

**Issue by chancedowns** [pat/thinking-sphinx#832]
I have a rather large data-set that I'm trying to use real-time indices on. The issue is that it takes roughly 2 hours to run generate. However, I found that you can run the sphinx ATTACH command to convert a plain index to a real-time index which is magnitudes faster (something like 10 seconds for it all vs 2 hours).
There are a few inconsistencies I'm finding with Real-time indices and plain indices that have come up:

1) sphinx_internal_id is a bigint on the plain index, but an integer on the real-time index. I believe that the change for plain indices in https://github.com/pat/thinking-sphinx/commit/c53cd88180fede61453eee27ee5a626e77286d43 didn't get ported for real-time indices. 

2) Also, there isn't a way to set an attribute type to bigint. I believe there just needs to be another when statement in https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/real_time/index.rb#L60 which would be similar to the integer case.

3) Real-time indices always seem to get the 'sphinx_internal_class_name' attribute, but plain indices only get it if they are for an STI index (due to https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/configuration/minimum_fields.rb#L10 ). I'm not sure if there's a work-around for this or a way to hardcode a value temporarily into a plain index so I can use it to convert to a real-time index.

4) Sorted fields in a Real-time index get an attribute with _sort, whereas the plain index just has the field.  It looks like the reason is because real-time indices have to have them split out (per https://github.com/pat/thinking-sphinx/commit/9b1f0f02730787a2c0edca25a7c5bd71b306d982 ). I can just include the same field as not sortable and add it as an attribute with _sort as the name, but not sure if that's the intended solution (if there is one).

Lastly, is there any plan to create some way to take a plain index and convert it to a real-time index? I was looking into creating a rake task for it, but am not sure the best/most ideal place. The syntax is:

``` sql
ATTACH INDEX <plain_index_name> TO RTINDEX <real_time_index_name>;
```

and you need to make sure the real-time index is empty, which you can use:

``` sql
TRUNCATE RTINDEX <real_time_index_name>;
```

**Comment by pat** [comment]
As part of some tidying up of my open source repos, I'm going to close this issue.

I'd love to see this feature happen, but it's a massive amount of work given the many small differences in behaviour between RT and SQL indices. It's not something I've had much demand for at all, so I'm not going to put time into sorting it out.

That said, if others want to give it a shot, I'm open to PRs, and happy to discuss implementation details to help things along :)
