### ISSUE TITLE
Facets not working with has_and_belongs_to_many

### ISSUE THREAD

**Issue by RCReddy** [pat/thinking-sphinx#870]
Hi @pat ,

One of my indices have indexes like:

indexes "SELECT restaurant_id * 2 + 0 as id, cuisines.name as cuisine FROM cuisines_restaurants INNER JOIN cuisines ON cuisine_id = cuisines.id ORDER BY restaurant_id", as: :cuisine, source: :query
  indexes "SELECT restaurant_id * 2 + 0 as id, features.name as feature FROM features_restaurants INNER JOIN features ON feature_id = features.id ORDER BY restaurant_id", as: :feature, source: :query
  indexes :name, permalink, :sortable => true
  indexes locality.name, :as => :locality, :sortable => true, :facet => true
  indexes :status, :facet => true
  indexes deal,          :as => :deal, :sortable => true, :facet => :true
  indexes sessions.name, :as => :session_name
  indexes sessions.days, :as => :session_days
  indexes sessions.type_of_session, :as => :session
  indexes locality.city.name, :as => :city
  indexes buffets.buffet_type, :as => :buffet_type
  indexes buffets.buffet_days.days_array, :as => :buffet_day
  indexes [name, locality.name, cuisines.name], :as => :name_loc_cuisine, :sortable => true
  indexes "concat(CASE vegetarian WHEN 1 THEN 'Vegetarian' WHEN 0 THEN 'Non Veg' ELSE '' END, CASE alcohol WHEN 1 THEN ',Alcohol' ELSE '' END, CASE a_la_carte WHEN 1 THEN ',A la carte' ELSE '' END, CASE buffet WHEN 1 THEN ',Buffet' ELSE '' END )", :as => :offer

  has rank
  has cost,              :as => :cost
  has vegetarian,        :as => :veg, :facet => :true
  has alcohol,           :as => :alcohol, :facet => :true
  has buffets.buffet_days.non_veg_cost, :as => :buffet_nonveg_cost, :type => :integer, :sortable => true
  has buffets.buffet_days.veg_cost, :as => :buffet_veg_cost, :type => :integer, :sortable => true
  has latitude,  :as => :lat,  :type => :float
  has longitude, :as => :lng, :type => :float
  has cost_range.range, :as => :cost_range, :facet => true
  has "SELECT restaurant_id * 2 + 0 as id, cuisine_id as cuisine_id FROM cuisines_restaurants ORDER BY restaurant_id", as: :cuisine_id, source: :query, facet: true, type: :integer, multi: true
  has "SELECT restaurant_id * 2 + 0 as id, feature_id as feature_id FROM features_restaurants ORDER BY restaurant_id", as: :feature_id, source: :query, facet: true, type: :integer, multi: true
  has "SELECT restaurant_id * 2 + 0 as id, session_name_id as session_name_id FROM sessions ORDER BY restaurant_id", as: :session_name_id, source: :query, facet: true, type: :integer, multi: true
  has "SELECT restaurant_id * 2 + 0 as id, session_type_id as session_type_id FROM sessions ORDER BY restaurant_id", as: :session_type_id, source: :query, facet: true, type: :integer, multi: true
  has "SELECT restaurant_id * 2 + 0 as id, buffet_name_id as buffet_name_id FROM buffets ORDER BY restaurant_id", as: :buffet_name_id, source: :query, facet: true, type: :integer, multi: true
  has "SELECT restaurant_id * 2 + 0 as id, veg_cost_range_id as veg_cost_range_id FROM buffet_days ORDER BY restaurant_id", as: :veg_cost_range_id, source: :query, facet: true, type: :integer, multi: true
  has "SELECT restaurant_id * 2 + 0 as id, nonveg_cost_range_id as nonveg_cost_range_id FROM buffet_days ORDER BY restaurant_id", as: :nonveg_cost_range_id, source: :query, facet: true, type: :integer, multi: true
  has :created_at

indexing is  working good and fast.
For 500 records facets are working but some times erratic behavior for  cuisine_id, feature_id, session_name_id, session_type_id, buffet_name_id, veg_cost_range_id, nonveg_cost_range_id
Ex. if i filter with location it displaying some restaurants which is having cuisines but facets are not showing any count.

For 10000 records there is no facets count  for  cuisine_id, feature_id, session_name_id, session_type_id, buffet_name_id, veg_cost_range_id, nonveg_cost_range_id

Do i need to change any thing?

**Comment by pat** [comment]
Hmm. This is a tricky thing to debug remotely...

I'd recommend connecting to your Sphinx daemon via the mysql command-line tool and running SphinxQL queries to see what the data's looking like in Sphinx, perhaps that holds some clues.

```
mysql --host 127.0.0.1 --port 9306
```

The SphinxQL queries (very similar to SQL) will be in your Rails logs, so that should be a helpful starting point. Also, the Sphinx documentation may be helpful too: http://sphinxsearch.com/docs/current.html#sphinxql-select

**Comment by RCReddy** [comment]
Thanks pat.

**Comment by pat** [comment]
Certainly happy to help further if your SphinxQL querying finds any further clues :)

**Comment by RCReddy** [comment]
No. I checked it by runnig sphinxQL qeries in mysql, i didn't get any results. Only sql join fields are not working, it showing zero results. I didn't get any clues.
I have changed my code.
  has cuisines.id, :as => :cuisine_id, :facet => :true
  has features.id, :as => :feature_id, :facet => :true
  etc..
 
Indexing is very slow but everything working.

I would like to know how many associations we can add. Is there any limit?
how many has_one, has_many, has_and_belongs_to_many, has_many_through fieds or attributes we can index in single indices?

**Comment by pat** [comment]
There's no fixed limit for the number of associations, but certainly every join makes things slower. Have you got database indices on your foreign key columns?

Also, what if you add `:query => :source` to those attributes you've just mentioned?
