### ISSUE TITLE
Searching without certain middlewares breaks `each_with_weight`

### ISSUE THREAD

**Issue by bricker** [pat/thinking-sphinx#874]
#### The Problem
When using the `RAW_ONLY` middleware collection, `each_with_weight` throws an error:

```
NoMethodError: undefined method `[]' for #<Mysql2::Result:0x007fe39465ce60>
from /Users/rickb014/clones/thinking-sphinx/lib/thinking_sphinx/search.rb:115:in `method_missing'
```

#### The Cause
In most middlewares, `context[:results]` is converted to an Array. For example:
* [`ActiveRecordTranslator`](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/middlewares/active_record_translator.rb#L25)
* [`Glaizer`](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/middlewares/glazier.rb#L22)

This doesn't happen in any of the [`BASE_MIDDLEWARES`](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/middlewares.rb#L13) (the only middlewares loaded when `RAW_ONLY` is used), which leaves `context[:results]` as a `Mysql2::Result` object. `Mysql2::Result` doesn't define a `[]` method. Through the `method_missing` hook on `ThinkingSphink::Search`, [this line](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/masks/weight_enumerator_mask.rb#L12) eventually attempts to call `[]` on `context[:results]`, a `Mysql2::Result` object.

Perhaps this is expected behavior, that's fine (after all, you are asking for *raw* results). However, `each_with_weight` should (and can) still work.

#### Proposed fixes
Before sending a PR I'd like to see which is your preferred fix:

1. Add a middleware to the front of `BASE_MIDDLEWARES` which simply converts `context[:results]` to an array, for consistency. This would still cause `each_with_weight` to break if *no* middlewares are used, but maybe giving the option to skip the Array coercion is good.
2. Update [this line](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/masks/weight_enumerator_mask.rb#L12) to something like:

```ruby
# Coerce @search into an Array
yield @search.raw.to_a[index], row[ThinkingSphinx::SphinxQL.weight[:column]]
```

Thanks! Let me know if you need clarification of the problem or proposed solutions.

**Comment by bricker** [comment]
Here's an example "Array middleware" as a workaround:

```
module ThinkingSphinx
  module Middlewares
    class ArrayResults < Middleware
      def call(contexts)
        contexts.each do |context|
          context[:results] = context[:results].to_a
        end

        app.call contexts
      end
    end
  end
end
```

**Comment by pat** [comment]
I'd be open to a middleware added at the end of `BASE_MIDDLEWARES` to convert results to arrays - but maybe it's better having that in `Inquirer`, the existing last middleware in that set? It feels like it's a somewhat appropriate fit, given that's what sets `context[:results]`, and setting it to be consistently an array is probably wise.

**Comment by pat** [comment]
And thanks for the thought that's gone into this!

**Comment by bricker** [comment]
Good idea. I've opened #875 with this change. Happy new year :)

**Comment by pat** [comment]
Happy New Year indeed (it's 2015 here :) - just merged this patch, greatly appreciated!
