### ISSUE TITLE
Escape/sanitize SphinxQL reserved words?

### ISSUE THREAD

**Issue by liveh2o** [pat/thinking-sphinx#876]
We've come across an issue where our users are querying Sphinx for "Paragraph". This raises an exception because (apparently) PARAGRAPH is a reserved token in SphinxQL:

> ThinkingSphinx::SyntaxError: index transaction_description_core: syntax error, unexpected TOK_PARAGRAPH near 'PARAGRAPH|9TH|AVE|SAN|FRANCISCOCAUS|ENDING|IN' - SELECT *, groupby() AS sphinx_internal_group, id AS sphinx_document_id, count(DISTINCT sphinx_document_id) AS sphinx_internal_count FROM `transaction_description_core` WHERE MATCH('PARAGRAPH|9TH|AVE|SAN|FRANCISCOCAUS|ENDING|IN') AND `sphinx_deleted` = 0 GROUP BY `sphinx_internal_class` LIMIT 0, 1000 OPTION max_matches=1000, ranker=proximity; SHOW META; SELECT *, groupby() AS sphinx_internal_group, id AS sphinx_document_id, count(DISTINCT sphinx_document_id) AS sphinx_internal_count FROM `transaction_description_core` WHERE MATCH('PARAGRAPH|9TH|AVE|SAN|FRANCISCOCAUS|ENDING|IN') AND `sphinx_deleted` = 0 GROUP BY `category_guid` LIMIT 0, 1000 OPTION max_matches=1000, ranker=proximity; SHOW META

We have implemented a temporary workaround that simply removes any reserved tokens (MAYBE, NEAR, SENTENCE, PARAGRAPH, ZONE) before querying Sphinx. Is there a preferred way that this should be handled? This seems like something that could be handled by TS (or possibly Riddle), but it appears that special (reserved?) characters are the [only thing being escaped](https://github.com/pat/riddle/blob/master/lib/riddle/query.rb#L101-L103).

**Comment by pat** [comment]
I'd be open to escaping handling these words - I wasn't aware that this behaviour was the case - but I worry about the edge cases: in particular, is it reserved if it's wrapped in quotes? Is there some way of escaping it that keeps it in the query? Probably good to have this discussion with the Sphinx team on their forum.

**Comment by liveh2o** [comment]
I did a quick search before I posted this, but didn't dive much deeper. Posting in the forums is a good idea. I'll also play around with adding quotes to see if there's a better way to do this, other than simply omitting them.

**Comment by lytnus** [comment]
I am having the same issue with escaping of reserved words; I'd be interested to know what you find. The best I can do is use the SphinxAPI and SetMatchMode to SPH_MATCH_ANY, which seems to ignore all special chars (and then rank so that more matched words = higher), but this is deprecated I gather and Id rather have a 'proper' solution :)

**Comment by jdelStrother** [comment]
I'm also running into this with people searching for 'MAYBE'.   Was this closed because you consider it fixed?   Did anyone make any progress on the regular sphinx forums?

**Comment by pat** [comment]
Not sure if @liveh2o went asking around on the Sphinx forum - I just closed this issue because it went quiet. I still remain open to patches, I just don't have much of an idea around how the edge cases should be handled :)

**Comment by liveh2o** [comment]
We're actually no longer using Sphinx the way we were, so I didn't end up posting in the Sphinx forum. Still think that's the best approach.

**Comment by jdelStrother** [comment]
Perhaps something like https://github.com/jdelStrother/riddle/commit/c26d5055080c547c4921152684873ced6e7ebfa1 ?

**Comment by pat** [comment]
`Riddle::Query.escape` (and the wrapper method in TS v3, `ThinkingSphinx::Query.escape`) is meant for SphinxQL queries, whereas `Riddle.escape` is for the older binary protocol queries (e.g. used by TS v1/v2).

So, what you've written is great, but it should be applied to `Riddle::Query.escape` instead :)

**Comment by jdelStrother** [comment]
Ok, will submit a PR against the latter
