### ISSUE TITLE
Can't remove transactional callbacks deprecation warning...

### ISSUE THREAD

**Issue by raviada** [pat/thinking-sphinx#877]
https://github.com/rails/rails/issues/18084

Pat, I saw this in rails gem issues, I am also getting the same warning message when I upgraded to 4.2. I did the similar exercise to comment all the gem and uncommenting one at a time. I was able to reproduce this warning message when I have "thinking-sphinx" gem in the gemfile. When I remove it, there is no warning. I think TS is loading AR too quickly before the it completely execute the application.rb, I am not completely sure why.

I have set     ```config.active_record.raise_in_transactional_callbacks = true``` in ```application.rb```

**Comment by pat** [comment]
This is fixed in the develop branch :)
https://github.com/pat/thinking-sphinx/issues/867#issuecomment-67950923

**Comment by raviada** [comment]
Thank you!!
