### ISSUE TITLE
Error connecting to Sphinx via the MySQL protocol.

### ISSUE THREAD

**Issue by xiaominger** [pat/thinking-sphinx#880]
I'm using coreseek4.2，but there are some issues:“ connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (111) - SELECT * FROM listing_core, listing_delta WHERE MATCH('股票') AND community_ids = 1 AND sphinx_deleted = 0 ORDER BY sort_date DESC LIMIT 0, 24; SHOW META”

**Comment by pat** [comment]
Sorry, I'm not quite sure what coreseek is?

But if you're using Thinking Sphinx, have you run `rake ts:start` to get the daemon running? Does it look like it was successful from the output?

**Comment by grishkovelli** [comment]
This error is related to the work of Keyword Highlighting and in case more than one daemon is running on different ports.  I connected to 9301 PORT with mysql, but may be use a different port than in the config?

**Comment by pat** [comment]
@grishkovelli if you're using more than one daemon, do you have them configured to use different ports? And do you know if you're using the right port?

**Comment by grishkovelli** [comment]
This my thinking_sphinx.yml:

```javascript
development:
  min_infix_len: 1
  charset_table: "0..9, english, U+0021..U+002F"
  mysql41: 9301
production:
  min_infix_len: 1
  charset_table: "0..9, english, U+0021..U+002F"
  mysql41: 9302
```

**Comment by pat** [comment]
You've set it correctly in your `config/thinking_sphinx.yml` file. Can you confirm the `listen` setting in the generated `config/development.sphinx.conf` has the right port number as well?

Do you have multiple applications running Sphinx daemons on your machine? Are they all using unique port numbers?

**Comment by khanimdad** [comment]
@pat i have same error, any help would be appreciated 

bundle exec rake ts:rebuild RAILS_ENV=production
searchd is not currently running.
Stopped searchd daemon (pid: ).
Generating configuration to /*********************/production.sphinx.conf
rake aborted!
Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `new'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `mysql2_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/model_schema.rb:230:in `table_exists?'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinkin


And here is the config/thinking_sphinx.conf

`production:
  address: 127.0.0.1
  # port: 9312
  mysql41: 19312 #9306
  configuration_file: "********************/production.sphinx.conf"
  log: "********************/shared/log/searchd.log"
  query_log: "********************/shared/log/searchd.query.log"
  pid_file: "********************/shared/log/searchd.production.pid"
`

**Comment by khanimdad** [comment]
@pat i have same error, any help would be appreciated 

bundle exec rake ts:rebuild RAILS_ENV=production
searchd is not currently running.
Stopped searchd daemon (pid: ).
Generating configuration to /*********************/production.sphinx.conf
rake aborted!
Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `new'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `mysql2_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/model_schema.rb:230:in `table_exists?'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinkin

production:
  address: 127.0.0.1
  # port: 9312
  mysql41: 19312 #9306
  configuration_file: "/*********************//shared/config/production.sphinx.conf"
  log: "/*********************/shared/log/searchd.log"
  query_log: "/*********************/shared/log/searchd.query.log"
  pid_file: "/*********************/shared/log/searchd.production.pid"

**Comment by khanimdad** [comment]
Here is the config/thinking_sphinx.conf

production:
  address: 127.0.0.1
  # port: 9312
  mysql41: 19312 #9306
  configuration_file: "/var/apps/youtoo/shared/config/production.sphinx.conf"
  log: "/var/apps/youtoo/shared/log/searchd.log"
  query_log: "/var/apps/youtoo/shared/log/searchd.query.log"
  pid_file: "/var/apps/youtoo/shared/log/searchd.production.pid"

**Comment by pat** [comment]
Hi @khanimdad - judging by the stack trace, it looks like the problem is that your database isn't available?

**Comment by khanimdad** [comment]
@pat , actually my database is available and i can "rails c" and can find records.

**Comment by pat** [comment]
Hmm, that's odd. The error, from what I can tell from the stack trace, is coming from Rails trying to load the database schema to determine if a model's table exists. It's not a connection to Sphinx that's failing (because TS does not use Rails' connection pool code).

Although, the stack trace also refers to an initialiser in your app - what's happening in `config/initializers/mysql2.rb`?

**Comment by khanimdad** [comment]
Here is config/initializers/mysql2.rb
``module ActiveRecord
  class Base
    # Overriding ActiveRecord::Base.mysql2_connection
    # method to allow passing options from database.yml
    #
    # Example of database.yml
    #
    #   login: &login
    #     socket: /tmp/mysql.sock
    #     adapter: mysql2
    #     host: localhost
    #     encoding: utf8
    #     flags: 131072
    #
    # @param [Hash] config hash that you define in your
    #   database.yml
    # @return [Mysql2Adapter] new MySQL adapter object
    #
    def self.mysql2_connection(config)
      config[:username] = 'root' if config[:username].nil?

      if Mysql2::Client.const_defined? :FOUND_ROWS
        config[:flags] = config[:flags] ? config[:flags] | Mysql2::Client::FOUND_ROWS : Mysql2::Client::FOUND_ROWS
      end

      client = Mysql2::Client.new(config.symbolize_keys)
      options = [config[:host], config[:username], config[:password], config[:database], config[:port], config[:socket], 0]
      ConnectionAdapters::Mysql2Adapter.new(client, logger, options, config)
    end
  end
end``

**Comment by pat** [comment]
Hmm, there's nothing there that seems like a cause of the problem… but again: the error is happening because Thinking Sphinx is trying to check what a model's primary key is, and that's reliant on the database being available. Are all your models (especially your indexed models) using the same database connection? Can you confirm that you're able to access records in `rails c` for every model that has a Sphinx index?

**Comment by khanimdad** [comment]
Yes @pat i can do search on all the models which is indexed , so below works for all models

`ThinkingSphinx.search(keyword, :classes => [Model Name])`

And am not sure if they are using the same database connection, but for your information its working fine on my local machine but on production, i production am also using monit

**Comment by pat** [comment]
Sorry, I wasn't quite clear. For each indexed model, does this work? `Model.first` - or better yet, does `Model.primary_key` work? And are you using STI for any of your indexed models?

**Comment by khanimdad** [comment]
Yes its working for all model i tried `Model.primary_key`, and yes am using STI as well

**Comment by pat** [comment]
It's working on your production server? Because you're running the same code Thinking Sphinx is running, so I've got no idea why it works in one situation but not the other.

**Comment by khanimdad** [comment]
No its not working on production server, but on my local machine

**Comment by pat** [comment]
Okay, you'll want to check `Model.primary_key` for each indexed model, on production.

**Comment by khanimdad** [comment]
`Model.primary_key` working fine on production server for all indexed model

**Comment by pat** [comment]
Okay. Can you share the full stack trace of the error? It'll help me understand exactly what's happening.

**Comment by khanimdad** [comment]
@pat  here you go

```
bundle exec rake ts:rebuild RAILS_ENV=production
searchd is not currently running.
Stopped searchd daemon (pid: ).
Generating configuration to /var/apps/youtoo/shared/config/production.sphinx.conf
rake aborted!
Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `new'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `mysql2_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/model_schema.rb:230:in `table_exists?'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/index.rb:66:in `source_options'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/index.rb:9:in `append_source'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/interpreter.rb:64:in `__source'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/interpreter.rb:20:in `indexes'
/var/apps/youtoo/releases/20170602211332/app/indices/artist_index.rb:2:in `block in <top (required)>'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/core/interpreter.rb:3:in `translate!'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/core/index.rb:38:in `interpret_definition!'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/index.rb:32:in `sources'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:31:in `collect'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:31:in `sources'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:19:in `attributes'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:23:in `sphinx_internal_ids'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:7:in `reconcile'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:90:in `render'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `block in render_to_file'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `render_to_file'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:24:in `configure'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:35:in `index'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in <top (required)>'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => ts:rebuild => ts:index
(See full trace by running task with --trace)
```

**Comment by pat** [comment]
Thanks, that's definitely useful. Can you now share the contents of `app/indices/artist_index.rb` please?

**Comment by pat** [comment]
Also: is Artist an STI model?

**Comment by khanimdad** [comment]
Yes Artist is an STI and the contents of `app/indices/artist_index.rb`  is below

```
ThinkingSphinx::Index.define :artist, :with => :active_record do
  indexes title#, :sortable => true
  indexes ntitle
  #indexes search_keywords
  set_property :enable_star => true
  set_property :min_infix_len => 1 
  set_property :morphology => 'stem_en'
  # attributes
  has youtoo_popularity, created_at, updated_at
end
```

**Comment by pat** [comment]
I don't think this is a fix, but just to see if a different error crops up: can you change the first line of that index from:

`ThinkingSphinx::Index.define :artist, :with => :active_record do`

to

`ThinkingSphinx::Index.define :artist, :with => :active_record, :primary_key => :id do`

And then re-run the rake task and see if anything's changed? Is it the same error? Does it have the same index definition in the stack trace?

**Comment by khanimdad** [comment]
No luck, still same error 

```
bundle exec rake ts:rebuild RAILS_ENV=production
searchd is not currently running.
Stopped searchd daemon (pid: ).
Generating configuration to /var/apps/youtoo/shared/config/production.sphinx.conf
rake aborted!
Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `new'
/var/apps/youtoo/releases/20170602211332/config/initializers/mysql2.rb:26:in `mysql2_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:15:in `initialize'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/index.rb:8:in `new'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/index.rb:8:in `append_source'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/interpreter.rb:64:in `__source'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/interpreter.rb:20:in `indexes'
/var/apps/youtoo/releases/20170602211332/app/indices/artist_index.rb:3:in `block in <top (required)>'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/core/interpreter.rb:3:in `translate!'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/core/index.rb:38:in `interpret_definition!'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/index.rb:32:in `sources'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:31:in `collect'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:31:in `sources'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:19:in `attributes'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:23:in `sphinx_internal_ids'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration/consistent_ids.rb:7:in `reconcile'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:90:in `render'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `block in render_to_file'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `render_to_file'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:24:in `configure'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:35:in `index'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in <top (required)>'
/var/apps/youtoo/shared/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => ts:rebuild => ts:index
(See full trace by running task with --trace)
```

**Comment by khanimdad** [comment]
Apart from `artist.rb` i also have other models which are STI and are indexed

**Comment by pat** [comment]
I'm really confused as to what the cause of this error is. In production, is your database on the same machine (i.e. 127.0.0.1), or is it running elsewhere?

**Comment by khanimdad** [comment]
In production we have 3 machine, but database and sphinx are same machine

**Comment by pat** [comment]
When you were running the `rails c` command in production and checking `Model.primary_key`, were you doing that on the Sphinx/Database machine, or one of the other machines?

**Comment by khanimdad** [comment]
Yes doing `rails c -e production` on machine which have DB and sphinx, may be below input can also help you which is from production server 

```
 $pgrep searchd
25238
25239
$ service searchd status
● searchd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

**Comment by pat** [comment]
Short of having access to the production machine myself to debug directly, I'm afraid I'm out of ideas for fixing this problem.

I don't think it's Sphinx/Thinking Sphinx related, though I'm confused as to why the database connection failure is happening only when configuring Sphinx, but not via the Rails console.

If anything else does come to mind, I'll certainly let you know.

**Comment by khanimdad** [comment]
Thanks @pat for all the attempts :).

Will let you know if i manage to fix it
