### ISSUE TITLE
set_database doesn't work in Rails 4.2

### ISSUE THREAD

**Issue by antage** [pat/thinking-sphinx#885]
In Rails 4.2 `ActiveRecord::Base.configurations` has all keys as string. But TS can't read database parameters because trying find it by symbol keys.

I convert all keys in symobls as workaround:
```
set_database ActiveRecord::Base.configurations["production"].map { |k, v| [k.to_sym, v] }.to_h
```

**Comment by pat** [comment]
Thanks for reporting this - I've just fixed it in the `develop` branch.
