### ISSUE TITLE
sphinx with synonyms 

### ISSUE THREAD

**Issue by joker-777** [pat/thinking-sphinx#886]
Hello,

I want to achieve the following behavior:

If I search for "os coxae" it should search for "os coxae", "ossae coxae" and "ossis
coxae". It should also sort the result in that way that results correspond to "os coxae"
stay on top. Additionally I use metaphone.

I tried to use wordforms with the following file

ossa > os
ossis > os

Unfortunately it only works in one direction. If I search for os for example it finds all
elements which contain os, ossa and ossis. But I want to have the opposite behavior which
doesn't work.

It would be great if anyone could help me finding the best solution.

Thanks in advance,

Johannes

**Comment by pat** [comment]
Hi Johannes

I'm afraid I don't know the answer to this question (or #887) - and my brain's a little broken after running a conference over the last few days. I think a better place to ask is the [Sphinx forum](http://sphinxsearch.com/forum/), given these aren't issues specific to Thinking Sphinx - and the people there will certainly have a deeper understanding of what the right approach could be.

So, I'm going to close this issue - but if you do find a solution, it'd be great to hear it :)

**Comment by joker-777** [comment]
No problem Pat. This forum seems to me quite abandoned. That's why I was hoping you could help me out since you must have a really good understanding of sphinx through developing thinking-sphinx.

**Comment by pat** [comment]
I certainly have a somewhat decent understanding of Sphinx, but I've not delved into metaphone, nor played much with wordforms. I think the Sphinx forum does receive some activity - the first few posts in the list are pinned to the top (hence why some are very old) but beyond that it seems there are posts/comments pretty much every day.
