### ISSUE TITLE
Delta indexing stops working after a few hours.

### ISSUE THREAD

**Issue by isaacsloan** [pat/thinking-sphinx#889]
Preliminarily I'm just trying to find out if this is a known error with a solution. I couldn't find anything after 20 minutes of google searching. I found a few people who had issues with delta's not working on production but that isn't my issue. They work fine on production for a few hours to a day then they just stop.

I'm using Sphinx 2.2.6-id64-release and thinking-sphinx (3.1.2). This project is currently in beta and has very little live data so it doesn't seem to be an issue of the delta's getting too big. Running rake ts:rebuild fixes the issue for a while, but rake ts:index doesn't. I'm checked and the permissions are all good. I've been using thinking sphinx for 6 years but never used delta's on a big project so this is a new issue for me. I've currently put a bandaid on it by running rake ts:rebuild in the crontab every hour. 

Any idea's?

**Comment by pat** [comment]
It's odd that ts:index doesn't fix things, but ts:rebuild does.

Are you running ts:index on a regular basis anyway? Any luck on seeing this issue reproduce?

**Comment by isaacsloan** [comment]
Well it's been working for 13 hours now so hopefully it will break again soon.

**Comment by isaacsloan** [comment]
Solved. It was a similar issue to this only it was just usind the default config/production.sphinx.conf even though I had it defined. Using an absolute path fixed it. http://stackoverflow.com/questions/26848081/thinking-sphinx-not-generating-configuration-file

**Comment by pat** [comment]
Ah, good to know you figured it out :)
