### ISSUE TITLE
polymorphic association and real_time index

### ISSUE THREAD

**Issue by raviada** [pat/thinking-sphinx#892]
I have a polymorphic association and trying to create a real_time index on it. I am getting an error while generating the index.
```
ThinkingSphinx::SphinxError: index 'training_core' does not support INSERT (enabled=1) - REPLACE INTO training_core (id, `sphinx_internal_class_name`, `name`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`) VALUES (6463012, 'Training', 'Allegheny General Hospital', 3231506, 'Training', 0)
```
Is it even supported? Here is my index definition

```
ThinkingSphinx::Index.define :training, :with => :real_time do
	polymorphs training_entity, :to => %w(Hospital Medschool)

	indexes training_entity.name

	set_property :min_prefix_len => 2
end
```

**Comment by raviada** [comment]
sorry my bad. I am closing this issue..

**Comment by f00stx** [comment]
Hi, would you mind commenting on what the issue was in the end? I'm having the same issue and this report is literally the only search result for this specific error. Thanks!

**Comment by pat** [comment]
Hi Richard,

Can you share your index definition, as well as the versions of Thinking Sphinx and Sphinx you're using? Also, it's worth noting that the `polymorphs` method is only useful in SQL-backed indices - real-time indices are dealing with Ruby methods, not SQL joins, so calls on such methods should work fine as they are.
