### ISSUE TITLE
Indexing new record

### ISSUE THREAD

**Issue by andrkrn** [pat/thinking-sphinx#893]
- Rails 4.1.9
- Thinking Sphinx 3.1.3
- Sphinx 2.2.7

/ indices
ThinkingSphinx::Index.define :footage, :with => :active_record do
  indexes title, sortable: true
  indexes abstract
  indexes tags.name, as: :tag_names

  indexes camera, lense, color, ratio, audio_recorder, audio_mixer, microphone, film

  has user_id, category_id, view_count, likes_count, created_at, updated_at, analog
  has published_at, as: :date
end

i need to run rake ts:index and then new record indexed

**Comment by pat** [comment]
This is how Sphinx behaves by default... but, if you want to have indices updated automatically with new/changed records, you can either investigate delta indices:
http://pat.github.io/thinking-sphinx/deltas.html

Or real-time indices:
http://freelancing-gods.com/posts/rewriting_thinking_sphinx_introducing_realtime_indices

**Comment by andrkrn** [comment]
nice, realtime indices !!!
