### ISSUE TITLE
ThinkingSphinx::Deltas::DelayedDelta not work with :conditions?

### ISSUE THREAD

**Issue by 4itosik** [pat/thinking-sphinx#896]
Hello,
My problem:
Example:
If I use  ThinkingSphinx::Deltas::DelayedDelta 
Requisition.search "#{params[:search_title]}", :order => 'created_at DESC', :conditions => {:sphinx_id => "1|2|3"} not work, 
but if I use rake ts:index, Sphinx all search!
What could be the problem?
Thx

**Comment by pat** [comment]
Are there any warnings or errors in your Rails logs or Delayed Job logs when a delta is processed?

**Comment by 4itosik** [comment]
When remove :conditions => {:sphinx_id => "1|2|3"} it worked

**Comment by pat** [comment]
Can you share your index definition for Requisition?

**Comment by 4itosik** [comment]
Now index definition 
ThinkingSphinx::Index.define :requisition, :with => :active_record, :delta => ThinkingSphinx::Deltas::DelayedDelta do
  indexes type_requisition.title, :as => :type_requisition_title, :sortable => true
  indexes sub_type_requisition.title, :as => :sub_type_requisition_title, :sortable => true
  indexes mileage
  indexes price
  indexes car.modification_car.title, :as => :car_modification_car_title, :sortable => true
  indexes car.modification_car.model_car.title, :as => :car_modification_car_model_car_title, :sortable => true
  indexes car.modification_car.model_car.brand_car.title, :as => :car_modification_car_model_car_brand_car_title, :sortable => true
  indexes car.modification_car.model_car.brand_car.type_car.title, :as => :car_modification_car_model_car_brand_car_type_car_title, :sortable => true
  indexes body
  indexes active
  indexes city.title, :as => :city_title, :sortable => true

  has active, created_at, updated_at, type_requisition_id, sub_type_requisition_id, car_id, user_id, end_trading
end

And I have warning if use rake ts:index

WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: 1 more warnings skipped.

**Comment by 4itosik** [comment]
thinking_sphinx.yml:

development:
  address: 127.0.0.1
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  config_file: "RAILS_ROOT/config/sphinx/development.sphinx.conf"
  searchd_log_file: "RAILS_ROOT/log/sphinx/searchd.log"
  query_log_file: "RAILS_ROOT/log/sphinx/searchd.query.log"
  pid_file: "/home/artem/project/sto/log/searchd.development.pid"
  utf8: true  
  morphology: 'stem_ru, stem_en'
  quiet_deltas: true

test:
  address: 127.0.0.1
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  config_file: "RAILS_ROOT/config/sphinx/development.sphinx.conf"
  searchd_log_file: "RAILS_ROOT/log/sphinx/searchd.log"
  query_log_file: "RAILS_ROOT/log/sphinx/searchd.query.log"
  pid_file: "/home/artem/project/sto/log/searchd.development.pid"
  utf8: true  
  morphology: 'stem_ru, stem_en'
  quiet_deltas: true

**Comment by pat** [comment]
The warnings can be ignored (I think those settings are removed in the `develop` branch too).

As for your search not working: there's no field or attribute called `sphinx_id` in your index definition, so that'd be why no matches are being returned. Did you mean to have something else other than `sphinx_id`?

**Comment by 4itosik** [comment]
This index definition I use, when remove :conditions => {:sphinx_id => "1|2|3"} and remove sphinx_id  from from index definition.

I use sphinx with active record search,My idei:

I add "Requisition.search "#{params[:search_title]}", :order => 'created_at DESC', :conditions => {:sphinx_id => "1|2|3"}"  at the end of the search block.
Sphinx_id = requisition.id. 
I wanted to look Requisitions  with sphinx, only found Requisitions in search block.

But this idea, not does not work properly.
I add  Requisition.search "#{params[:search_title]}", :order => 'created_at DESC' to the top search block, and add
Requisition.where(id: array_id_sphinx_result)

**Comment by pat** [comment]
If you want to limit a search by certain primary keys, these are automatically added to each Sphinx index as an attribute, which means you should use `:with` instead of `:conditions`, and the attribute is called `sphinx_internal_id`:

```ruby
Requisition.search params[:search_title],
  :order => 'created_at DESC',
  :with  => {:sphinx_id => [1, 2, 3]}
```

**Comment by 4itosik** [comment]
Thx, in next project I use this!

**Comment by pat** [comment]
So it's all working now?

**Comment by 4itosik** [comment]
Yes, all working!

**Comment by pat** [comment]
Great :)
