### ISSUE TITLE
 HTTP caching

### ISSUE THREAD

**Issue by RCReddy** [pat/thinking-sphinx#897]
Hi Pat, 

We need your help clearing this confusion!

Does HTTP caching work when using sphinx/thinking sphinx for faceted search? We are attempting http caching of index pages but it is failing possibly because maximum(:updated_at) is not fetched. 

Any solutions? Or is it that HTTP caching can't be done when using sphinx?

**Comment by pat** [comment]
I would presume HTTP caching would work - that's really dependent on your app and how it works though? As far as HTTP is concerned, it's just another page - whether Sphinx is being used or not shouldn't matter. Or is there something I'm missing here?
