### ISSUE TITLE
What is the latest sphinx version supported?

### ISSUE THREAD

**Issue by pedrocunha** [pat/thinking-sphinx#898]
Hello Pat,

What is the latest sphinx version supported? I tried to install 2.2.6 and I started to get a few warnings regarding:

```
WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
```

I had this on my `config/thinking_sphinx.yml`. Moving it to `app/indices/model_index.rb` as `set_property` seems to raise the same issue too.

Thanks in advance.

**Comment by pat** [comment]
The latest in the `develop` branch removes charset_type and sql_query_info, and you don't need to specify enable_star at all (it's always enabled now).

**Comment by pat** [comment]
But also: they're warnings, so while they're annoying, things will still work anyway.

**Comment by pedrocunha** [comment]
Thanks for your reply Pat.

I think `sql_query_info` is being generated by TS. Charset_type i'm using it to be able to convert accented chars and such. Does it mean it will lose support in the future OR it will be UTF-8 by default (i doubt it because probably of Chinese chars or/and similar)?

Seems I managed to make it work with 2.2.6 just fine too (one of my initial questions). Maybe worth to update the README to promote people on newer versions ?

**Comment by pat** [comment]
`sql_query_info` won't get generated by TS if you use the latest commits from the `develop` branch.

And it's worth noting the difference between `charset_type` (which is deprecated) and `charset_table` (which perhaps you're using for converting accented characters?) - charset_type is UTF8 only in Sphinx 2.2.

And once I get the next TS release out, updating the README is an excellent idea :)

**Comment by pedrocunha** [comment]
Thanks for all this information :100: ace as usual.
