### ISSUE TITLE
Does one need `enable_star: 1` for wildcard searching?

### ISSUE THREAD

**Issue by airblade** [pat/thinking-sphinx#899]
Hi Pat,

I want to enable wildcard searching so that, for example, a search for `jack` finds both `jacke` and `jacket`.

I added `min_prefix_length: 4` to the configuration, regenerated the sphinx config, reindexed, and found to my surprise that `jack*` matches `jacke` and `jacket`.  The query log shows `jack*` being sent to sphinx.  I had thought I would also need to add `enable_star: 1` to the configuration – is this unnecessary?

I'm on TS 3.1.2 with Riddle 1.5.11.

I was also wondering the best way to append the star automatically to queries.  My non-wildcard search looks like:

```ruby
ThinkingSphinx.search Riddle::Query.escape(q)
```

Should I do the following instead?

```ruby
ThinkingSphinx.search ThinkingSphinx::Query.wildcard(q)
```

Would I still need to escape the queries?  And my facet calls?  I looked at the code but wasn't sure.

Thanks!

**Comment by airblade** [comment]
It looks like I do still need to escape the queries:

```ruby
ThinkingSphinx.search(ThinkingSphinx::Query.wildcard(ThinkingSphinx::Query.escape(q)))
```

**Comment by pat** [comment]
With newer versions of Sphinx (I think 2.1 and definitely 2.2), enable_star is switched on (and cannot be switched off), so that'd explain why it works straight away.

If you want to automatically wildcard the queries (instead of expecting users to enter *'s), then yes, your escape + wildcard solution looks right to me.

**Comment by airblade** [comment]
I'm on Sphinx 2.2.4 so that explains it.  Thank you!

Thanks also for confirming the escape + wildcard.
