### ISSUE TITLE
Search without a query

### ISSUE THREAD

**Issue by ngan** [pat/thinking-sphinx#900]
Hey Pat, I'm trying to upgrade to TS 3 and Sphinx 2.  How do you perform a perform a search without a query?

e.g. `Foo.search("bar", options)` gives me results, but `Foo.search(options)` doesn't.

In TS 2, the later would consider all rows as matched.

**Comment by pat** [comment]
I would certainly expect `Foo.search(options)` to work - does it work with no options? Does it seem like there's a specific option that could be part of the problem?

**Comment by ngan** [comment]
I'm getting...
```
>> Foo.search
  Sphinx Query (3.1ms)  SELECT * FROM `foo_core` WHERE MATCH('[]') AND `sphinx_deleted` = 0 LIMIT 0, 20 OPTION max_matches=100000
  Sphinx  Found 0 results
```

I think the `MATCH('[]')` is the culprit...but not sure how to remove it.

**Comment by pat** [comment]
Hmm, maybe it is a bug in TS! Which version are you using?

Also, as a workaround, try passing through nil as the query: `Foo.search(nil, options)`

**Comment by ngan** [comment]
```
thinking-sphinx (3.1.3)
```

`nil` doesn't work either...

```
>> Foo.search(nil)
  Sphinx Query (3.2ms)  SELECT * FROM `foo_core` WHERE MATCH('[nil]') AND `sphinx_deleted` = 0 LIMIT 0, 20 OPTION max_matches=100000
  Sphinx  Found 0 results
```

**Comment by pat** [comment]
I'm not seeing this issue locally (using TS v3.1.3 as well). You're not overwriting the search method, or perhaps using a default sphinx scope or something else that may be different?

**Comment by ngan** [comment]
Argh! we were overriding.  Thanks Pat. As always, you're the BEST!

**Comment by pat** [comment]
No worries :)

**Comment by ngan** [comment]
One more quick question :-D  We have 2 indices for 1 model.   When doing Foo.search, is there a way to default to just one of the indexes (and not search both unless specified)?

**Comment by pat** [comment]
I think the following should work, within your model:

```ruby
sphinx_scope(:main_index_only) { {:indices => ['foo_core']} }
default_sphinx_scope :main_index_only
```

**Comment by pat** [comment]
Oh, and include this module into your model: `include ThinkingSphinx::Scopes`

**Comment by ngan** [comment]
:heart:
