### ISSUE TITLE
Records missing from Sphinx results after updating

### ISSUE THREAD

**Issue by mrjamesriley** [pat/thinking-sphinx#902]
Hi all, having a issue that I haven't managed to make sense of for the last few hours - where records are missing from search results once they have been updated. I've been able to replicate it on a fresh Rails app, using the latest gems. Have also replicated this with a Rails 4 app. Here's the details:

````
thinking-sphinx - 3.1.3
ts-datetime-delta - 2.0.1
Rails - 3.2.21

Sphinx version: 2.2.7-id64-release (r4883)
````

The Animal Model:
````ruby
# app/models/animal.rb
class Animal < ActiveRecord::Base
  attr_accessible :name
end
````

The Animal Index:
````ruby
# app/indices/animal_index.rb
ThinkingSphinx::Index.define(:animal,
     with: :active_record,
          delta: ThinkingSphinx::Deltas::DatetimeDelta,
          delta_options: { threshold: 1.minute }
     ) do
     indexes name
     indexes id
end
````

After running `rake ts:rebuild` - I can `Animal.search(1)` (or any other ID) and results return fine.
But, **when I update any of the records, from that point, they fail to return till I re-index**

Here's an example from console:

````ruby
Loading development environment (Rails 3.2.21)
1.9.3-p551 :001 > Animal.search 1
 => [#<Animal id: 1, name: "Cat", created_at: nil, updated_at: "2015-03-01 19:48:32">]
1.9.3-p551 :002 > Animal.find(1).update_attribute :name, 'Dog'
 => true
1.9.3-p551 :003 > Animal.search 1
 => []
````

In this example, I'd expect to still be able to search for the record by ID, even if the name had been changed. Are my expectations wrong or is there an issue here?

(By querying Sphinx by connecting via mysql, `mysql -h 127.0.0.1 -uroot --port 9306` - I'm seeing the `animal_core` contain all records, and the `animal_delta` contain no records - which I'd expect as they have all been updated outside of the delta threshold that I have set. After making a change to one of the records, as shown in the example above - `sphinx_deleted` is showing as `1` for the record, and `animal_delta` remains empty. Should I be expecting to see the record there?)

Hoping you can help here!

**Comment by pat** [comment]
With DateTime deltas, you still need a rake task to be run regularly (as often as your threshold) - that task is `rake ts:in:delta`.

If you want more immediate updates, then a queue-backed delta (Sidekiq, Resque, Delayed Job) is worth looking into, or real-time indices which avoid the need for deltas completely.

**Comment by mrjamesriley** [comment]
Thanks for the response Pat. I understand the need to delta index - the issue I'm seeing is that the second a record is updated, it no longer appears in search till the next time I index.

For example, say I have run a delta threshold of 30 minutes, and run a delta index every 5 minutes.
If I update a record, then it immediately disappears from the search results, till I next index.

This means, even if the delta indexing occurred every minute, it would still mean records are constantly disappearing from search results, for up to a minute at a time. **Importantly, it only seems to be an issue for items that were updated at a time in the past, outside of the delta threshold**.

Here's what sequence I'm seeing, using the same example of a 30minute delta threshold, with delta indexing occurring every 5 minutes:
1. I have a record that was updated 24 hours ago
2. I update this record - it immediately stops appearing in search results
3. At the time of the next delta index, the item reappears in search results
4. Now, as the records `updated_at` is now within its 30 minute threshold, it seems to now exist in the delta index, and thus further updates to the record do not cause it to drop out of search.

From what I'm seeing, it seems as though an item which was last updated 24 hours ago - does not appear within the `delta` index, and so when it gets updated - it's set as `sphinx_deleted = 1` in `core` index. So when a search takes place, it is filtered out by Thinking Sphinx, as its marked as deleted. The difference is, once it's delta indexed - then it now also lives in the `delta` index (because it fell within the delta threshold), and so further updates will not cause it to drop out of search - that is, until the threshold time passes and it's no longer in the delta index and so the issue returns. 

Should I not be expecting to be able to find a record by it's ID, even if it's been updated before the next delta index? If the record had it's name attribute changed for example, I understand that it'd need to be indexed for me to now search by its new name. But id, or other attributes that have not changed, should surely still yield the updated item in its result?

This issue appears to be new, as of Thinking Sphinx v3, as I believe I was not experiencing this on v2. Hope that clarifies the issue and thanks again for your time.

**Comment by pat** [comment]
Ah, thanks for your patient understanding and detail James - I misunderstood the problem.

I've just pushed a fix for this - if you can give the master branch a spin and confirm it now works well for you, then I'll get a new gem release out.

**Comment by mrjamesriley** [comment]
That appears to work a treat! You rock Pat - thank you for being so prompt.
Looking forward to seeing it published =)

**Comment by pat** [comment]
2.0.2 is now released :)

**Comment by mrjamesriley** [comment]
Thank you!
