### ISSUE TITLE
Setting database_adapter

### ISSUE THREAD

**Issue by exAspArk** [pat/thinking-sphinx#904]
Hi,

As far as I understand, the code from [documentation](http://pat.github.io/thinking-sphinx/common_issues.html#other_adapters) doesn't work with current version of `ThinkingSphinx`  as here is no method called `database_adapter`. I am trying to use [Octopus](https://github.com/tchandy/octopus) gem (#131).

Currently I have to patch TS like this:
```ruby
module ThinkingSphinx::ActiveRecord::DatabaseAdapters
  class << self
    def adapter_type_for(model)
      class_name = model.connection.class.name
      case class_name.split('::').last
      when 'MysqlAdapter', 'Mysql2Adapter'
        :mysql
      when 'PostgreSQLAdapter'
        :postgresql
      when 'JdbcAdapter'
        adapter_type_for_jdbc(model)
      when 'Proxy'
        :mysql
      else
        class_name
      end
    end
  end
end
```

Is there any other proper and more extendable way to do it? 

Thanks!

**Comment by pat** [comment]
There is indeed - it's noted in the documentation a bit further down in that section:

```ruby
ThinkingSphinx::ActiveRecord::DatabaseAdapters.default =
  ThinkingSphinx::ActiveRecord::DatabaseAdapters::MySQLAdapter
```

The order in the docs should probably be reversed, given TS v3 has been around for a good while now.

**Comment by exAspArk** [comment]
@pat got it! Thanks a lot. 
Closing the issue
