### ISSUE TITLE
Customising the wildcard token

### ISSUE THREAD

**Issue by airblade** [pat/thinking-sphinx#905]
Hi Pat,

I've been looking at the [wildcard](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/wildcard.rb) code, trying to decide the best way to stop hyphenated words being treated as multiple words.  I can't quite follow the `extended_pattern` so I'm not entirely sure of the best approach.

I'd like `ab-cd-ef` to be wildcarded as `*ab-cd-ef*` instead of `*ab*-*cd*-*ef*`.  Would you recommend something like `Regexp.union(/\p{Word}+/, '-')` as a pattern?  It looks sketchy to me but I can't quite put my finger on why...

**Comment by pat** [comment]
I think what you're after is `/[\p{Word}-]+/`, perhaps?

**Comment by airblade** [comment]
So simple and it works – thanks!

For some reason I didn't think one could use a character property like `\p{Word}` inside a `[]`character class...

Thanks, Pat.

**Comment by airblade** [comment]
I subsequently noticed #251 and #844 and think I may need to add the hyphen to my `charset_table` too.

**Comment by pat** [comment]
Yup, probably necessary :)
