### ISSUE TITLE
ThinkingSphinx::SphinxError: no enabled local indexes to search

### ISSUE THREAD

**Issue by MaicolBen** [pat/thinking-sphinx#910]
Shows this error on Mac OS X (not in Linux). When run `rake ts:rebuild` logs:

    Stopped searchd daemon (pid: 16342).
    ....

    using config file '...../config/development.sphinx.conf'...
    WARNING: 25 more warnings skipped.
    indexing index 'campaign_core'...
    ERROR: index 'campaign_core': id is not a valid attribute name.
    total 0 docs, 0 bytes
    total 0.007 sec, 0 bytes/sec, 0.00 docs/sec
    indexing index 'campaign_delta'...

Has the 'is not a valid attribute name' problem relation with 'no enabled local indexes to search' ?

Thanks

**Comment by pat** [comment]
Yeah, you can't name an attribute or field `id`, as it conflicts with Sphinx's own document ids. Best to give that attribute an alias using the `:as` option: `has id, :as => :campaign_id` - but also, Thinking Sphinx already has an aliased version of the indexed model's primary key available for you - `sphinx_internal_id` - so just use that in any filtering/sorting/grouping instead :)

**Comment by MaicolBen** [comment]
Thanks a lot, after hours searching and researching, it's the solution! Do you like that change the name of the issue to 'id is not a valid attribute name' for others who has the same problem?

**Comment by pat** [comment]
Good idea. Just changed the title, and great to know it's now working for you - sorry it took hours for the solution to be found!

**Comment by j3ck** [comment]
Hello. I have such a problem on the mac os, but on the ubuntu is all right even with the id, whether it may be due to version gem or thinking sphinx?

**Comment by pat** [comment]
Hi @j3ck - what versions of Thinking Sphinx, Rails and Sphinx are you using? And in particular, are you using different versions of Sphinx on the different machines?

**Comment by j3ck** [comment]
@pat 
**mac:**
thinking-sphinx (3.1.4)

rails 4.2.4

Sphinx 2.2.10-id64-release (2c212e0)

**ubuntu:**
thinking-sphinx (3.1.4)

rails 4.2.4

Sphinx 2.0.4-id64-release (r3135)

**Comment by pat** [comment]
@j3ck yeah, you're using a _really_ old version of Sphinx on your Ubuntu server (exactly four years old today!) - upgrading is recommended.

If you're seeing this problem using the latest Sphinx release on your mac, then I guess Sphinx has become fussier and smarter over the last few years. Certainly, if you have a field or attribute named `id`, I'd recommend changing it to avoid the conflict even if Sphinx didn't complain.

**Comment by j3ck** [comment]
@pat Thank you very much !
