### ISSUE TITLE
Config via capistrano

### ISSUE THREAD

**Issue by blackjid** [pat/thinking-sphinx#911]
hi!, 

Is there any way to set some configuration variables, like the ones you set in in `config/thinkinx_sphinx.yml` but in the capistrano deploy.rb??? something like:

```ruby
    set :pid_file,            -> { "#{shared_path}/tmp/pids/searchd.pid" }
    set :indices_location,    -> { "#{shared_path}/db/sphinx" }
    set :configuration_file,  -> { "#{shared_path}/config/sphinx.conf" }
    set :binlog_path,         -> { "#{shared_path}/sphinx_binlog" }
    set :log,                 -> { "#{shared_path}/log/searchd.log" }
    set :query_log,           -> { "#{shared_path}/log/searchd.query.log" }
```

**Comment by pat** [comment]
These settings all belong in `config/thinking_sphinx.yml` under the appropriate environment - is there a reason why you don't want to do that?

**Comment by blackjid** [comment]
I wanted to have some defaults at capistrano level.

I'm creating this file with a [capistrano gem](https://github.com/platanus/negroku/blob/master/lib/negroku/tasks/thinking_sphinx.rake) with sphinx so anyone that use that gem will have some convention defaults without the need of adding the file explicitly. Thats the way extensions for capistrano like [capistrano3-unicorn](https://github.com/tablexi/capistrano3-unicorn) and [capistrano3-nginx](http://github.com/platanus/capistrano3-nginx) works...

I finally implement this configuration on my gem, I think is enough... :)
thanks anyway
