### ISSUE TITLE
Add ts-activejob-delta

### ISSUE THREAD

**Issue by philipgiuliani** [pat/thinking-sphinx#913]
Currently we have `ts-delayed-delta` for delayed_job and `ts-sidekiq-delta` for sidekiq.

It would be cool to add a `ts-activejob-delta` for ActiveJob, so it would support a lot of other queuing systems out of the box!

**Comment by pat** [comment]
It would indeed be cool! Would you like to build it? ;)

Seriously, if you or anyone else wants to take a stab at it, using ts-sidekiq-delta as a template is not a bad place to start. I can tackle it at some point, but I've got a backlog of other things to do as well, so if it's left to me, it won't be done any time soon.

**Comment by pat** [comment]
As part of some tidying up of my open source repos, I'm going to close this issue - I'm still open to someone creating `ts-activejob-deltas`, but given it's not a feature that I've had others requesting, I'm not going to spend the time on it myself (I'm already too good at adding extra open source maintenance into my life).

So yes: if you need it, please build it! :)

**Comment by bikeath1337** [comment]
@pat I'd like to give a shot at the ActiveJob adapter for deltas. Do you still recommend basing it off of the Sidekiq implementation? If so, are unique jobs still a requirement in the latest release of thinking sphinx?

**Comment by pat** [comment]
Hi @bikeath1337 - yes, ts-sidekiq-delta remains the best reference at this point for a place to start.

Unique jobs are ideal, but I guess not essential - Thinking Sphinx does have its own approach to avoid processing the same delta index concurrently. And I'm guessing unique jobs becomes wrapped up in the underlying queue library's own approach, so maybe for ActiveJob it's just not an option? (I'm still yet to use ActiveJob, so I'm not sure.)

**Comment by bikeath1337** [comment]
Hi, @pat, I decided to implement this in our app and then pull the code out into a gem later. I finally got it all working nicely using serial execution of the delta index backed by https://github.com/cfis/activejob-locking. It's going through some testing on staging but looks pretty good. FWIW, we're a Rails 5.2 app, use FlyingSphinx on Heroku with docker containers.

Stay tuned for that gem.

**Comment by pat** [comment]
Great to hear it's coming along nicely :)
