### ISSUE TITLE
Some delta index queries running even if suspended

### ISSUE THREAD

**Issue by hooverlunch** [pat/thinking-sphinx#914]
In my spec support I have

```
  config.around(:each, no_sphinx: true) do |example|
    ThinkingSphinx::Deltas.suspend(:answers) do
      example.run
    end
  end
```

But in my test log, I'm still getting this:

```
Sphinx  Retrying query "UPDATE answer_core
SET sphinx_deleted = 1
WHERE id IN (3)
" after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - UPDATE answer_core
SET sphinx_deleted = 1
WHERE id IN (3)
```

I know I could spin up Sphinx to avoid this error, but the test doesn't need Sphinx so I don't want to spin it up for performance reasons.

Thoughts?

**Comment by pat** [comment]
Given it's been almost a week (sorry), perhaps you've figured this out - but I think the issue here is that the argument for `suspend` should be singular, like in the index definition. Thus: `ThinkingSphinx::Deltas.suspend(:answer)`.

If that doesn't make things work, let me know.

**Comment by hooverlunch** [comment]
Oh wow! I'll try that. Thanks.
