### ISSUE TITLE
Possible to set min_infix_len for specific indices? 

### ISSUE THREAD

**Issue by ngottlieb** [pat/thinking-sphinx#916]
And min_prefix_len. Seems like it's possible from the sphinx side but that TS doesn't support it in generating the sphinx.conf file. I.e. the only place to set it is in thinking_sphinx.yml which sets it for all indices. 

Is there a reason to not have that functionality? If not, I will look into submitting a PR to support it, but I figured I would ask before I gave it a try.

**Comment by ngottlieb** [comment]
Ah, sorry, I found the syntax for it here (I had tried a couple guesses and had not succeeded):

https://github.com/pat/thinking-sphinx/blob/6e7e0fd072ec73c840862d5ded089773818dc190/spec/internal/app/indices/article_index.rb

Something to think about -- set_property is not shown in any examples or documentation.

**Comment by pat** [comment]
Fair point, just added this to the docs: http://pat.github.io/thinking-sphinx/indexing.html#options
