### ISSUE TITLE
Question: Delta Indices and Testing

### ISSUE THREAD

**Issue by ngottlieb** [pat/thinking-sphinx#918]
In our application, I had rspec set up almost exactly the way you describe in the documentation and it was working well -- without delta indexing. But I turned on deltas for one index and now the specs for that index hang -- I've done some investigation and it's because the `index_finished?` method never seems to return true. Checking why, it's because this file, `db/sphinx/test/ts-event_instance_delta.tmp` never goes away. I'm not sure why -- delta indices are working fine in practice, it just seems to be hanging in the test environment. 

Is there any extra configuration needed to make it work with deltas in the test environment?

**Comment by pat** [comment]
Which version of TS are you using? Also: try deleting that file, then running the tests, and see if they keep hanging...

**Comment by ngottlieb** [comment]
Doh! Deleting the file solved it. Thanks!

**Comment by pat** [comment]
Sometimes those files get stuck, and so further updates fail. I'm pretty sure the TS code has improved in recent releases to avoid such situations (it'll try to delete the file even when an exception's raised), so best to use the latest if possible :)

**Comment by ngottlieb** [comment]
Sounds good, thanks!

**Comment by corinnekunze** [comment]
Thanks all for writing this, I was running into the same issue. It might be helpful to mention in the README that you should check that you have no leftover tmp files in your DIR that will cause your sphinx specs to hang indefinitely.

**Comment by pat** [comment]
Appreciate the comment @corinnekunze - and for everyone who's been hit by this issue, I've made the following changes lately:

* Added details of the guard files to the documentation - both in [the rake tasks section](https://freelancing-gods.com/thinking-sphinx/rake_tasks.html#index-guard-files) and [the common issues section](https://freelancing-gods.com/thinking-sphinx/common_issues.html#ignored-indices).
* Made sure guard files are removed as part of a rebuild (9c91644d2c309a16017882820576fb94107dcf71).
* Add a warning about any present guard files when running a full index (5784551c3b619b5930a928924706457394f6c7c6).
