### ISSUE TITLE
Proximity Operator Highlighting Numbers

### ISSUE THREAD

**Issue by nartz** [pat/thinking-sphinx#921]
Thinking Sphinx 3.1.3

When i query for something using the proximity search operator (i.e. the tilde with a number), with a raw query like:

"my eyes"~4 | "my eye"~5

The problem is that the numbers 4 and 5, which are NOT part of the search terms, are actually being 'highlighted' by the following CALL SNIPPETS call. Inotherwords, I'm trying to do a proximity search for the words in quotes, but for some reason sphinx is also highlighting the 'metadata' of the search, i.e. the literal number 4 and 5!

I'm not sure if this is a ruby ThinkingSphinx thing or the fault of the SphinxAPI it self.

Here's what a typical call would look like:

CALL SNIPPETS('...some text....', 'post_core', '\"my eyes\"~4 | \"my eye\"~5', '<span class=\"match\">' AS before_match, '</span>' AS after_match, ' &#8230; ' AS chunk_separator, 300 AS around)

**Comment by pat** [comment]
The default behaviour for TS is to just take the query and send it through to the SNIPPETS statement... in your case, that's certainly not ideal, so you'll want to set something up that's a little bit more manual but accurate:

```ruby
excerpter = ThinkingSphinx::Excerpter.new 'post_core', '"my eyes" "my eye"',
  :before_match    => '',
  :after_match     => '',
  :chunk_separator => ' ... ',
  :around           => 300
excerpter.excerpt! '... some text ...'
```

Wrap that into a helper or two, with the excerpter object memoised to avoid creating it again and again, and it should do the trick. I guess you'll want to gsub your query to remove ~\d+ from it, if that's all through user input?
