### ISSUE TITLE
Custom config file location

### ISSUE THREAD

**Issue by kalkov** [pat/thinking-sphinx#925]
Hi, we want to set a custom location for the configuration. Currently we are using version 2, with a config file inside `config/sphinx.yml` .

We want to have config files like: 

```
config/settings/settings.development.yml
config/settings/settings.production.yml
```
with a `thinking_sphinx` keys inside. 

Any suggestions how to accomplish that?

**Comment by pat** [comment]
Well, `config/sphinx.yml` gets parsed as YAML, so I guess you could work around it using that? I don't think there's an easier way, I'm afraid - certainly not with v2.

**Comment by kalkov** [comment]
Is there easier way with v3?

**Comment by pat** [comment]
Hmm, just reviewing that code, I'm afraid there's not a better way there either. While `ThinkingSphinx::Configuration.instance.settings` has all the settings, that singleton instance makes use of settings when it initialises, so you can't create it and then populate it and expect _all_ settings to be used appropriately (only some are set dynamically).

**Comment by skanev** [comment]
Would you be interested in a pull request that allows for that? If so, can you give some pointers? :smile:

**Comment by pat** [comment]
Just pushed commit cd60a4253b0aad9b212a1d3366cce2c92a6e781d to the `develop` branch for v3 that should help. The process would be having something along these lines in an initializer:

```ruby
input = File.read Rails.root.join('config', 'settings', "settings.#{Rails.env}.yml")
yaml  = YAML.load input

ThinkingSphinx::Configuration.instance.settings.merge! yaml['thinking_sphinx']
ThinkingSphinx::Configuration.instance.setup
```

Of course, if you're upgrading from V2 to V3, read this:
http://freelancing-gods.com/thinking-sphinx/upgrading.html
And the release notes for the more recent releases as well:
https://github.com/pat/thinking-sphinx#upgrading

**Comment by skanev** [comment]
Thanks! :)

**Comment by kalkov** [comment]
Thanks Pat!

**Comment by the-teacher** [comment]
**/config/initializers/thinking_sphinx.rb**

I concentrated all my configs for development into `config/DEV_ENV`

There is recipe for TS

```ruby
if Rails.env.development?
  class ThinkingSphinx::Configuration
    private

    def settings_file
      framework_root.join 'config', 'DEV_ENV', 'thinking_sphinx.yml'
    end
  end
end
```
