### ISSUE TITLE
rake ts:rebuild alternative

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#928]
Hi,

Running this command causes the server to throw a 500 error if any requests come in during the time that the index is rebuilding.  Is there a solution for this?

Adam

**Comment by pat** [comment]
Ergh, I really should have replied sooner, sorry.

`ts:rebuild` should be considered the equivalent of `db:migrate` - sometimes you may have significant database changes which temporarily break your site. In these situations, you'd perhaps put your site into maintenance mode. It's the same for `ts:rebuild`: if you've changed your Sphinx structure, then best to put your site into maintenance mode or similar while running this task.

And perhaps you're across this already, but it's something I see people occasionally getting confused about: you *only* need to run `ts:rebuild` when you change your Sphinx structure (add an index, remove an index, change the configuration of an index). It's not a task you'll want to have running every day/hour. To just update the data in your Sphinx indices, use `ts:index`, which will not restart the daemon. It's the task that should be run regularly.
