### ISSUE TITLE
Revelance keyword order problem

### ISSUE THREAD

**Issue by itshakeel23** [pat/thinking-sphinx#930]
I am using thinking sphinx (3.1.4) and facing the ordering problem. 
e.g these are the list of keywords in my database:

- advanced american mining company quot quot
- american securities
- american united telecommunication
- al american contracting
- american bank
.... .... ... etc

when i search for keyword "american" it should return the result in this order:

- american bank
- american securities
- american united telecommunication
- al american contracting
- advanced american mining company quot quot

but this is what i am getting:

- advanced american mining company quot quot
- american securities
- american united telecommunication
- al american contracting
- american bank

Query: Company.search "american*", :limit => 5
Index:

ThinkingSphinx::Index.define :company, :with => :active_record do
  indexes name, :sortable => true
  has :count, :sortable => true
  set_property :min_prefix_len => 1
  set_property :enable_star => true
end

how can i order by relevance keyword or best match?

**Comment by pat** [comment]
Just to be clear, Sphinx sorts by relevance by default, but the default ranking mode doesn't seem to be returning results in an order you like. You could try using [a different ranking mode](http://sphinxsearch.com/docs/current.html#builtin-rankers) - maybe SPH04 would be better?

```ruby
Company.search "american*", :limit => 5, :ranker => :sph04
```
