### ISSUE TITLE
no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by kinaan-khan-confiz** [pat/thinking-sphinx#933]
Hi Pat,

I was previously using thinking sphinx version 2.1.0 and I was caching the `ThinkingSphinx::Search` Object but few days back I upgraded to thinking sphinx 3.1.4 and same code part has started to give me this exception.

````ruby
TypeError - no _dump_data is defined for class Proc:
  activesupport (3.2.19) lib/active_support/cache.rb:561:in `initialize'
  activesupport (3.2.19) lib/active_support/cache.rb:363:in `block in write'
  activesupport (3.2.19) lib/active_support/cache.rb:520:in `instrument'
  activesupport (3.2.19) lib/active_support/cache.rb:362:in `write'
  activesupport (3.2.19) lib/active_support/cache.rb:299:in `fetch'
  app/controllers/used_cars_controller.rb:180:in `search'
```

I reverted back to my old commits to verify if any other change might have produced this exception but reverting back to 2.1.0 , the code started to work again. 

I tried the following code in console on both version 

```ruby
Marshal.dump ThinkingSphinx.search('honda')
```

with TS 3.1.4 it gives the same error

Any help ? 

Thanks in advance

**Comment by kinaan-khan-confiz** [comment]
is there anything that we can do to resolve this issue ?

**Comment by pat** [comment]
I tried investigating this the other week - but Marshal doesn't make it easy to find the Proc that's causing the error. I certainly want to figure it out, though… but life is a little busy right now, so I'm not sure when I can get it sorted.

**Comment by pat** [comment]
Okay, so I think I may have something that works: 2aa5b850b2fc0f62934921675f340bc3cae991ef

If you want to try it in your Gemfile:

```ruby
gem 'thinking-sphinx',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '2aa5b850b2'
```
