### ISSUE TITLE
weird search result

### ISSUE THREAD

**Issue by casiodk** [pat/thinking-sphinx#935]
given a customer

```
Customer.create(address_street_name: "Bjælkevej", address_street_number: "44", rec_id: "kj3")
```

I get these seacrh results
```
Customer.search "jælkevej", star: true, ranker: :bm25, with: { deleted_at: 0 }, page: 1, per_page: 15
  Sphinx Query (0.6ms)  SELECT * FROM `customer_core`, `customer_delta` WHERE MATCH('*jælkevej*') AND `deleted_at` = 0 AND `sphinx_deleted` = 0 LIMIT 0, 15 OPTION ranker=bm25
  Sphinx  Found 0 results
```
```
Customer.search "ælkevej", star: true, ranker: :bm25, with: { deleted_at: 0 }, page: 1, per_page: 15
  Sphinx Query (0.6ms)  SELECT * FROM `customer_core`, `customer_delta` WHERE MATCH('*ælkevej*') AND `deleted_at` = 0 AND `sphinx_deleted` = 0 LIMIT 0, 15 OPTION ranker=bm25
  Sphinx  Found 1 results
  Customer Load (0.4ms)  SELECT "customers".* FROM "customers" WHERE "customers"."id" = 2
 => [#<Customer id: 2, address_city_name: nil, address_country_name: nil, name: nil, name_alias: nil, phone: nil, rec_id: "kj3", address_street_name: "Bjælkevej", address_street_number: "44", address_zip_code: nil, created_at: "2015-08-08 16:03:58", updated_at: "2015-08-08 16:03:58", address_additional_info: nil, street: nil, delta: true, imported_at: "2015-08-08 16:03:58", deleted_at: nil, email: nil>]
```

THIS IS MY INDEX
```
# -*- encoding : utf-8 -*-
ThinkingSphinx::Index.define :customer, :with => :active_record, :delta => ThinkingSphinx::Deltas::DelayedDelta do
  indexes name, as: :customer_name, infixes: true, sortable: true
  indexes name_alias, as: :customer_name_alias, infixes: true, sortable: true
  indexes [address_street_name, address_street_number, address_additional_info, address_zip_code, address_city_name, address_country_name, street], as: :customer_address, infixes: true, sortable: true
  indexes rec_id, as: :customer_rec_id, infixes: true, sortable: true
  has deleted_at
  set_property :enable_star => true
  set_property :min_infix_len => 1
  set_property :html_strip => true
  set_property :charset_type => "utf-8"
end
```

**Comment by pat** [comment]
I'm not really sure why this is happening… which versions of Thinking Sphinx and Sphinx are you using? And what settings do you have for this environment in `config/thinking_sphinx.yml`?

**Comment by casiodk** [comment]
Yes very strange. It works on circleci , but not in development, so i guess
its my local version of sphinx?

VERSION
sphinx: stable 2.2.9 (bottled), devel 2.3.1-beta, HEAD

YML
development:
  mysql41: 9312
  enable_star: true
  min_infix_len: 3

FAILING TEST
context "GET index", focus: true do
    let!(:customer_a) { create(:customer, address_city_name: "København",
address_country_name: "Danmark", name: "Kjeld Fanøgræs", name_alias:
"Kikært", phone: "123456", rec_id: "777777777", address_street_name:
"Bjælkevej", address_street_number: "44", address_zip_code: "1234",
address_additional_info: "4 th v", street: "Bjælkevej 34, 4 th v" )}
    let!(:customer_deleted) { create(:customer, address_city_name:
"København", address_country_name: "Danmark", name: "Kjeld Fanøgræs",
name_alias: "Kikært", phone: "123456", rec_id: "77777777743",
address_street_name: "Bjælkevej", address_street_number: "44",
address_zip_code: "1234", address_additional_info: "4 th v", street:
"Bjælkevej 34, 4 th v" )}
    let!(:customer_b) { create(:customer, address_city_name: "Odense",
address_country_name: "Danmark", name: "Bingo børge", name_alias: "bimmer",
phone: "987987", rec_id: "76487648", address_street_name: "skistien",
address_street_number: "2", address_zip_code: "5000",
address_additional_info: "", street: "Skistien 2" )}

    before :each do
      customer_deleted.destroy
      index_sphinx
    end

    [
      { attribute: :name, q: "anøg" },
      { attribute: :address_city_name, q: "nha" },
      { attribute: :name_alias, q: "ikær" },
      { attribute: :rec_id, q: "777777777" },
      { attribute: :address_street_name, q: "jælk + 44" }
    ].each do |h|
      it "should be able to search on customers.#{ h[:attribute] }" do
        authorize_request

        get :index, { q: h[:q], format: :json }

        expect(assigns(:customers)).to include(customer_a)
        expect(assigns(:customers)).to_not include(customer_deleted)
        expect(assigns(:customers)).to_not include(customer_b)
      end
    end
  end

WORKING TEST
context "GET index", focus: true do
    let!(:customer_a) { create(:customer, address_city_name: "København",
address_country_name: "Danmark", name: "Kjeld Fanøgræs", name_alias:
"Kikært", phone: "123456", rec_id: "777777777", address_street_name:
"Bjælkevej", address_street_number: "44", address_zip_code: "1234",
address_additional_info: "4 th v", street: "Bjælkevej 34, 4 th v" )}
    let!(:customer_deleted) { create(:customer, address_city_name:
"København", address_country_name: "Danmark", name: "Kjeld Fanøgræs",
name_alias: "Kikært", phone: "123456", rec_id: "77777777743",
address_street_name: "Bjælkevej", address_street_number: "44",
address_zip_code: "1234", address_additional_info: "4 th v", street:
"Bjælkevej 34, 4 th v" )}
    let!(:customer_b) { create(:customer, address_city_name: "Odense",
address_country_name: "Danmark", name: "Bingo børge", name_alias: "bimmer",
phone: "987987", rec_id: "76487648", address_street_name: "skistien",
address_street_number: "2", address_zip_code: "5000",
address_additional_info: "", street: "Skistien 2" )}

    before :each do
      customer_deleted.destroy
      index_sphinx
    end

    [
      { attribute: :name, q: "anøg" },
      { attribute: :address_city_name, q: "nha" },
      { attribute: :name_alias, q: "ikær" },
      { attribute: :rec_id, q: "777777777" },
      { attribute: :address_street_name, q: "ælk + 44" }
    ].each do |h|
      it "should be able to search on customers.#{ h[:attribute] }" do
        authorize_request

        get :index, { q: h[:q], format: :json }

        expect(assigns(:customers)).to include(customer_a)
        expect(assigns(:customers)).to_not include(customer_deleted)
        expect(assigns(:customers)).to_not include(customer_b)
      end
    end
  end


INDICES
# -*- encoding : utf-8 -*-
ThinkingSphinx::Index.define :customer, :with => :active_record, :delta =>
ThinkingSphinx::Deltas::DelayedDelta do
  indexes name, as: :customer_name, infixes: true, sortable: true
  indexes name_alias, as: :customer_name_alias, infixes: true, sortable:
true
  indexes [address_street_name, address_street_number,
address_additional_info, address_zip_code, address_city_name,
address_country_name, street], as: :customer_address, infixes: true,
sortable: true
  indexes rec_id, as: :customer_rec_id, infixes: true, sortable: true
  has deleted_at
  set_property :enable_star => true
  set_property :min_infix_len => 1
  set_property :html_strip => true
  set_property :charset_type => "utf-8"
end


GEM LIST
actionmailer (4.2.0)
actionpack (4.2.0)
actionview (4.2.0)
activejob (4.2.0)
activemodel (4.2.0)
activerecord (4.2.0)
activesupport (4.2.0)
acts_as_list (0.6.0)
addressable (2.3.7)
afm (0.2.2)
akami (1.2.2)
amoeba (3.0.0)
ancestry (2.1.0)
apipie-rails (0.3.1)
arel (6.0.0)
Ascii85 (1.0.2)
ast (2.0.0)
astrolabe (1.3.0)
bcrypt-ruby (3.1.2)
bitmask_attributes (1.0.0)
brakeman (3.0.1)
builder (3.2.2)
bullet (4.14.4)
bundler (1.7.6)
cancancan (1.10.1)
carrierwave (0.10.0)
CFPropertyList (2.3.0)
dalli (2.7.4)
database_cleaner (1.3.0)
delayed_job (4.0.6)
delayed_job_active_record (4.0.3)
delayed_job_web (1.2.10)
diff-lcs (1.2.5)
erubis (2.7.0)
excon (0.44.2)
factory_girl (4.5.0)
factory_girl_rails (4.5.0)
fakeweb (1.3.0)
faraday (0.9.1)
fastercsv (1.5.5)
figaro (1.1.0)
fission (0.5.0)
flying-sphinx (1.2.0)
fog (1.27.0)
fog-atmos (0.1.0)
fog-aws (0.1.0)
fog-brightbox (0.7.1)
fog-core (1.28.0)
fog-ecloud (0.0.2)
fog-json (1.0.0)
fog-profitbricks (0.0.1)
fog-radosgw (0.0.3)
fog-riakcs (0.1.0)
fog-sakuracloud (1.0.0)
fog-serverlove (0.1.1)
fog-softlayer (0.4.1)
fog-storm_on_demand (0.1.0)
fog-terremark (0.0.4)
fog-vmfusion (0.0.1)
fog-voxel (0.0.2)
fog-xml (0.1.1)
formatador (0.2.5)
geocoder (1.2.7)
globalid (0.3.3)
gyoku (1.2.2)
haml (4.0.6)
hashery (2.1.1)
highline (1.6.21)
hike (1.2.3)
httpi (2.3.0)
i18n (0.7.0)
inflecto (0.0.2)
innertube (1.1.0)
ipaddress (0.8.0)
jbuilder (2.2.7)
joiner (0.3.4)
json (1.8.2)
kaminari (0.16.1)
kgio (2.9.3)
launchy (2.4.3)
letter_opener (1.3.0)
loofah (2.0.1)
macaddr (1.7.1)
mail (2.6.3)
middleware (0.1.0)
mime-types (1.25.1)
mini_magick (4.1.0)
mini_portile (0.6.2)
minitest (5.5.1)
monetize (1.1.0)
money (6.5.1)
money-rails (1.4.1)
multi_json (1.10.1)
multipart-post (2.0.0)
mysql2 (0.3.18)
net-scp (1.2.1)
net-ssh (2.9.2)
nokogiri (1.6.6.2)
nori (2.4.0)
paranoia (2.1.0)
parser (2.2.0.3)
pdf-core (0.5.1)
pdf-inspector (1.2.0)
pdf-reader (1.3.3)
pg (0.18.1)
powerpack (0.1.0)
prawn (2.0.2)
prawn-table (0.2.1)
pusher-client (0.6.0)
rack (1.6.0)
rack-cors (0.3.1)
rack-protection (1.5.3)
rack-test (0.6.3)
rails (4.2.0)
rails-api (0.4.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
rails_12factor (0.0.3)
rails_serve_static_assets (0.0.4)
rails_stdout_logging (0.0.3)
railties (4.2.0)
rainbow (2.0.0)
raindrops (0.13.0)
rake (10.4.2)
riddle (1.5.11)
rspec-core (3.2.0)
rspec-expectations (3.2.0)
rspec-mocks (3.2.0)
rspec-rails (3.2.0)
rspec-support (3.2.1)
rubocop (0.29.1)
ruby-progressbar (1.7.1)
ruby-rc4 (0.1.5)
ruby2ruby (2.1.3)
ruby_parser (3.5.0)
rubyntlm (0.4.0)
sass (3.4.12)
savon (2.8.1)
sexp_processor (4.4.5)
simplecov (0.7.1)
simplecov-html (0.7.1)
sinatra (1.4.5)
sprockets (2.12.3)
sprockets-rails (2.2.4)
systemu (2.6.4)
terminal-table (1.4.5)
thinking-sphinx (3.1.3)
thor (0.19.1)
thread_safe (0.3.4)
tilt (1.4.1)
timecop (0.7.3)
ts-delayed-delta (2.0.2)
ttfunk (1.4.0)
tzinfo (1.2.2)
unicorn (4.8.3)
uniform_notifier (1.7.0)
uuid (2.3.7)
vcr (2.9.3)
wasabi (3.3.0)
websocket (1.2.1)

VH
*Nicolai Seerup*

*Soundtracktor ApS*
*Lead Developer - Ruby on Rails*

Danas Plads 17A
DK - 1905 Frb. C.

+45 3145 8035
ns@s <nicolai@music-in-motion.co.uk>oundtracktor.com

Follow Me
Twitter <http://www.twitter.com/soundtracktor>
Newsletter <https://soundtracktor.com/#social>

2015-08-09 1:43 GMT+02:00 Pat Allan <notifications@github.com>:

**Comment by pat** [comment]
The fact that it passes on CircleCI does suggest it's probably a difference between the two environments. Does it pass in the test environment on your machine, as opposed to development? Do you know what version of Sphinx is being used on CircleCI?

**Comment by casiodk** [comment]
Hi Pat, Im building a strictly JSON API and its not set up to run in
development env locally, only test env. But the test has passed previously,
but after an update of brew, ruby to 2.2.2 and sphinx to 2.2.9_1 it
suddenly failed

Circleci is using 2.0.4 https://circleci.com/docs/test-with-sphinx

Cheers /N

VH
*Nicolai Seerup*

*Soundtracktor ApS*
*Lead Developer - Ruby on Rails*

Danas Plads 17A
DK - 1905 Frb. C.

+45 3145 8035
ns@s <nicolai@music-in-motion.co.uk>oundtracktor.com

Follow Me
Twitter <http://www.twitter.com/soundtracktor>
Newsletter <https://soundtracktor.com/#social>

2015-08-10 19:16 GMT+02:00 Pat Allan <notifications@github.com>:

**Comment by pat** [comment]
When you upgraded Sphinx versions, do you know what you were on previously when it *did* work on your machine?

**Comment by casiodk** [comment]
No sorry, i didnt check. Its not a big problem, i can just downgrade to a
previous version, but I´m just thinking its an unexpected behaviour in this
new version that should be investigated...

VH
*Nicolai Seerup*

*Soundtracktor ApS*
*Lead Developer - Ruby on Rails*

Danas Plads 17A
DK - 1905 Frb. C.

+45 3145 8035
ns@s <nicolai@music-in-motion.co.uk>oundtracktor.com

Follow Me
Twitter <http://www.twitter.com/soundtracktor>
Newsletter <https://soundtracktor.com/#social>

2015-08-10 19:40 GMT+02:00 Pat Allan <notifications@github.com>:

**Comment by pat** [comment]
Indeed - it'd be good to know which version the issue started appearing. Perhaps it's worth downgrading to the latest 2.1.x Sphinx release first, see how that goes?

Also, there have been some changes to how Thinking Sphinx behaves when interacting with different versions of Sphinx - have you looked at the release notes for this? https://github.com/pat/thinking-sphinx/releases (particularly 3.0.6 and 3.1.0)
