### ISSUE TITLE
Handling has_many association through single index

### ISSUE THREAD

**Issue by mattecalcio** [pat/thinking-sphinx#938]
Hey Pat

I have the following models:

```
class User < ActiveRecord::Base
   has_many :locations
   ...
end
```
```
class Location < ActiveRecord::Base
   belongs_to :user
   ...
end
```

and the following index on `User`:

```
ThinkingSphinx::Index.define :user, name: :user, with: :active_record do
   indexes name, as: :user_name

   has 'RADIANS(location.latitude)', as: :lat, type: :float
   has 'RADIANS(location.longitude)', as: :lng, type: :float

   join locations
end
```

and this is how I search:

`User.search(geo: [lat, lng], with: {geodist: 0.0..10_000.0})`

After running `ts:rebuild` it seems as though only the first location of the user was indexed and Ideally I would like all locations to be available when searching to provide more accurate results.

Is there a way to alter the existing index to take into account the has_many association of user on locations?

I know I could create an index on `Location` and search using that but there are a lot of other attributes on the `User` index (omitted for simplicity since they rely on other `User` associations) that I would like to use for the search. Also creating an additional index would require a second search to retrieve the `User` from the `Location`.

**Comment by pat** [comment]
Hi Matteo

Sphinx has no concept of multiple lat/lng points for a given record, so what you're trying to do isn't possible. Instead, as you've suggested, I'd look into searching on Location instead, and pull in all the user fields/attributes into the location index.

To improve performance, I'd recommend grouping by user_id (to ensure only one location per user), and then use `:sql => {:include => :user}` as a search option, thus all the users will be loaded for locations in as few SQL queries as possible, saving the need for further SQL/Sphinx calls.

**Comment by mattecalcio** [comment]
Yeah that's what I thought also but I was hoping you would prove me wrong. Thanks for the quick reply, I appreciate the help. :+1:

**Comment by pat** [comment]
No worries :)
