### ISSUE TITLE
Wild grouping with TS

### ISSUE THREAD

**Issue by kiote** [pat/thinking-sphinx#939]
Hi, @pat!

I've asked related question in [TS mailing list already](https://groups.google.com/forum/#!topic/thinking-sphinx/0tQjpKpE1DM), but here I'll be more concrete.

#### Environment

* Ruby 2.2.2
* Rails 4.2.2
* Postgres 9.3.6
* Sphinx 2.0.4
* Thinking Sphinx 3.1.3

#### Problem description

I have 3 tables: doctors, person_organizations and organizations. One record in the organization 
table could have GPS coordinates: latitude and longitude. One doctor could have 
many organizations connected trough person_organizations table.

My aim is to show "nearest doctors", so I have some user's coordinates pre-setted and want
to make geo-distance search by them.

But for those doctors, who connected to more than one organization I have for example one record 
in the index instead of several I expect to see there.

I've created TS index file like this:

```ruby
ThinkingSphinx::Index.define :doctor,
                             with: :active_record,
                             delta: ThinkingSphinx::Deltas::DelayedDelta do
  indexes [firstname, lastname], as: :name, sortable: true
  indexes organizations.name,    as: :practice_name
  
  # Filter by GPS-coordinates
  join organizations
  has "RADIANS(organizations.latitude)",  as: :lat,  type: :float
  has "RADIANS(organizations.longitude)", as: :lng,  type: :float

  # we need this group_by according to thinking sphinx doc
  # see http://freelancing-gods.com/thinking-sphinx/geosearching.html
  group_by 'organizations.latitude', 'organizations.longitude'
end
```

It gives me sql-query of a kind:

```sql
SELECT "people"."id" * 24 + 9 AS "id", 
  COALESCE(people."firstname", '') || ' ' || COALESCE(people."lastname", '') AS "name", 
  array_to_string(array_agg(DISTINCT organizations."name"), ' ') AS "practice_name",
  RADIANS(organizations.latitude) AS "lat", 
  RADIANS(organizations.longitude) AS "lng"
FROM "people" LEFT OUTER JOIN "person_organizations" ON "person_organizations"."person_id" = "people"."id" 
  LEFT OUTER JOIN "person_organizations" "person_organizations_people_join" ON "person_organizations_people_join"."person_id" = "people"."id" 
  LEFT OUTER JOIN "organizations" ON "organizations"."id" = "person_organizations_people_join"."organization_id" AND (person_organizations.active = 't') 
GROUP BY "people"."id", people."firstname", people."lastname", organizations.latitude, organizations.longitude;
```

Which gives me 2 rows as a result for doctor with 3 organization connected. 
Practice column name has actually two practices names.
Since 2 out of 3 of this organizations have the same address I think it's GROUP BY result:

```
   id   |    name     |        practice_name                |      lat         |        lng        
--------+-------------+----------------------------------+------------------+-------------------
 402345 | John Doe | Clinic name 2 Clinic name 3         | 1.06598537639786 | 0.186908243347223 
 402345 | John Doe | Clinic name 1                       | 1.06629175149475 | 0.192180017334188 
(2 rows)
```

Next, I'm trying to find the same doctor directly in Sphinx:

```
mysql> select practice_name, lat, lng from specialist_doctor_core, specialist_doctor_delta where match('John Doe');
+--------+--------+-------------------------+----------+----------+
| id     | weight | practice_name           | lat      | lng      |
+--------+--------+-------------------------+----------+----------+
| 402345 |   2675 | Clinic name 1           | 1.066292 | 0.192180 |
+--------+--------+-------------------------+----------+----------+
1 row in set (0.01 sec)
```

And tada! having only one result row. So question is why is that and how I should behave to have 2 or even 3 records in index instead.

**Comment by pat** [comment]
Sphinx expects unique document ids, which are based on the model's primary key (and may be exactly the same, if you're only indexing one model). Also, Sphinx can only have one lat/lng pair per record. So, you can't have multiple records representing the same doctor instance with different locations.

What I would recommend is instead having a Sphinx index on your PersonOrganization model - thus, you're guaranteed a single lat/lng pair, and you can have multiple results for doctors with multiple locations. This should give you the number of records you want.

**Comment by kiote** [comment]
Thanks, Pat! I completely forgot about this primary-key stuff. 
Do I have any option to make this key manually? 

Now it's creating with ```"people"."id" * 24 + 9 AS "id"``` as far as I get it. But what if I could add there joined organization's ID, then it could give me 3 records, right? And there won't be this duplication issue.

Cause with your suggestion (indexing PersonOrganization) I should completely rewrite application architecture, it's searching layer I mean, which does not sounds really inspiring :grin:

**Comment by pat** [comment]
Finding a way to combine both `people.id` and `organizations.id` and ensure uniqueness might be difficult - but also, it's not possible with Thinking Sphinx, so you'd be mucking around with the generated Sphinx configuration manually.

So, either path you take is going to be at least a little complex, but I'd highly recommend searching on PersonOrganization instead of Person/Doctor if you want one result per organization location.

**Comment by kiote** [comment]
Oh, cool. At least I have no doubts now. Thank you, Pat!
