### ISSUE TITLE
Non-ascii characters are not indexed in 3.1.4

### ISSUE THREAD

**Issue by rolkos** [pat/thinking-sphinx#940]
After upgrade from 3.1.0 to 3.1.4 non-ascii characters are not indexed (ÅåÄäÖö). Everything started to work fine after downgrade to 3.1.0.

**Comment by pat** [comment]
Which version of Sphinx are you using?

**Comment by rolkos** [comment]
On local machine (OS X):
Sphinx 2.1.8-release (rel21-r4675)
On server (Centos): 
Sphinx 2.0.8-id64-release (r3831)

**Comment by pat** [comment]
And you're seeing this issue in both environments?

**Comment by rolkos** [comment]
Yes on both and after I downgraded to previous 3.1.0 it and run ts:rebuild it just starded to work (on both environments.

**Comment by pat** [comment]
I believe you'll need to add the charset_type setting (or upgrade to Sphinx 2.2.x): https://github.com/pat/thinking-sphinx/releases/tag/v3.1.4

**Comment by rolkos** [comment]
Updating to sphinx 2.2.9 fixed the problem. But I had to leave `charset_table` as it was in sphinx 2.0.x and TS 3.1.0.  Correct me if I'm wrong but if Sphinx use utf-8, and my DB also use utf-8, shouldnt this work just like that wihout charset_table?

**Comment by pat** [comment]
Sphinx 2.2.x does not remove the need for `charset_table`, *only* `charset_type`. What this means is that Sphinx will now index UTF-8 characters as they are, but if you want some characters to be treated as identical as others (å as a), then that's where `charset_table` helps.
