### ISSUE TITLE
TS doesn't respect rank_mode and return different order from sphinxQL

### ISSUE THREAD

**Issue by terencelin** [pat/thinking-sphinx#941]
Hi Pat,

Got really weird case here.
When I do sphinxQL query, it returns the right order

sphinxQL> select weight(),* from flyer_item_core where match('fruit') OPTION ranker=sph04;
+----------+-----------+-------------------+
| weight() | id        |sphinx_internal_id |
+----------+-----------+-------------------+
|     6641 | 493673526 |          70524789 |
|     6641 | 505033945 |          72147706 |
|     4641 |  68599275 |           9799896 |
|     4641 |  68600311 |           9800044 |
|     4641 | 419234196 |          59890599 |

But when I use model.search, got different ordering (the first 2 was not returned).

irb(main):032:0> FlyerItem.search_for_ids 'fruit', :rank_mode => :sph04
  Sphinx Query (2.8ms)  fruit
  Sphinx  Found 54 results
=> [9799896, 9800044, 59890599, 59890693, 59890815, 63490510, 63490511, 63491200, 63491212, 63491257, 64329646, 64331014, 64332728, 64332762, 64332809, 64332859, 64332887, 70524784, 70524789, 72147252]

Could you help to think what might go wrong? 

Thank you,
Terence

**Comment by pat** [comment]
With TS v3, the option to use in your searching is `:ranker` - `:rank_mode` is for v1/v2: http://freelancing-gods.com/thinking-sphinx/searching.html#ranking

**Comment by terencelin** [comment]
ohh, I'm using thinking-sphinx-2.0.14.gem

**Comment by pat** [comment]
Oh really? But TS v2 doesn't use SphinxQL…

**Comment by pat** [comment]
Though I guess you can still enable the mysql41 protocol to use SphinxQL for testing, but it's worth nothing that behaviour *may* be different with the binary protocol…

**Comment by terencelin** [comment]
Another weird thing:

irb(main):047:0* FlyerItem.search_for_ids 'fruit', :rank_mode => :sph04, :order => "weight() DESC"
  Sphinx Query (2.8ms)  fruit
  Sphinx  Found 54 results
=> [9799896, 9800044, 59890599, 59890693, 59890815, 63490510, 63490511, 63491200, 63491212, 63491257, 64329646, 64331014, 64332728, 64332762, 64332809, 64332859, 64332887, 70524784, 70524789, 72147252]
irb(main):048:0> FlyerItem.search_for_ids 'fruit', :rank_mode => :sph04, :order => "weight() ASC"
  Sphinx Query (2.9ms)  fruit
  Sphinx  Found 54 results
=> [9799896, 9800044, 59890599, 59890693, 59890815, 63490510, 63490511, 63491200, 63491212, 63491257, 64329646, 64331014, 64332728, 64332762, 64332809, 64332859, 64332887, 70524784, 70524789, 72147252]

It's returning me the same order, ignoring the :order passed in.

**Comment by terencelin** [comment]
Thanks Pat, any suggestions on what should I do next to better verify?

P.S I've done reindex and restart searchd several times already.

**Comment by pat** [comment]
Which version of Sphinx are you using?

**Comment by terencelin** [comment]
backflipp@db1.backflipp.qa ~/app/current $ /usr/local/bin/indextool -v
Sphinx 2.1.4-id64-release (rel21-r4421)
Copyright (c) 2001-2013, Andrew Aksyonoff
Copyright (c) 2008-2013, Sphinx Technologies Inc (http://sphinxsearch.com)

**Comment by terencelin** [comment]
I saw other posts and added :match_mode => :extended like you suggested before, and it works now :)

Thanks Pat, I really love TS gem...:)

**Comment by pat** [comment]
Ah, great to know you figured it out! TS v2 is very old, and I forget how the binary syntax works… so it's a good thing you happened across the solution much faster than I would have!
