### ISSUE TITLE
Searching a table that uses UID

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [pat/thinking-sphinx#946]
Hello!

I'm using sphinxsearch to provide full text searching on my service. Everything was fine since I installed UID support. So my id column became a string, not integer auto-inc anymore.

When I run `rake ts:index` I've got this error:

ERROR: sql_query_range: min_id='495a384c-5136-11e5-b751-080027b5756c', max_id='8f37cc4e-5131-11e5-9522-080027b5756c': min_id must be less than max_id.

Have somebody experienced something similar?

**Comment by pat** [comment]
Sphinx (and thus Thinking Sphinx) requires integers for document ids, so using UIDs isn't an option, I'm afraid.

**Comment by raphaelduartepinheiro** [comment]
@pat thank you for your reply. 

Is there a prevision when this feature will be implemented? Or another full text search engine that supports it?

**Comment by pat** [comment]
I've no idea if the Sphinx team plan to support non-integer document ids - certainly, if they do, then I'll adapt Thinking Sphinx to do the same.

As for other full-text search options, I'm really not sure - I've not used anything but Sphinx (when I started Thinking Sphinx, Solr was very new and Elastic Search didn't exist). I hear Elastic Search has some great features (albeit with perhaps more complexity?), so perhaps have a look at that?

**Comment by raphaelduartepinheiro** [comment]
Oh, okay! I'll look for these options. Thanks!

**Comment by raphaelduartepinheiro** [comment]
Just a feedback: Moved to Elastic Search and it works like a charm!
