### ISSUE TITLE
Disabling TS delete callbacks in test environment

### ISSUE THREAD

**Issue by soundrussian** [pat/thinking-sphinx#950]
I'd like to be able to run my specs without sphinx search deamon running.

I'm using RT indices if that's important, but I was able to turn off real time callbacks by putting
```
test:
  <<: *default
  real_time_callbacks: false
```
into my `thinking_sphinx.yml` config.

Now I'm getting the following messages in my test.log:
```
Sphinx  Retrying query "DELETE FROM spot_core WHERE id = 51" after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - DELETE FROM spot_core WHERE id = 51
```
This is because searchd demon is not running when thinking_sphinx delete callback is called on my model. But I don't want it to be running when I run my spec. So how can I disable TS delete callbacks?

**Comment by soundrussian** [comment]
My current workaround is this, but it feels like a dirty hack:
```ruby
RSpec.configure do |config|
  config.before(:all) do
    # Make thinking_sphinx believe no model has any indices
    # so there's no need to delete from index when model instance is destroyed
    ThinkingSphinx::Test.config.index_set_class = Class.new(ThinkingSphinx::IndexSet) do
      def to_a; []; end
    end
  end
end
```

**Comment by pat** [comment]
Fixed in the `develop` branch :)
