### ISSUE TITLE
Delta indexing does not merged

### ISSUE THREAD

**Issue by DIGITALSQUAD** [pat/thinking-sphinx#953]
I'm working on thinking-sphinx 3.1.3 and sphinx 2.2.7-1.
I set delta true on Doc model to enable delta indexing.
When I create a doc, development.searchd.log shows that delta indexing successfully done, but the doc does not indexed on main index(does not hit by search) and indexed when I create one more doc.

development.searchd.log
```
[Tue Oct  6 10:39:14.972 2015] [ 5752] caught SIGHUP (seamless=1, in queue=1)
[Tue Oct  6 10:39:14.979 2015] [ 5752] rotating index 'doc_delta': started
[Tue Oct  6 10:39:15.149 2015] [ 5752] WARNING: binlog: failed to unlink /vagrant/pubannotation/tmp/binlog/development/binlog.001: No such file or directory (remove it manually)
[Tue Oct  6 10:39:15.168 2015] [ 5752] rotating index 'doc_delta': success
[Tue Oct  6 10:39:15.171 2015] [ 5752] rotating index: all indexes done
```

doc_index.rb
```
ThinkingSphinx::Index.define :doc, with: :active_record, delta: true do
  indexes sourcedb, sortable: true
  indexes sourceid, sortable: true
  indexes body, sortable: true
  indexes serial

  has projects.id, as: :project_id
  set_property enable_star: 1
  set_property min_infix_len: 2
end
```

Any suggestions?

**Comment by pat** [comment]
I'm not quite sure if what you're seeing is a bug or a misunderstanding of how Thinking Sphinx behaves. Delta processing does not modify the core index, *only* the delta index - there's no merging, but search results will include records from both the core and delta indices.

Are you seeing the right search results appear?

**Comment by DIGITALSQUAD** [comment]
I misunderstood about delta indexing. Now I see that search by both core and delta indexes.

I found that the problem is *association*.
Doc model and Project model have *has_and_belongs_to_many* association each other.
model/doc.rb
```
has_and_belongs_to_many :projects
```
models/project.rb
```
has_and_belongs_to_many :docs
```
Therefore **Doc.search(conditions: {...})** returns the doc which added last but **Project.find(1).docs.search(conditions: {...})** does not include the doc added last.

I added index for project_id
doc_index.rb
```
ThinkingSphinx::Index.define :doc, with: :active_record, delta: true do
  indexes sourcedb, sortable: true
  indexes sourceid, sortable: true
  indexes body, sortable: true
  indexes serial
  indexes projects.id, as: :project_id # <= Added
  has projects.id, as: :project_id
  set_property enable_star: 1
  set_property min_infix_len: 2
end
```

And added after_add method for project.
models/project.rb
```
class Project < ActiveRecord::Base
  has_and_belongs_to_many :docs, after_add: :update_doc_delta_index
 
  def update_doc_delta_index
    doc.save
  end
end
```
And now works fine, but I think this is a little bit verbose.
Is there any good way?

**Comment by pat** [comment]
You don't need to add the field (especially since it conflicts with the existing attribute of the same name), but yes, what you're doing with the `after_add` call is the right approach.
