### ISSUE TITLE
Lost connection to MySQL server at 'reading initial communication packet', system error

### ISSUE THREAD

**Issue by DIGITALSQUAD** [pat/thinking-sphinx#954]
I got an error about MySQL when execute Doc.search.
Actually it worked fine before yesterday, but raised the error since yesterday.
```
Lost connection to MySQL server at 'reading initial communication packet', system error: 0 - SELECT *, groupby() AS sphinx_internal_group, id AS sphinx_document_id, count(DISTINCT sphinx_document_id) AS sphinx_internal_count FROM `doc_core`, `doc_delta` WHERE MATCH('@sourcedb AA* @sourceid * @body *') AND `project_id` = 160 AND `sphinx_deleted` = 0 GROUP BY `sourcedb`, `sourceid` ORDER BY `sourcedb` ASC, `sourceid` ASC LIMIT 0, 10; SHOW META 
```
Though rake ts:start command finished without errors.
```
[vagrant@localhost pubannotation]$ rake ts:start
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.7.6
Started searchd successfully (pid: 6214).
```
Searchd is running successfully.
```
[vagrant@localhost pubannotation]$ ps aux | grep searchd
vagrant   6213  0.0  0.3  92740  1520 ?        S    03:08   0:00 searchd --pidfile --config /vagrant/pubannotation/config/development.sphinx.conf
vagrant   6214  1.2  1.5 104524  7476 ?        Sl   03:08   0:00 searchd --pidfile --config /vagrant/pubannotation/config/development.sphinx.conf
vagrant   6222  0.0  0.2 107464   952 pts/0    S+   03:08   0:00 grep searchd
```
Any suggestions?
My environment is thinking-pshinx 3.1.3 sphinx 2.2.7

**Comment by pat** [comment]
Does it work if you do a full `rake ts:rebuild`?

**Comment by pat** [comment]
Also: what's in your config/thinking_sphinx.yml file (if it exists)?

**Comment by DIGITALSQUAD** [comment]
I added mysql41 port in config/thinking_sphinx.yml and did `rake ts:rebuild` command it works fine now.
config/thinking_sphinx.yml
```
development:
  port: 9306
  mysql41: 9312
test:
  port: 9307
```
After delete mysql41, it works fine now though. 
I don't figure out which fixed the problem rebuild command or mysql41 port...

**Comment by pat** [comment]
They achieve the same purpose, but the `port` setting is *only* for TS v1 and v2, and the `mysql41` setting is *only* for TS v3. So, you should use only `mysql41`.

**Comment by DIGITALSQUAD** [comment]
I confirmed that use ony `mysql41` and works fine.
Thanks for your comment.
