### ISSUE TITLE
ThinkingSphinx::ParseError when upgrading from 3.0.6 to 3.1.0

### ISSUE THREAD

**Issue by declan** [pat/thinking-sphinx#955]
I have a search query which runs fine in 3.0.6, but breaks when I upgrade to 3.1.0. The generated Sphinx query is slightly different between the two versions, which may be the problem.

Here's what is generated by TS 3.0.6:

    SELECT *, weight() - (1.5 * GEODIST(0.7309109668442155, -1.5294285014482003, lat, lng)) AS pb_weight, (adult + medicaid) AS match_count, GEODIST(0.7309109668442155, -1.5294285014482003, lat, lng) AS geodist FROM `location_program_core`, `location_program_delta` WHERE MATCH('Medication @dataset chicago-metro-region') AND `program_hidden` = 0 AND `is_mailing` = 0 AND `match_count` BETWEEN 1 AND 2 AND `sphinx_deleted` = 0 GROUP BY `program_id` ORDER BY `match_count` DESC, `pb_weight` DESC LIMIT 0, 10 OPTION max_matches=1000, field_weights=(org_name=10, name=10, services_offered=10)

And here's what I get (from the same Ruby code) with TS 3.1.0:

    SELECT GEODIST(0.7309109668442155, -1.5294285014482003, lat, lng) AS geodist, *, weight() - (1.5 * GEODIST(0.7309109668442155, -1.5294285014482003, lat, lng)) AS pb_weight, (adult + medicaid) AS match_count FROM `location_program_core`, `location_program_delta` WHERE MATCH('Medication @dataset chicago-metro-region') AND `program_hidden` = 0 AND `is_mailing` = 0 AND `match_count` BETWEEN 1 AND 2 AND `sphinx_deleted` = 0 GROUP BY `program_id` ORDER BY `match_count` DESC, `pb_weight` DESC LIMIT 0, 10 OPTION field_weights=(org_name=10, name=10, services_offered=10), max_matches=1000

What immediately jumps out to me is that TS 3.1.0 puts the call to `GEODIST` at the start of the select statement, while TS 3.0.6 put it at the end, but I'm not sure why that would cause a parse error.

The Ruby code that is generating these queries is

        MyModel.search(
          geo: [@lat, @lng],
          order: "match_count DESC, pb_weight DESC",
          page: @current_page,
          select: "*, weight() - (1.5 * GEODIST(#{@lat}, #{@lng}, lat, lng)) AS pb_weight, #{match_count_str} AS match_count"
        )
      

This is with Rails 3.2 and Sphinx 2.1.9.

**Comment by pat** [comment]
Hi Declan

The fix, from a quick check locally (so I hope it works for you too) is to refer to the generated `geodist` function instead of calling `GEODIST` again, with your `:select` option becoming: `*, weight() - (1.5 * geodist) AS pb_weight, #{match_count_str} AS match_count`

Let me know if this doesn't work!

**Comment by declan** [comment]
Hi Pat,

That does fix the parse error, but now I get a NoMethodError:

    undefined method `inject' for nil:NilClass

    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/inquirer.rb:49:in `call'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/inquirer.rb:14:in `block in call'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/inquirer.rb:13:in `each'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/inquirer.rb:13:in `call'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/geographer.rb:11:in `call'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/sphinxql.rb:14:in `call'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/middlewares/stale_id_filter.rb:10:in `call'
    middleware (0.1.0) lib/middleware/runner.rb:31:in `call'
    middleware (0.1.0) lib/middleware/builder.rb:102:in `call'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/search.rb:67:in `populate'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/search.rb:46:in `meta'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/masks/pagination_mask.rb:41:in `total_entries'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/search.rb:110:in `block in method_missing'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/search.rb:109:in `each'
    thinking-sphinx (3.1.0) lib/thinking_sphinx/search.rb:109:in `method_missing'
    app/controllers/explore_controller.rb:36:in `index'

The same thing was happening with version 3.0.6, and I was able to work around it by calling `GEODIST` myself instead of referring to `geodist` - that's why I started doing that in the first place.

Here's the stack trace from 3.0.6, although as far as I can see it's the same as for 3.1.0:

    undefined method `inject' for nil:NilClass

    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/inquirer.rb:49:in `call'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/inquirer.rb:14:in `block in call'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/inquirer.rb:13:in `each'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/inquirer.rb:13:in `call'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/geographer.rb:11:in `call'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/sphinxql.rb:14:in `call'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/middlewares/stale_id_filter.rb:10:in `call'
    middleware (0.1.0) lib/middleware/runner.rb:31:in `call'
    middleware (0.1.0) lib/middleware/builder.rb:102:in `call'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/search.rb:67:in `populate'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/search.rb:46:in `meta'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/masks/pagination_mask.rb:41:in `total_entries'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/search.rb:110:in `block in method_missing'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/search.rb:109:in `each'
    thinking-sphinx (3.0.6) lib/thinking_sphinx/search.rb:109:in `method_missing'
    app/controllers/explore_controller.rb:36:in `index


And just to answer some obvious trouble shooting questions: I'm re-configuring, re-indexing, and re-starting ThinkingSphinx and also the Rails server every time I change the gem version.

**Comment by declan** [comment]
Just in case it's helpful, here's the generated Sphinx query from version 3.1.0, after I followed your suggestion.

    Sphinx Query (7.1ms)  SELECT GEODIST(0.7309109668442155, -1.5294285014482003, lat, lng) AS geodist, *, weight() - (1.5 * geodist) AS pb_weight, 1 AS match_count FROM `location_program_core`, `location_program_delta` WHERE MATCH('Medication @dataset chicago-metro-region') AND `program_hidden` = 0 AND `is_mailing` = 0 AND `match_count` = 1 AND `sphinx_deleted` = 0 GROUP BY `program_id` ORDER BY `match_count` DESC, `pb_weight` DESC LIMIT 0, 10 OPTION field_weights=(org_name=10, name=10, services_offered=10), max_matches=1000

**Comment by pat** [comment]
Hmm… I've generally seen this error when Sphinx isn't compiled with MySQL support, or when an old version of the mysql2 gem is being used. But I presume other queries are working normally for you, it's just this one with the GEODIST logic?

From glancing at the release notes in post 3.1.0 releases, it doesn't look like there's anything directly related to this in any bug fixes… but is there a reason you've not given 3.1.4 a shot?

**Comment by declan** [comment]
Ok, I upgraded to 3.1.4 and the issue seems to be resolved. Thanks for the help.
