### ISSUE TITLE
Processing XML Data in XMLPIPE2

### ISSUE THREAD

**Issue by nartz** [pat/thinking-sphinx#962]
Does TS support processing of files? Or only sql data sources for now? Specifically I need to index some xml files with a defined schema.

**Comment by pat** [comment]
Thinking Sphinx only supports SQL and real-time indices. There is no XML or CSV/TSV support at this point in time.

Given the rarity of such a request, I'm probably not going to add it… but if anyone wants to work on a feature, I'm happy to discuss how it could possibly work. That said, Thinking Sphinx *does* expect to work with ActiveRecord objects as search results, so I don't feel this is a good match. However, Riddle – the pure-Ruby (as opposed to Rails-focused) Sphinx gem that underpins Thinking Sphinx – does have support for configuring XML sources/indices and so could be used instead as a simpler option?

**Comment by nartz** [comment]
ok thanks!
