### ISSUE TITLE
mysql 0.4.3 "array size too big" for raw results

### ISSUE THREAD

**Issue by dreyks** [pat/thinking-sphinx#964]
Since mysql2 v0.4.3 a simple `Article.facets('non_existent_text')` raises `ArgumentError: array size too big` when no results where found.
Traced it down to https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/facet.rb#L13 where`raw` seems to be a normal `Mysql::Result` but any sort of `raw#first` or `raw#each` calls result in said `ArgumentError`

This seems to be caused by brianmario/mysql2@5189cfee45872a10cf54afbfcd721de12b2ae36e but my C-fu isn't high enough for further elaboration

**Comment by dreyks** [comment]
UPD: this boils down to `ThinkingSphinx::Search#raw`
```console
> Article.search('lorem ipsum').raw.first
Sphinx Query (0.9ms)  SELECT * FROM `article_core` WHERE MATCH('lorem ipsum') AND `sphinx_deleted` = 0 LIMIT 0, 20
  Sphinx  Found 0 results
NoMemoryError: failed to allocate memory
```
I'm sure this has something to do with accessing the freed memory

Again, this happens only when no results where found.

**Comment by pat** [comment]
Well that's certainly frustrating! Sounds like it might not be a bug in TS itself, but could be either mysql2 or Sphinx itself. Of course, not ruling out that the problem may lie in my code!

Which version of Sphinx are you using?

**Comment by dreyks** [comment]
I'm using Sphinx 2.2.10.

**Comment by dreyks** [comment]
Ok, this is not a thinking_sphinx bug...

```console
> client = Mysql2::Client.new(host: 'db', password: 'root')
> raw = client.query('SELECT * FROM i_rails.schema_migrations WHERE 1 = 0 LIMIT 1')
> raw.to_a
=> []
> raw.first
ArgumentError: array size too big

**Comment by pat** [comment]
I think it might actually be a TS bug. Just pushed a commit to the develop branch that seems to fix things: 42f5c859cbc5068b876345dea37623caab11f4e2.

**Comment by dreyks** [comment]
If I get the issue correctly, this won't fix the issue.

I'll test the develop branch and report back in

**Comment by dreyks** [comment]
Nope, still not working. However what **does** fix this is `context[:raw]     = context[:results].dup`

As I see it, mysql2 calls `free` on the first call to raw_results, and all subsequent calls to `raw_results#free` result in memory access failure

**Comment by pat** [comment]
Updated in f8914931580f1c365a505b73b0ea6e920b2dbffd :)

**Comment by dreyks** [comment]
The original issue is also fixed in mysql2 master branch by brianmario/mysql2#741
