### ISSUE TITLE
Specify Column as Document ID

### ISSUE THREAD

**Issue by nartz** [pat/thinking-sphinx#965]
Hi - I have a table that has a primary key, `AUI`( Varchar(9)), whose values always start with the letter 'A', i.e.:
'A12345678'

I would **like** to use this as the primary key column for sphinx, by using a selector like:

has 'SUBSTR(AUI,2)', as: :id

When sphinx wanted to retrieve the document from the database, add back in the 'A' char to the prefix.

1. Is this at all possible to specify in my index to use a modified 'AUI' column as the sphinx document id?
2. Is there a place to hack in an 'A' prefix to the thinkingsphinx lookup after its retrieved results from sphinx, but before it has looked them up using activerecord?

Any other ways to acheive this? (short of adding on an integer 'id' column? We really cant modify the original tables.)
Thanks!

**Comment by pat** [comment]
I'm sorry, but short of a _serious_ amount of hacking of Thinking Sphinx's internals, this just isn't possible. The expectations of an integer primary key column in the TS codebase have impacts in many places.

Of course, you're welcome to dive into the code and see if you can get it working, but I feel that path is long, painful, and saddles you with a bunch of hard-to-maintain code.

Perhaps it's worth looking into using a different search tool?

**Comment by nartz** [comment]
Alright, thanks! I figured out a pretty hacky way, namely, doing a custom sql query that processes the column to turn it into an integer, i.e. 'SUBSTR(AUI,2)' as id. Then, simply querying for the ids themselves, appending back the prefix 'A' to each id, and then looking them up directly in mysql. 

However, probably wont go that route, if possible will just focus on adding an integer id column to the original database (although with this comes its own set of headaches).

Thanks for the feedback!
