### ISSUE TITLE
No callbacks for removing records from RT indexes

### ISSUE THREAD

**Issue by dmons** [pat/thinking-sphinx#967]
Hi all,
Inspecting class ```ThinkingSphinx::RealTime::Callbacks::RealTimeCallbacks``` I didn't found the way how to remove record from index. Any ideas for this?

**Comment by pat** [comment]
The magic lies within `ThinkingSphinx::ActiveRecord::Callbacks::DeleteCallbacks` which covers deletion for both types of indices.
https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb

**Comment by dmons** [comment]
Thanks for the link. But I would like to delete some record from index not by AR::destroy, but on changing state in state_machine. Could you advice a nice way? 
Another problem I've got sphinx call is going inside transaction and I can't properly update index with latest state, which will be reachable after state transition commit.

**Comment by pat** [comment]
Sorry for the delay.

You can invoke that callback class without actually using a callback, if you want. That said, you'd also need to implement a wrapper around the after_save TS callback so it doesn't update records that you _don't_ want in your indices.

I'm not quite understanding your second issue - can you provide some code of how you're using a transaction, and some more detail on what data won't be up-to-date in Sphinx?
