### ISSUE TITLE
Sphinx Facet Search with new syntax 

### ISSUE THREAD

**Issue by Kinaan** [pat/thinking-sphinx#968]
Hi, 

I have been reading about the faceted search in sphinx and I came across the following link http://sphinxsearch.com/blog/2014/05/22/the-facet-feature/ . 

I know that in thinking sphinx we are using the old syntax. I am currently looking into the difference it would make in terms of performance.  

nevertheless, is there any plan to shift to the new syntax ? As I was quite interested in working on it.

**Comment by pat** [comment]
I've not yet looked at switching - mainly due to the hassle of supporting two different approaches because people may still be using older releases of Sphinx.

Certainly, if you want to investigate, I'd love to see a patch, I'm just not sure when it'll be merged in.

**Comment by pat** [comment]
I'm going to close this issue - I don't think I'm going to rush to implement this change, given a preference to support older versions of Sphinx. Still, am open to patches if someone wants to investigate :)
