### ISSUE TITLE
Realtime index deeply nested model associations

### ISSUE THREAD

**Issue by al3izz** [pat/thinking-sphinx#969]
By far, I have found Thinking Sphinx and Sphinx Search to be the best searching APIs I've ever used. I'm really glad with the work which has been done.

However, I'm still a bit confused about a couple of things regarding Realtime indexing:

Say I have the following association relationship:

```
# Person.rb

after_save ThinkingSphinx::RealTime.callback_for(:person, [:person])

has_many :oldjobs, dependent: :destroy
has_many :experiences, dependent: :destroy


# Experience.rb

belongs_to :person, touch: true
belongs_to :department


# Oldjob.rb

belongs_to :person, touch: true
```

So now, the questions:

**1. How do I index something like Person.experiences.department.name ???**
I read that I have to use a method inside Person.rb, so I tried the following **but it doesn't work**:

```
# Person.rb

def experiences_department_names
  experiences.map{ |e| e.department.name }.join(' ')
end
```

```
# person_index.rb

indexes experiences_department_names
```

**2. How do I correctly register the after_save callbacks for the above relationship?**
So far I only put one inside Person.rb, but I'm unsure what to do about the other models.

**3. How do I save my realtime indices?** I find that they disappear if I restart the server and I end up having to re-index. And when I check inside my db/sphinx/environment folder, I don't find any index files, it's just a blank folder.

**4. Are destroy callbacks already incorporated for Realtime indices?** For example, if I delete a model instance, it would be removed from the sphinx index automatically right?

Thank you.

**Comment by pat** [comment]
**1.** What you're doing should indeed work. In what way is it not behaving as expected? Have you run `rake ts:regenerate` after adding that new field?

**2.** In the Person model, what you've got isn't quite right - it's actually a little simpler:

```ruby
after_save ThinkingSphinx::RealTime.callback_for(:person)
```

The second argument is the method path to follow to get the associated objects. In the case of Person, no methods need to be called to access the person being indexed. But in the case of both Experience and Oldjob, it is a single method call to get the associated person:

```ruby
# Because you call `person` in an experience or old job to access the person object(s)
after_save ThinkingSphinx::RealTime.callback_for(:person, [:person])
```

If, say, you had an index on Experience and wanted the callback to fire when a person changes, it would be the following in the Person model - TS is smart enough to take an array and persist changes for each item:

```ruby
after_save ThinkingSphinx::RealTime.callback_for(:experience, [:experiences])
```

**3.** Initially, Sphinx stores the data in memory. If you stop the daemon through the rake task (rather than `kill -9`), it _should_ shift the data from memory to files. A way to manually persist data on a regular basis (say, if you've got something backing up the data files) is to send the FLUSH INDEX command for each index name:

```ruby
configuration = ThinkingSphinx::Configuration.instance
configuration.preload_indices
indices = configuration.indices.select { |index| index.type == 'rt' }
ThinkingSphinx::Connection.take do |connection|
  indices.each { |index| connection.execute "FLUSH RTINDEX #{index.name}" }
end
```

**4.** Yes, deletions are a standard callback attached to all models, and they trigger the appropriate behaviour if there are any SQL-backed or real-time indices.

**Comment by pat** [comment]
Also: thanks for the kind words :)

**Comment by al3izz** [comment]
**1.** Yes, it doesn't work. Here's what I want to achieve:
A person has many work experiences/histories. Say he worked at a grocery store about 2 years ago. When I search for 'Grocery Store', I want to be able to find this person even if his current job isn't that job. In other words, I want to be able to find all people who worked at a specific place even if it was a long time ago. So this is why I want to be able to index the experiences department names, because a single person can have many experiences -- one of them is current and the rest are old.

Also, this is a separate issue, but sometimes ts:regenerate doesn't refresh the indices; instead, I have to use the following commands in this specific order: sudo service sphinxsearch stop && rake ts:rebuild ts:stop ts:configure ts:start ts:generate

Do you think that might be related to my issue above?

**2.** Ah ok thank you, that helps. Okay, let me get a complete understanding here, so what if I have the following setup:

```
# Person.rb

after_save ThinkingSphinx::RealTime.callback_for(:person)

has_many :oldjobs, dependent: :destroy
has_many :experiences, dependent: :destroy
belongs_to :department 


# Department.rb

has_many :people
```

And I have an index on Department, so it would be like so?

```
# Department.rb

after_save ThinkingSphinx::RealTime.callback_for(:department)

# Person.rb

after_save ThinkingSphinx::RealTime.callback_for(:department, [:department])
```

Instead of the above two, what if I did just one statement inside of Department.rb as follows:

```
# Department.rb

after_save ThinkingSphinx::RealTime.callback_for(:department, [:people])
```

I would assume that this works; however, the downside to it is that it only indexes when 1 association changes and not the rest. Correct? Sorry if I'm getting really theoretical, but I just want to understand well.

**3.** Ah ok that's very interesting, thank you very much. Is this something I should put inside an initializer?

4. Ok, great.

**Comment by al3izz** [comment]
I really need help on **question 1**

**Comment by pat** [comment]
1A: Are you finding the method you've added to your model is returning the right data, even though Sphinx isn't?

1B: Are you using both SQL-backed and real-time indices? If not, you don't need to use the `ts:rebuild` task. That said, manually stopping Sphinx before running `rake ts:regenerate` might be more reliable.

2A: The callback you've suggested in your Person model to cover the Department index is indeed correct.

2B: This callback isn't valid - it would be hitting the `people` method on a department instance, and treating each person instance as a department instance and trying to save department index values from the person object.

If you want to have the person index update when a department is updated, you'd instead want the following:

```ruby
after_save ThinkingSphinx::RealTime.callback_for(:person, [:people])
```

3: That code is only useful when you want the index files to be updated before copying data elsewhere (so, possibly in a rake task called before backing up data?). It's not needed in an initializer. Sphinx should persist data automatically, it just won't appear _immediately_ in the file system while Sphinx is running.

**Comment by al3izz** [comment]
1A: yes, this is the exact method I'm using:
```
# Person.rb

def experiences_department_names
  experiences.map{ |e| e.department.name }.join(' ')
end
```

And as you can see it returns a single string containing all the specific person instance's previously worked at department names separated by a space.

I'm still finding this to be troublesome. I simply can't get any results, it always returns 0.
I have this within my index:
```
# person_index.rb

indexes experiences_department_names
```

And when I search, I search:
`Person.search("@experiences_department_names *")`
and I get nothing returned

1B: I'm using Realtime-only indices as far as I know. Okay no problem then, thank you.

Thank you for all your responses.

**Comment by pat** [comment]
I'm pretty sure Sphinx won't treat `*` as a regex-like 'match everything' approach. What happens if you search for a specific value you're expecting to match?

**Comment by al3izz** [comment]
Wow it works now when I search for a specific value. I was searching for a specific value earlier but it wasn't working.. Anyway, all that matters is it works now, thank you.

**Comment by pat** [comment]
Good to know it's working now at least! Do let me know if there are any further issues :)
