### ISSUE TITLE
Indexer is double counting records

### ISSUE THREAD

**Issue by chris-roerig** [pat/thinking-sphinx#970]
Hello,

I'm fairly certain this is a configuration issue and not TS but I've run out of debugging ideas. I have a couple tables that live on a database other than the default Production. My db user does not have write access to the database which may explain the issue I'm having. However, things have been working as expected up until today when I added a new index. What is happening is it appears Sphinx is counting records twice. 

```
Foo.count # 1266797
Foo.search.count # 2533594
```

This is the output of the indexer:
```
indexing index 'foo_core'...
collected 1266797 docs, 31.7 MB
sorted 17.7 Mhits, 100.0% done
WARNING: sql_query_post_index: UPDATE command denied to user 'readonly'@'fakeserver.net' for table 'foos' (DSN=mysql://readonly:***@fakeserver/somedb)
total 1266797 docs, 31697173 bytes
total 15.252 sec, 2078151 bytes/sec, 83054.59 docs/sec
indexing index 'foo_delta'...
collected 1266797 docs, 31.7 MB
sorted 17.7 Mhits, 100.0% done
total 1266797 docs, 31697173 bytes
total 14.294 sec, 2217409 bytes/sec, 88620.13 docs/sec
```

You can see that `_core` and `_delta` each collected 1266797 docs where as my other records that are indexed properly report `_core` has a number and `_delta` is 0. 

My guess is this may be due to not being able to update the delta column.

Here is where it gets strange. There are 2 tables like this however only 1 is duplicating the count.

@pat any help would be greatly appreciated.

**Comment by pat** [comment]
Hi Chris

Can you let me know which versions of Thinking Sphinx and Sphinx you're using? I feel like there was a bug around this some time ago…

That said: if you have read-only access, then using deltas doesn't give you anything: as you're seeing, it takes just as long to process the delta index as the core index, whereas normally you'd want the delta to be small and thus super fast. That is probably unrelated to the issue you're seeing, though.

**Comment by chris-roerig** [comment]
@pat, thank you for your support on this. 

```
Sphinx 2.2.6-id64-release (r4843)
thinking-sphinx (3.1.4)
```

**Comment by pat** [comment]
Is the count correct if you only have a core index (or even, if you limit the search to just the core index, using `:indices => ['foo_core']`)?

As mentioned before, it doesn't sound like there's much point to having deltas if you've only got read access to the database - unless there's further context I'm not aware of?

**Comment by chris-roerig** [comment]
Removing `delta: ThinkingSphinx::Deltas::SidekiqDelta` from Index.define seems to have fixed the count issue. Thanks @pat
