### ISSUE TITLE
Thinking sphinx rspec unit test

### ISSUE THREAD

**Issue by edenisn** [pat/thinking-sphinx#971]
How to test (rspec unit tests) search with thinking sphinx and database cleaner? If I use transaction strategy in database cleaner search doesn't work. If I use truncation strategy search work, but some other tests doesn't work. Show the sample code of test and cofiguration of database cleaner, thanks

**Comment by pat** [comment]
For the configuration, I'd do something like this (and note that the order of the `before(:each)` callbacks matters).

```
RSpec.configure do |config|
  config.use_transactional_fixtures = false

  config.before(:each) do
    # Default to transaction strategy for all specs
    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each, :sphinx => true) do
    # For tests tagged with Sphinx, use deletion (or truncation)
    DatabaseCleaner.strategy = :deletion
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.append_after(:each) do
    DatabaseCleaner.clean
  end
end
```

And then I'd tag specific specs to use Sphinx and the deletion/truncation strategy:

```
it "searches", :sphinx => true do
  # ...
end
```

**Comment by pat** [comment]
This is now covered in the improved testing docs: http://freelancing-gods.com/thinking-sphinx/testing.html
