### ISSUE TITLE
Complexe association filtering

### ISSUE THREAD

**Issue by Romz** [pat/thinking-sphinx#972]
Hi,

First of all, good job this amazing gem.

I need to do a complexe filtering through an association, but i didn't find any way to make it work as i want. I don't know if it's possible to do this. I explain my problem:

I have an "Announces" model that contains relationship to another model "Characteristics" Through table "Announces_Characteristcs".
"Announces_Characteristics" contain an integer field named "value".

I need to make a range search to value for each characteristics like this:

```ruby
Announces..search params[:q], :with: {  
   (:characteristic_value => 0..100 AND :characteristic_id => 15 ) 
   AND 
  (:characteristic_value => 50 AND :characteristic_id => 16) 
  #etc...
}
```

Heres my models

```ruby
class Announce < ActiveRecord::Base
  has_many :announces_characteristics
  has_many :characteristics, through: :announces_characteristics
end
```

```ruby
class Announce < ActiveRecord::Base
  has_many :announces_characteristics
  has_many :characteristics, through: :announces_characteristics
end
```

```ruby
class AnnouncesCharacteristic < ActiveRecord::Base
  belongs_to :characteristic
  belongs_to :announce
 # Value is in this model
end
```

```ruby
class Characteristic < ActiveRecord::Base
end
```

Is it possible to do something like this?

**Comment by Romz** [comment]
May be it's possible to index each characteristic values as separated attribute, like this:

```ruby
Characteristics.all.each do |characteristic|
    has	"IF(announces_characteristics.characteristic_id = #{characteristic.id}, announces_characteristics.v\
alue, null)", :as => "characteristic_#{characteristic.id}", :type => :integer
  end
```

This code doesn't work, but is it possible to do something like that?

**Comment by Romz** [comment]
In fact, adding 
```ruby
join announces_characteristics
```

make it work :).

**Comment by pat** [comment]
Ah, great to know you found a solution!

Of course, this only works if characteristics aren't changing often (every time you have a new characteristic, you'll need to run `ts:rebuild` with the above approach).

Sphinx doesn't have any native concept of hashes/dictionaries, so while you can have both characteristic values and characteristic ids tied to an announce document in Sphinx, there's no way in Sphinx's standard attributes approach to link a specific characteristic value and id together.

One alternative is instead to have a Sphinx index on AnnounceCharacteristic, and group by announce_id - but this would only work when searching on single id/value pairs. Sphinx however, does also support JSON attributes, so perhaps an option is to store those values as a JSON hash in the attribute, and then construct a custom SphinxQL SELECT clause to filter on one or many key/value pairs. Something to consider for the future (or for others who come across this issue but are dealing with more dynamic key/value pairs).

**Comment by Romz** [comment]
In fact my solution work only for the first announces_characteristic.

Do you have a simple example of JSON attribute? 
I didn't find examples on documentation.

**Comment by pat** [comment]
You'd need to cache your id/value pairs as a JSON column on your Announce model, and then add that column as an attribute to your index.

```
has json_attribute
```

And then, once you've run `rake ts:rebuild`, the following should work (I've not tried it myself, but syntax is taken from [this Sphinx blog post](http://sphinxsearch.com/blog/2013/08/08/full-json-support-in-trunk/)):

```
Announce.search :with => {"json_attribute.16" => 50}
```

Make sure you're using a 2.2.x release of Sphinx (from what I understand, this feature was introduced reliably in 2.2.1).

**Comment by Romz** [comment]
Thank you, it works very well.

This is what i did:

announce_index.rb:

```ruby
has json_characteristics
```

announce.rb:

```ruby
before_save :serialize_characteristics

def serialize_characteristics
    json = {}

    self.announces_characteristics.each do |ac|
      json[ac.characteristic_id] = ac.value
      self.json_characteristics = json.to_json
    end
  end
```

It works great :). Thank you.

**Comment by pat** [comment]
Great! :)
