### ISSUE TITLE
What is the preferred way to index a single table that does not utilize delta indexing?

### ISSUE THREAD

**Issue by chris-roerig** [pat/thinking-sphinx#979]
I understand its possible to index a single table using:

```
ThinkingSphinx::Deltas::IndexJob.new("model_delta").perform
```

Does this work for models that do not use delta indexing? If not, is there a way to do this using Thinking Sphinx rather than calling `system "indexer model_core"` ?

**Comment by pat** [comment]
You can use that same approach with any index name, whether it's a delta index or not. Of course, if you've got a lot of data, this task could end up being quite slow, and you'll want to be wary of having it run concurrently.

If you've got frequently updating data, deltas or real-time indices are highly recommended :)

**Comment by chris-roerig** [comment]
Thanks @pat
