### ISSUE TITLE
Search Permissions?

### ISSUE THREAD

**Issue by al3izz** [pat/thinking-sphinx#980]
This is a discussion rather than an issue; I've got two questions about TS right now:

**1.** I want to implement search permissions in my Rails app, such that lets say I have an index of about 20 fields/attributes; I want to allow a specific user to only be able to search on 5 out of those 20 fields/attributes.

Can you think of any way this would be possible within TS?

I was thinking this is easy with attributes since you can just filter the search params, however with fields this would be hard because its possible to search any word and get results without using the field operator... Unless I made using the field operator mandatory.

What do you think?

**2.** I would like to create a progress bar on the frontend for the progress of a search index regeneration... This means I would have to access the original method you use for indexing and then add an update_counter kind of method for each iteration of the loop. This is what comes to mind, do you know of any better way?

**Comment by pat** [comment]
For the first question: I think the safest/most reliable approach here would be to have two separate index definitions for each model that you want different search approaches for. That way, programatically, you can just use the `:indices` option and pass in the index names that are appropriate.

The second question, however, is certainly more complex. Are you using real-time indices or SQL indices?

**Comment by al3izz** [comment]
1. That sounds great, but I've got a follow up question to that: my permissions are not based on Role names, e.g. Admin, Manager, User, etc. as traditional ACLs are, no; rather, they're based on the permissions themselves, i.e. can he edit a Department, can he delete a Department, can he search on a Department, can he search on a Department's name field, can he search on a Department's location field, etc. and the Role name could be anything.

Therefore, my follow up question is: am I able to generate indices on the fly without having to reindex all the data (ideally for everytime a Role is edited/saved/created)?

2. I'm using Realtime indices.

Thanks

**Comment by pat** [comment]
Okay, separate indices doesn't sound like a good approach here, given the custom nature of the fields available. Instead, what you can do is manually limit a query to specific fields through Sphinx's own syntax:

```ruby
Department.search "@(name,location) #{query}"
```

You'll want to be checking the provided search queries for any field references (e.g. `@name`, `@location`, etc) and remove them, to ensure only the fields _you_ are specifying are queried against.

As for tracking a full regenerate call - firstly, why? Your data should be automatically up-to-date with the real-time callbacks… are you changing index definitions on the fly? Or are you bulk updating data in a way that callbacks aren't fired?

That said, you can subscribe to progress indicators for the population using ActiveSupport::Notification - my own code does this too: https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/subscribers/populator_subscriber.rb

**Comment by al3izz** [comment]
> As for tracking a full regenerate call - firstly, why? Your data should be automatically up-to-date with the real-time callbacks… are you changing index definitions on the fly? Or are you bulk updating data in a way that callbacks aren't fired?

I said that so that the fields that they are not able to search on wouldn't have any data indexed on them; however, now that you mentioned Sphinx's special syntax for limiting search to particular fields, this issue is now solved! Thank you.

And about the progress indicators, thank you very much.

Thanks once again.

**Comment by pat** [comment]
Great to know it's all sorted :)
