### ISSUE TITLE
Sphinx trying to "UPDATE *_core" during tests. Why?

### ISSUE THREAD

**Issue by subimage** [pat/thinking-sphinx#981]
Hey Pat,

Got an app I'm upgrading from Sphinx 2.x to 3.x. Currently Rails 3.2.22. I had it on ThinkingSphinx 3.1.4 latest, but downgraded to 3.0.6 after reading your notes on the home page about ActiveRecord incompatibility problems.

Anyhow, here's my issue that's happening on both versions.

My tests were hanging, and during the hang I went to inspect my test.log file. I'm seeing lots of stuff like this:

    Sphinx  Retrying query "UPDATE invoice_core
    " after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - UPDATE invoice_core
    Sphinx  Retrying query "UPDATE invoice_core
    " after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - UPDATE invoice_core
    Sphinx  Retrying query "UPDATE invoice_core
    " after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - UPDATE invoice_core
    Sphinx  Retrying query "UPDATE in

I read this was an issue with not switching `port` to `mysql41` in the thinking_sphinx.yml file - which I've done. However, I believe this is a symptom of a larger issue.

My question: _Why is sphinx doing anything during tests?_ 

In my test_helper.rb I'm not doing anything that should be touching them. I've disabled deltas and stopped tests like so:

```ruby
class ActiveSupport::TestCase
  self.use_transactional_fixtures = true
  self.use_instantiated_fixtures  = false

  ThinkingSphinx::Test.stop
  ThinkingSphinx::Deltas.suspend!
  
  ActiveRecord::Base.observers.disable :all
  Time.zone = 'UTC'

  setup :log_test_name
  def log_test_name
    Rails.logger.debug "\n\n#{self.method_name}"
    Rails.logger.debug "#{'-' * 40}"
  end
end
```

Now, since updating the `mysql41` bit I'm not seeing those errors in the logs, _but the tests still hang_.
**If I remove Sphinx completely, the hanging issue goes away.**

Any advice you could suggest to remove Sphinx from my test framework completely would be appreciated.

**Comment by pat** [comment]
Hrm. So, I think the errors in the logs are from Thinking Sphinx trying to update Sphinx when records are deleted. The suspend setting only applies to creates/updates. At this point, there's actually no way to disable the delete callback, so I'll have to look into improving that…

But it doesn't sound like that's the cause of the hanging issue. When the test process is hanging, do you get a stacktrace if you kill it with control-c?

**Comment by subimage** [comment]
Thanks for the quick response as usual Pat.

On Ctrl-C…I’m using autotest, so using that key combo just restarts the test cycle. I can’t reliably get it to hang on single tests (only the whole suite, randomly), so trying to isolate this has been a huge pain.

That’s exactly the case. All tests that use “destroy_all” or variants are running into that hanging issue. Guess I’ll poke around and see if there’s some monkey patch to be made. There’s no way I can use deltas if it’s going to affect my tests in this manner.

Any pointers on where to start looking?

**Comment by pat** [comment]
I just pushed commit 198cf980a9644d403900c3affd76a204bb723772 that adds `ThinkingSphinx::Callbacks.suspend!`. This stops delta updates completely, deletions, and also real-time updates.

Granted, that's only available in the develop branch at this point, but perhaps it's useful if you wanted to fork a branch off the v3.0.6 tag and cherry-pick this commit in?

**Comment by subimage** [comment]
[I've branched and applied fixes here](https://github.com/subimage/thinking-sphinx/tree/3.0.x-fixes) if anyone runs across this in the future.

Thanks again for the ever-quick response and attention to this gem. Couldn't run my apps without it.
