### ISSUE TITLE
Unknown attribute type 'json'

### ISSUE THREAD

**Issue by nvma** [pat/thinking-sphinx#982]
Hello, Pat. Thanks for an amazing gem, it has been working great in our project. The only issue we're experiencing is with the json type: we're using PSQL 9.5.2 jsonb to store our json, and rake aborts at generating configuration file:
```
rake ts:configure
** Invoke ts:configure (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute ts:configure
rake aborted!
Unknown attribute type 'json'
```
migration file:
` add_column :organisations, :detail, :jsonb, default: '{}', null: false`

index file:
```
ThinkingSphinx::Index.define :organisation, with: :real_time do
  ...
  # attributes
  has created_at, type: :timestamp
  has updated_at, type: :timestamp
  has detail, type: :json
end
```
We're using latest (3.1.4) TS gem and Sphinx 2.2.10. Is this issue related specifically to PSQL's jsonb format, or we're missing something out? Thanks for your time!

**Comment by pat** [comment]
Somehow I didn't have this in place for real-time indices. That's now fixed with 1aa27bdb37ed79f5d2f6c32352445ded29e8e267 in the develop branch. I do want to tidy up the implementation a little, and then I'll push out a proper gem release - but do feel free to use the develop branch in your Gemfile in the meantime!

```ruby
gem 'thinking-sphinx', '~> 3.1.4',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '1aa27bdb37'
```

**Comment by nvma** [comment]
Worked like a charm, thanks a lot!

**Comment by pat** [comment]
Just pushed [v3.2.0](https://github.com/pat/thinking-sphinx/releases/tag/v3.2.0) :)
