### ISSUE TITLE
Best strategy for indexing tables change by stored procedures

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#983]
Hi,

We have stored procedures that kick off and modify tables we want to keep up to date with Sphinx. Do you have any ideas on how we could automatically reindex a table when this happens?

**Comment by pat** [comment]
Hmm, this is a tricky one. If you're using Delayed Job or Que or some other database-backed background job processing tool, then I guess your stored procedures could add a row to the corresponding table to invoke a new job? Of course, that means being across the exact approach these libraries use for adding jobs, which could be painful when upgrades happen.

Or, have a new table that the stored procedures can add records to, and some kind of repeating task in any background job tool that checks that table, creates new jobs itself (safer, more reliable) to process the indices in question.

I'll ponder further, but not sure if there are any more elegant solutions at the moment.

**Comment by atomical** [comment]
We usually use stored procedures when a massive amount of records are created, updated, or destroyed.  I don't think keeping track of each change is worth it in our case.

A solution might be to have the stored procedure shell out to curl when it is finished. That command would make a call to an API endpoint that reindexes the table.

**Comment by pat** [comment]
Ah, I didn't realise stored procedures could shell out to the command line - but yeah, that sounds like a simpler solution :)
