### ISSUE TITLE
Conditions with quorum operator

### ISSUE THREAD

**Issue by dwickwire** [pat/thinking-sphinx#984]
The[ documentation states](http://freelancing-gods.com/thinking-sphinx/searching/ts2.html):

> Extended mode combines boolean searching with phrase searching, field-specific searching, field position limits, proximity searching, quorum matching, strict order operator, exact form modifiers (since 0.9.9rc1) and field-start and field-end modifiers (since 0.9.9rc2).

Is it possible to use a conditions hash with the quorum operator?  If so, could I get an example of how to define that?  

Currently I have to do this to use the quorum operator:

``` ruby
Customer.search("\"Joe Smith 5555555555\"/1"
  match_mode: :extended2
)
```

I'd rather do this and let TS handle the string pass off to Sphinx.

``` ruby
Customer.search(
  conditions: conditions,
  quorum: 1
  match_mode: :extended2
)
```

I need the fuzzy search logic that a quorum matching operator provides, but I'd rather not build a large search string out of the hash parameter format I begin with.  That would allow me to just pass my conditions to TS and sort-of fire and forget.

**Comment by dwickwire** [comment]
One more comment about all this, I am slightly confused if the match_mode `:any` does anything, since I would expect `:any` to effectively have a quorum matching of 1.  I'm basically using the quorum operator because `:any` does not find anything if any of them match.

**Comment by pat** [comment]
To deal with your second issue first: in TS v3 (or rather, with Sphinx's newer SphinxQL syntax, which is what TS v3 uses), all queries use the extended2 match mode - the `:match_mode` setting does nothing. So, if you want to have `:any`-like behaviour, you'll need to manually add OR pipes into your queries: `Joe | Smith`.

But, regarding the quorum operator… with your example query, can you explain what you're hoping to be matched?

**Comment by dwickwire** [comment]
Interesting.

Sure, so here's what I'm hoping to be matched, given a record of 
```yaml
name: John Smith
phone: 5555551234
```

Let the user change their phone number to `5555555555` (but this isn't in the database/index yet) and now we search against that record with a new phone number: 
```ruby
Customer.search("\"Joe Smith 5555555555\"/1"
  match_mode: :extended2
)
```

Using the quorum matching of 1 in that scenario will allow me to get a result, which is why I expected `:any` to do as well, but you say that it doesn't work.

What I'd like to be able to do is to pass a conditions hash and still use the quorum operator, so for the same string query I'd instead be able to do:
```ruby
conditions = {
  name: "Joe Smith",
  phone: "5555555555"
}
Customer.search(
  conditions: conditions,
  quorum: 1
  match_mode: :extended2
)
```
The phone number does not match the record but the name does and because I have a quorum match limit of 1, it will return the record.

**Comment by pat** [comment]
Would it be easier to use the OR logic instead of quorum? I _think_ the following would work…

```ruby
Customer.search "(@name #{name} | @phone #{phone})"
```

**Comment by dwickwire** [comment]
That would work but I guess my point by creating this issue is that that *is not* easier.  

Its the difference of passing form params through a controller to TS and calling it a day or having some intermediary query building logic which a) knows what Sphinx expects and b) knows the structures of the form and how to manipulate them.  

In my thinking it might be much easier for everyone involved to just pass the conditions hash along to TS and sort-of fire and forget.  In other words, let TS handle building the query string for Sphinx.   I don't mean to say this to add loads of work for you, I'd be happy to fork things and try adding that with some collaboration and direction, I guess I'm raising something of a more philosophical point here.

Yeah, that would work but I think maybe I'm raising more of a philosophical issue maybe?  I'd really like to avoid building Sphinx specific queries and would like TS to handle that for me.

At this point I have three or four apps using sphinx, two use TS and one or two use django-sphinx which I'm phasing out and moving to haystack+ES, in any event both TS and django-sphinx have had pain points for me in query building for Sphinx and I guess I'm wondering if its a) feasible to be able to pass the conditions hash in with use of a quorum operator or b) to make the any match_mode *do* something and implicitly enforce a `OR` operator?

**Comment by pat** [comment]
Ah, I was getting confused between quorum and the NEAR operator, and wondering what you were trying to do with your search query. Now that I've re-reviewed the Sphinx docs, this certainly makes more sense - sorry!

But, I do still have questions… if you're specifying conditions, TS translates that to Sphinx's field syntax, which is why I was using in my search example previously (the @fieldname syntax). So, the following two statements are exactly the same:

```ruby
Customer.search(:conditions => {:name => "Joe Smith", :phone => "5555555555"})
# identical results to:
Customer.search("@name Joe Smith @phone 5555555555")
```

To add a quorum option that applies in the first case would perhaps be a little confusing. Should it apply to each field value separately, thus resulting in `@name "Joe Smith"/1 @phone "5555555555"/1`? Or, the entire query: `"@name Joe Smith @phone 5555555555"/1`? The former's not what you want, the latter will probably not be understood by Sphinx (though you're welcome to check!).

It sounds like a better solution is that a quorum option applies to the general query (not specific conditions), thus making these two calls equivalent:

```ruby
Customer.search('"Joe Smith 5555555555"/1')
Customer.search("Joe Smith 5555555555", :quorum => 1)
```

I realise this isn't quite going to match your form params, by the sounds of things - but using `:conditions` has had specific behaviour from the very beginning, and unless I'm misunderstanding things, your suggestion when combined with a `:quorum` option would change that. Or have I got it wrong?

**Comment by dwickwire** [comment]
Ah, gotcha.  Yeah, the NEAR operator is nearly the same in syntax, isn't it :)

I'm with you, a quorum key:value argument (`quorum: N`) which applies to a general query string would be nice, in the way you suggest.  At the very least it'd put a label to a Sphinx feature that is otherwise obfuscated (i.e. `query/N` requires knowledge that `/N` is the quorum operator, using `quorum: N` at least tells you what its called).

As for quorum interactions with conditions, I see your point about needing to be careful about conflating how conditions are transformed to SphinxQL.

Would it make sense for it to do this, given the presence of a `match_mode :any`?
```ruby
Customer.search(conditions: {name: "Joe Smith", phone: "5555555555"}, match_mode: :any)
# will then get converted to
Customer.search("@name Joe Smith | @phone 5555555555")
```

Taking it then a step further to include the quorum operator, then if a quorum argument were to be included with a match mode of `:any`, what if we convert in this way:
```
Customer.search(conditions: {name: "Joe Smith", phone: "5555555555"}, match_mode: :any, quorum: 1)
# to be identical to this, which does work
Customer.search("\"@name Joe Smith | @phone 5555555555\"/1")
```

If I'm not mistaken, this seems it would have the benefit of combining :any, with a quorum and maintain field weighting.

**Comment by pat** [comment]
The complications I'm seeing here go a little deeper. A few more examples of potential parameters:

```ruby
:conditions => {:name => "Joe Smith", :phone => "5555555555"}, :match_mode => :any
```

If we're hoping to replicate Sphinx's old `:any` match mode, then this should be translated to `@name (Joe | Smith) | @phone 5555555555`.

```ruby
:conditions => {:name => '"Joe Smith"', :phone => "5555555555"}, :match_mode => :any
```

What if `:name`'s value has quotes in it? Should it become `@name "Joe Smith" | @phone 5555555555`? That kind of parsing can get complicated, quickly.

I think, if we're going to go down this path, there's a few things to be clear on:

* We can't use `:match_mode`, given historically it's referring to a Sphinx feature. It'd be better to have a new option without the historical baggage.
* Given the query you're hoping for is a little different to Sphinx's original `:any` behaviour anyway, perhaps that helps us be clear about what we want: to match any of the given field conditions (but not any keyword within a field's condition). So, maybe `:match_fields => :all` as a default, `:match_fields => :any` for the behaviour you're after? Also, avoids the need to parse specific condition values :)
* Have a clear order in which options are applied. `:conditions`, then `:match_fields`, then `:quorum`? That way, `:quorum` is applied reliably to the entire generated query.

How does that sound?

**Comment by dwickwire** [comment]
That sounds great!  How can I help?  I'd be happy to take a stab at this and submit a PR with a little guidance on where to start.

**Comment by pat** [comment]
You're certainly welcome to have a crack at this!

Currently, the search query is generated by `ThinkingSphinx::Search::Query`, and that is called from `ThinkingSphinx::Middlewares::SphinxQL`. The former is reasonably simple at this point in time, so I guess the easiest place to make changes is there - and there's a unit spec file to work with as well.

If you really want to dive in, I think there's opportunity to refactor things more deeply:

* Everything we need to know about is on the search object: `search.query` and `search.options`.
* Add `ThinkingSphinx::Search::QueryBuilder`, which is initialised with the search object and makes local copies of the search object's query and options values (we don't want to muck around with the originals).
* Separate small classes for each possible operation (class filter - which can then be removed from the SphinxQL middleware, wildcarding, field syntax, match fields logic, quorum wrapping), which perhaps have the query builder instance passed to them to operate upon? The finer details of how to implement this I'm not so sure about just yet
* Add a `call` method in the QueryBuilder that calls all these smaller classes, and returns the final string.
* And it'd be really nice to have some specs on QueryBuilder which _do_ use the smaller classes (don't mock them out) to confirm queries are being generated exactly as requested.

That's a lot to think through, of course, and I wouldn't blame you if you opt for the simpler solution! I can ponder the larger refactoring at another stage :)

**Comment by pat** [comment]
As part of some tidying up of my open source repos, I'm going to close this issue - I'm still open to a PR for this, but given it's not a feature that I've had others requesting, I'm not going to spend the time on it myself. Further comments/code are very much welcome though!
