### ISSUE TITLE
Indexing multiple items per record

### ISSUE THREAD

**Issue by nartz** [pat/thinking-sphinx#985]
I have a BlogPost table, but instead of indexing the entire post, I want to split the post_body up into sentences and then index each sentence individually - is there any way to do something like this without having to create an entire other table that i index separately?

**Comment by pat** [comment]
Thinking Sphinx is built to expect a model instance is represented by a single Sphinx document - so yes, you'd need a separate model/table at the sentence level, I'm afraid.
