### ISSUE TITLE
search for primary key on real time index

### ISSUE THREAD

**Issue by palidanx** [pat/thinking-sphinx#987]
I have some code to make sure an item is in the index and I call

mis = MasterIngredient.search '', :with=>{:id=>1}

But when I switched over to the real time index, this no longer works.  What is the correct way to query by the primary key (id) of an object?

**Comment by pat** [comment]
Hi Dan

Thinking Sphinx creates an internal attribute for this purpose, named `sphinx_internal_id`:

```ruby
mis = MasterIngredient.search :with => {:sphinx_internal_id => 1}
```

Any further questions, do let me know!

**Comment by palidanx** [comment]
thank you!
