### ISSUE TITLE
Application wide search does not work?

### ISSUE THREAD

**Issue by khanimdad** [pat/thinking-sphinx#988]
Using thinking-sphinx 3.1.3
I have several models, here i am taking example of only two, Book and Author.

When i do Thinking ThinkingSphinx.search('heinlein') it returns only the matching books and movies but not matching author "Robert A. Heinlein" which is in my DB, even when i do ThinkingSphinx.search('Robert A. Heinlein') it does not return the author.

And there is also error when specify the class name 

irb(main):012:0> ThinkingSphinx.search('Heinlein', :classes => [Author])
   (0.4ms)  SELECT DISTINCT artist_type
FROM artists

  Sphinx  Retrying query "SELECT * FROM `artist_core` WHERE MATCH('Heinlein @sphinx_internal_class_name (Author)') AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META" after error: no enabled local indexes to search - SELECT * FROM `artist_core` WHERE MATCH('Heinlein @sphinx_internal_class_name (Author)') AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META
  Sphinx  Retrying query "SELECT * FROM `artist_core` WHERE MATCH('Heinlein @sphinx_internal_class_name (Author)') AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META" after error: no enabled local indexes to search - SELECT * FROM `artist_core` WHERE MATCH('Heinlein @sphinx_internal_class_name (Author)') AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META
  Sphinx Query (6.4ms)  SELECT * FROM `artist_core` WHERE MATCH('Heinlein @sphinx_internal_class_name (Author)') AND `sphinx_deleted` = 0 LIMIT 0, 20
ThinkingSphinx::SphinxError: no enabled local indexes to search - SELECT * FROM `artist_core` WHERE MATCH('Heinlein @sphinx_internal_class_name (Author)') AND `sphinx_deleted` = 0 LIMIT 0, 20; SHOW META

**Comment by pat** [comment]
Is Author a subclass of Artist? And do you have an index defined on either of those models? Both?

**Comment by khanimdad** [comment]
Yes Author is a subclass of Artist and i have defined index on Artist, as below.

ThinkingSphinx::Index.define :artist, :with => :active_record do
  indexes title#, :sortable => true
  indexes ntitle
  indexes search_keywords
  set_property :enable_star => true
  set_property :min_infix_len => 1 
  set_property :morphology => 'stem_en'
  # attributes
  has youtoo_popularity, created_at, updated_at
end

Apart from Author, Artist also other subclasses.

**Comment by pat** [comment]
Okay. It looks like the Rails app is picking up the index without any issues, but Sphinx isn't aware of it. Have you run `rake ts:rebuild` since adding that index definition?

**Comment by khanimdad** [comment]
Yes, the record is very old, and i always run rake ts:rebuild

**Comment by pat** [comment]
Does searching on Author directly work, as opposed to a global search? What about searching on Artist?

And do you have the output from a full indexing run on hand? I'm curious as to whether there are any errors processing the artist_core index (which would explain why Sphinx doesn't have it available for searches).

**Comment by khanimdad** [comment]
Not sure how i can i run it for Artist, but when i do ThinkingSphinx.search('Heinlein', :classes => [Artist]) it returns error as stated above.

FYI: I also a method Artist#search

**Comment by pat** [comment]
Sorry, yes, I should have been more clear - I meant `Artist.search('Heinlein')` and `Author.search('Heinlein')`. If neither of those work, then it sounds like your index files either have been loaded by Sphinx and then corrupted, or Sphinx hasn't loaded them for some reason. Does running `rake ts:index` help at all? And if not, can you run `rake ts:rebuild` and let me know what the output is?

**Comment by khanimdad** [comment]
Thanks pat i have fixed it, the issue was the field "search_keywords" was not available in DB while artist_index.rb had "indexes search_keywords", so i removed this and things are working find.

Thank you so much for helping out :)

**Comment by pat** [comment]
No worries, good to know it's working again :)
