### ISSUE TITLE
Index or regenerate for real time?

### ISSUE THREAD

**Issue by victorngkp** [pat/thinking-sphinx#990]
Hi @pat. I am using real time indexes. I have a few questions:

1. Every day I schedule to run `thinking_sphinx:regenerate` to reindex everything. Should I just use `thinking_sphinx:index` instead?

2. After each deployment, do we actually need to restart thinking sphinx?

Thanks.

**Comment by pat** [comment]
Hi Victor

1. Just run `ts:generate` (which is the real-time equivalent of `ts:index`).
2. If you've configured all Sphinx paths (for the configuration file, the index files, etc) to live in shared directories (as covered in [the deployment docs](http://freelancing-gods.com/thinking-sphinx/deployment.html)) then no, you don't need to restart Sphinx after each deployment.

Hope this helps!

**Comment by victorngkp** [comment]
Thanks.
