### ISSUE TITLE
Field search with star: true not working as expected

### ISSUE THREAD

**Issue by codez** [pat/thinking-sphinx#997]
The following call does not work as expected: 

    Person.search("@name john @town new", star: true)

results in:

    @name *john* @*town* *new*

I would expect

    @name *john* @town *new*

**Comment by pat** [comment]
Thanks for pointing this out - just fixed it in 1d997f5fc1678ae4603d83990fa1aed8d6ae8af9.

**Comment by codez** [comment]
Thank you very much for the quick fix and for maintaining this great library!
