### ISSUE TITLE
Getting 'Record IDs found by Sphinx but not by ActiveRecord'

### ISSUE THREAD

**Issue by jonsgold** [pat/thinking-sphinx#999]
Hi Pat, I'm getting this error all the time: 

`ActionView::Template::Error (Record IDs found by Sphinx but not by ActiveRecord : long-list-of-ids )`

I have a hunch that it is caused in part by the index of my comment model:

```
class Comment < ActiveRecord::Base
  belongs_to :commenter, polymorphic: true
  belongs_to :user
  ...
end

ThinkingSphinx::Index.define :comment, with: :active_record, delta: ThinkingSphinx::Deltas::ResqueDelta do
  where "accounts.status='enabled'"

  indexes body

  has id, as: :id_number
  has updated_at
  has commenter_id
  has commenter_type
  has user.id
  has user.account_id, as: :account_id
  has user.account.status, as: :account_status
end
```

I noticed that searching might be returning comments from different accounts, not only the account of the user performing the search. I can't be certain, though, as I don't know to which objects `long-list-of-ids` refers in the error message.

Am I right in my hunch? What can I do to fix this problem?

Thanks,
Jonathan

**Comment by pat** [comment]
Hi Jonathan,

I don't think it's related to any mismatch of account/comment data - though it sounds like you're searching across multiple models? Otherwise, the ids supplied are going to be comment ids.

The underlying error is a `ThinkingSphinx::Search::StaleIdsException` - wrapped inside a template error, I guess - and this crops up when data has been removed from your database without the corresponding removal from Sphinx. The latter happens if ActiveRecord callbacks are fired - so, is there anywhere you're deleting indexed objects in a way that doesn't ensure callbacks are invoked?

**Comment by jonsgold** [comment]
Yes, I am searching across multiple models, but via comments. That means, I collect the comment IDs then in code translate the results to the polymorphic parents (the `commenter`). I had to do that because comments on parents with many comments would not show on searches due to the property `group_concat_max_len: 8192` set in the parent index.

We do soft deleting, not removal of the row from the DB. Could the problem be the comment belongs to a "deleted" parent? Is there any way to know to which objects the IDs refer?

**Comment by pat** [comment]
Soft deleting should be okay… TS uses an unscoped relation to query for records, so default scopes (if they're in play here) won't have any affect.

As for figuring out which objects - I'd recommend you take a failing query, and run it in the console with the same arguments, but for each model separately.

Or am I misunderstanding things, and you're searching on comments via Sphinx, and then you have your own code that finds the commenters for each comment? If this is what's happening, then the ids in the error are comment ids, and somehow those comments don't exist in your database anymore but are still in Sphinx.

**Comment by jonsgold** [comment]
Yes, that is what I do with comments. However, I found that in one error message all the IDs are from another table, not comments. TS found the objects, but didn't find them in the DB. I ran a query myself in the DB and found all the objects.

Why is there a query to the DB?

**Comment by pat** [comment]
When a search happens, TS sends a query to Sphinx, gets back the raw Sphinx data, and then makes a query to your database to translate the Sphinx results into ActiveRecord objects. The error you're seeing is TS saying "Sphinx returned records with ids x, y and z, but they're not in the database". The fact that you're saying they _are_ in the database makes this rather confusing!

Can you share the code you're running for the search and the corresponding retrieval of commenter objects?

Also, it might be worth looking at your app's logs to see both the SphinxQL statement being executed in Sphinx, and then ActiveRecord's SQL query to retrieve the comments… if you can post both of those here, that'd be helpful too :)

**Comment by jonsgold** [comment]
Sorry for the trouble Pat, I found the problem. We are using a fork of thinking-sphinx that filters out some of the results when users don't have the permissions to view them (with CanCan). Therefore the ActiveRecord query always returns less results than the sphinx query for these users.

**Comment by pat** [comment]
Ah, well it's good to know the cause of the problem! Hopefully applying the permissions filter isn't too complex and can become part of the search call as well?

**Comment by jonsgold** [comment]
It's worth checking. How would I add the permissions to the sphinx query?

**Comment by pat** [comment]
Can you talk me through the logic you're using to figure out if a user has access to a comment? How is this permission structure managed in your database?

**Comment by jonsgold** [comment]
We have roles for users, each role can have many permissions or restrictions for each object type. So for example, a user of role X can create and view only tickets he himself opened. A user of role admin can see all tickets. Tickets have comments, so for each type of comment parent, I check the user's permissions to filter out tickets he cannot view.

**Comment by pat** [comment]
I have a feeling this might be too complex to bring into Sphinx… how dynamic are roles (do they get added/changed/removed often?) How many roles are there? Can a user have different restriction levels for different object types?

One potential option is to have an attribute `user_ids` with all non-admin users who have access to the comment, and filter on it when you're a non-admin user. Depending on how your roles are being used, though, this could mean a _lot_ of users have access? And having those user ids available through an association may be tricky? If you were to go down this path, caching/denormalising these ids in an array column might save some querying/index structuring hassle.

**Comment by pat** [comment]
But also, as floated in #1001, it might be worth searching across all possible commenter_type classes instead of searching on comments and then translating comment results to their corresponding commenters. This would mean defining search indices on each of these models if you haven't already.

**Comment by jonsgold** [comment]
Roles aren't changed that often, and there are maybe tens of roles. A user can have different restrictions for different types.

Yes, many users (hundreds) can have access. I don't think this is a viable solution for me.

As for https://github.com/pat/thinking-sphinx/issues/1001, I already have indices for the commenter_type classes. I had previously included comments in those indices, but for a couple of reasons I removed comments into a separate index.

**Comment by pat** [comment]
Hmm… not sure I have any inspiration on how this could work.

But, I'm still surprised this error came up - the initial Sphinx and SQL queries made by TS should be unfiltered (and thus, no error). Is CanCan or something else filtering out results under the hood in a monkey-patched approach?

If we can get past this error, then you could manually filter out search results that aren't allowed. Granted, that'd screw up any pagination on search results (though perhaps that's not important in this scenario?).

**Comment by jonsgold** [comment]
Yes, after Sphinx returns with results, we use CanCan to filter out the non-permissible ActiveRecord results. When the discrepancy is small, the stale retries solves the problem. However, when the difference is large, we still have the discrepancy and hence the exception.

A quick and dirty solution would be just returning the results instead of raising the exception. I'd prefer a more holistic approach, though.

**Comment by pat** [comment]
I just want to make sure I'm understanding this correctly… is this the order of operations here?

1. Use Thinking Sphinx for searching on comments
2. Get commenter objects for each comment
3. Use CanCan to filter out non-permissible commenters

**Comment by pat** [comment]
(With the stale ids error coming in at step one?)

**Comment by jonsgold** [comment]
This is the order:

1. Use TS to search on comments
2. Use CanCan to filter out non-permissible commenters from the Sphinx results (in our monkey patched TS gem)
3. Get commenter objects for each comment, since we aren't interested in comments as search results

The stale ids error occurs in step 2.

**Comment by jonsgold** [comment]
OK, thanks for all your help, Pat.
